//! zone-maps — forge lab 02 (columnspaces).
//!
//! Per-block statistics (min, max, null count) and a pruning planner over
//! run-length-encoded blocks. Lab 01 made the column small; this lab makes
//! most of it unread. Lab 03 executes over the blocks that survive.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/zone_maps.rs   (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.             │
//! └────────────────────────────────────────────────────────────────┘
//!
//! What the harness is, in one paragraph: an independent second
//! implementation plus a ground truth. It re-derives every min, max and
//! null count from the block's rows with its own code, and it decides every
//! block's fate twice — once with its own conservative planner, and once by
//! actually scanning every row for a match. A student's planner is graded
//! against the scan, not against their own statistics, so wrong statistics
//! cannot excuse a wrong skip.
//!
//! The asymmetry, which is the entire subject of the lab, is graded the way
//! it behaves in production:
//!
//!   * `no_false_negatives` is PASS/FAIL with zero tolerance. Skipping a
//!     block that contained a matching row is a silent wrong answer.
//!   * `prunes_target` is a BAND. Reading a block that held nothing is only
//!     a bill — but a planner that never skips is not a planner, so the
//!     band has a floor as well as a ceiling.
//!
//! Cost here is a COUNT — blocks read, rows read — never a clock, which is
//! why this suite means the same thing in the terminal and in the browser.
//!
//! BTreeMap only, never HashMap: std's HashMap seeds itself from OS
//! randomness that does not exist on `wasm32-unknown-unknown`.

mod zone_maps;

use kslab::{Check, Report};
use std::collections::BTreeMap;
use zone_maps::{Block, BlockMeta, Predicate, Run, Stats};

/* --------------------------- determinism ---------------------------- */

/// xorshift64* — the same tables and the same predicates on every machine,
/// every run, in both wasm and native. Seeded per check so one failure
/// cannot move another check's data.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        if n == 0 { 0 } else { (self.next() % n as u64) as usize }
    }
}

/* ----------------------- the reference model ------------------------ */
/* A second implementation of the pinned semantics. Every expectation the   */
/* checks compare against comes from here, not from the student's crate.    */

/// Maximal runs — the encoded form a block arrives in.
fn rle(values: &[Option<i64>]) -> Vec<Run> {
    let mut runs: Vec<Run> = Vec::new();
    for &v in values {
        match runs.last_mut() {
            Some((last, count)) if *last == v => *count += 1,
            _ => runs.push((v, 1)),
        }
    }
    runs
}

/// The rows a run list holds. A run of count 0 holds none.
fn expand(runs: &[Run]) -> Vec<Option<i64>> {
    let mut out = Vec::new();
    for &(v, count) in runs {
        for _ in 0..count {
            out.push(v);
        }
    }
    out
}

/// The zone map, derived from ROWS: min/max over non-null values only,
/// absent together when the block holds no non-null value.
fn ref_stats(values: &[Option<i64>]) -> Stats {
    let (mut min, mut max, mut null_count) = (None::<i64>, None::<i64>, 0u32);
    for &v in values {
        match v {
            None => null_count += 1,
            Some(x) => {
                min = Some(min.map_or(x, |m| if x < m { x } else { m }));
                max = Some(max.map_or(x, |m| if x > m { x } else { m }));
            }
        }
    }
    Stats { min, max, null_count }
}

/// GROUND TRUTH, at row level: three-valued logic, in which a null is not
/// comparable to anything. This function is the definition every skip is
/// judged against.
fn ref_matches(value: Option<i64>, pred: &Predicate) -> bool {
    let v = match value {
        None => return matches!(pred, Predicate::IsNull(_)),
        Some(v) => v,
    };
    match pred {
        Predicate::Ge(_, k) => v >= *k,
        Predicate::Gt(_, k) => v > *k,
        Predicate::Le(_, k) => v <= *k,
        Predicate::Lt(_, k) => v < *k,
        Predicate::Eq(_, k) => v == *k,
        Predicate::Between(_, lo, hi) => v >= *lo && v <= *hi,
        Predicate::IsNull(_) => false,
        Predicate::IsNotNull(_) => true,
    }
}

/// The reference planner: read unless the metadata PROVES the block cannot
/// match. Soundness of this function is asserted against `ref_matches` on
/// every block of every corpus below — a false negative in the harness
/// would be worse than one in a student's lab.
fn ref_might_read(meta: &BlockMeta, pred: &Predicate) -> bool {
    let s = match meta.stats.get(pred.column()) {
        Some(Some(s)) => *s,
        // no entry for the column, or the writer recorded nothing: nothing
        // is provable, so the bytes get fetched
        _ => return true,
    };
    match pred {
        Predicate::IsNull(_) => s.null_count > 0,
        Predicate::IsNotNull(_) => s.null_count < meta.row_count,
        _ => {
            let (min, max) = match (s.min, s.max) {
                (Some(min), Some(max)) => (min, max),
                // no non-null value in the block: no comparison can match
                _ => return false,
            };
            match pred {
                Predicate::Ge(_, k) => max >= *k,
                Predicate::Gt(_, k) => max > *k,
                Predicate::Le(_, k) => min <= *k,
                Predicate::Lt(_, k) => min < *k,
                Predicate::Eq(_, k) => min <= *k && *k <= max,
                Predicate::Between(_, lo, hi) => lo <= hi && max >= *lo && min <= *hi,
                Predicate::IsNull(_) | Predicate::IsNotNull(_) => unreachable!(),
            }
        }
    }
}

fn ref_meta(block_values: &[Vec<Option<i64>>]) -> BlockMeta {
    BlockMeta {
        row_count: block_values.first().map(|c| c.len()).unwrap_or(0) as u32,
        stats: block_values.iter().map(|c| Some(ref_stats(c))).collect(),
    }
}

/// Predicates in the messages read like SQL, because "Gt(0, 1700000000512)"
/// is not a diagnosis.
fn pred_str(p: &Predicate) -> String {
    match p {
        Predicate::Ge(c, k) => format!("col{c} >= {k}"),
        Predicate::Gt(c, k) => format!("col{c} > {k}"),
        Predicate::Le(c, k) => format!("col{c} <= {k}"),
        Predicate::Lt(c, k) => format!("col{c} < {k}"),
        Predicate::Eq(c, k) => format!("col{c} == {k}"),
        Predicate::Between(c, lo, hi) => format!("col{c} BETWEEN {lo} AND {hi}"),
        Predicate::IsNull(c) => format!("col{c} IS NULL"),
        Predicate::IsNotNull(c) => format!("col{c} IS NOT NULL"),
    }
}

fn shape(p: &Predicate) -> &'static str {
    match p {
        Predicate::Ge(..) => ">=",
        Predicate::Gt(..) => ">",
        Predicate::Le(..) => "<=",
        Predicate::Lt(..) => "<",
        Predicate::Eq(..) => "==",
        Predicate::Between(..) => "between",
        Predicate::IsNull(..) => "is null",
        Predicate::IsNotNull(..) => "is not null",
    }
}

/// One decimal place, computed in integers: no floating point crosses the
/// wasm boundary in this course.
fn ratio(numer: u64, denom: u64) -> String {
    if denom == 0 {
        return "n/a".to_string();
    }
    let tenths = numer * 10 / denom;
    format!("{}.{}", tenths / 10, tenths % 10)
}

fn percent(part: usize, whole: usize) -> String {
    if whole == 0 {
        return "n/a".to_string();
    }
    let tenths = part as u64 * 1000 / whole as u64;
    format!("{}.{}%", tenths / 10, tenths % 10)
}

/* ------------------------------ layouts ----------------------------- */
/* A table is values first and blocks second — the whole lesson is that the  */
/* same values in a different physical order prune differently.             */

struct Layout {
    name: String,
    /// block → column → the rows themselves. The harness's ground truth.
    blocks: Vec<Vec<Vec<Option<i64>>>>,
}

impl Layout {
    /// Chunk column-major values into blocks of `rpb` rows.
    fn new(name: String, cols: &[Vec<Option<i64>>], rpb: usize) -> Layout {
        let rows = cols.first().map(|c| c.len()).unwrap_or(0);
        let mut blocks = Vec::new();
        let mut lo = 0;
        while lo < rows {
            let hi = (lo + rpb).min(rows);
            blocks.push(cols.iter().map(|c| c[lo..hi].to_vec()).collect());
            lo = hi;
        }
        Layout { name, blocks }
    }

    /// A block holding no rows at all: legal metadata, and provably
    /// impossible under every predicate including IS NULL.
    fn with_empty_block(mut self, at: usize) -> Layout {
        let ncols = self.ncols();
        let at = at.min(self.blocks.len());
        self.blocks.insert(at, vec![Vec::new(); ncols]);
        self
    }

    fn ncols(&self) -> usize {
        self.blocks.first().map(|b| b.len()).unwrap_or(0)
    }

    fn rows(&self) -> usize {
        self.blocks.iter().map(|b| b.first().map(|c| c.len()).unwrap_or(0)).sum()
    }

    /// The encoded blocks handed to the student's `block_meta`.
    fn encoded(&self) -> Vec<Block> {
        self.blocks
            .iter()
            .map(|b| Block { columns: b.iter().map(|c| rle(c)).collect() })
            .collect()
    }

    fn ref_metas(&self) -> Vec<BlockMeta> {
        self.blocks.iter().map(|b| ref_meta(b)).collect()
    }

    fn student_metas(&self) -> Vec<BlockMeta> {
        self.encoded().iter().map(zone_maps::block_meta).collect()
    }

    /// (min, max) over the whole column — the range predicates are drawn
    /// from, so that a generated predicate is sometimes selective and
    /// sometimes matches nothing at all.
    fn col_range(&self, col: usize) -> (Option<i64>, Option<i64>) {
        let mut all = Vec::new();
        for b in &self.blocks {
            if let Some(c) = b.get(col) {
                all.extend(c.iter().copied());
            }
        }
        let s = ref_stats(&all);
        (s.min, s.max)
    }

    /// GROUND TRUTH: the first row of block `b` that satisfies `pred`, if
    /// any. Computed by scanning every row — the only authority on whether
    /// a skip was legal.
    fn first_match(&self, b: usize, pred: &Predicate) -> Option<(usize, Option<i64>)> {
        let col = self.blocks[b].get(pred.column())?;
        col.iter().enumerate().find(|(_, &v)| ref_matches(v, pred)).map(|(i, &v)| (i, v))
    }
}

/* --------------------------- column shapes -------------------------- */

/// Monotone timestamps: the clustered case, and the reason zone maps work.
fn col_ts(rng: &mut Rng, n: usize) -> Vec<Option<i64>> {
    let mut t = 1_700_000_000_000i64 + rng.below(1 << 20) as i64;
    (0..n)
        .map(|_| {
            t = t.wrapping_add(1 + rng.below(97) as i64);
            Some(t)
        })
        .collect()
}

/// Random ids over a narrow span: uncorrelated with row order, which is
/// what a secondary column looks like once the table is sorted by another.
fn col_ids(rng: &mut Rng, n: usize, span: usize) -> Vec<Option<i64>> {
    (0..n).map(|_| Some(rng.below(span) as i64)).collect()
}

fn col_all_null(n: usize) -> Vec<Option<i64>> {
    vec![None; n]
}

fn col_constant(rng: &mut Rng, n: usize) -> Vec<Option<i64>> {
    let v = rng.below(1000) as i64;
    vec![Some(v); n]
}

fn col_flags(rng: &mut Rng, n: usize) -> Vec<Option<i64>> {
    (0..n).map(|_| Some(rng.below(2) as i64)).collect()
}

/// Long runs of nulls beside long runs of values: the shape a column added
/// by a schema migration has, and the one that makes `null_count` matter.
fn col_null_runs(rng: &mut Rng, n: usize) -> Vec<Option<i64>> {
    let mut out = Vec::with_capacity(n);
    while out.len() < n {
        let v = if rng.below(3) == 0 { None } else { Some(rng.below(50) as i64) };
        let len = (1 + rng.below(40)).min(n - out.len());
        for _ in 0..len {
            out.push(v);
        }
    }
    out
}

/// Values at the edges of i64, where a range test written with arithmetic
/// instead of comparisons overflows.
fn col_extremes(rng: &mut Rng, n: usize) -> Vec<Option<i64>> {
    (0..n)
        .map(|_| match rng.below(5) {
            0 => Some(i64::MIN),
            1 => Some(i64::MAX),
            2 => Some(0),
            3 => None,
            _ => Some(rng.next() as i64),
        })
        .collect()
}

/// Shuffle inside windows of `group` rows. With `group == rows_per_block`
/// nothing changes; with `group == the whole table` every block spans the
/// whole range and pruning is impossible. This one knob is clustering
/// depth, and it is the only difference between the two rows of the table
/// in C0.L4.
fn shuffle_within(rng: &mut Rng, col: &mut [Option<i64>], group: usize) {
    if group < 2 {
        return;
    }
    let mut lo = 0;
    while lo < col.len() {
        let hi = (lo + group).min(col.len());
        for i in (lo + 1..hi).rev() {
            let j = lo + rng.below(i - lo + 1);
            col.swap(i, j);
        }
        lo = hi;
    }
}

fn sprinkle_nulls(rng: &mut Rng, col: &mut [Option<i64>], one_in: usize) {
    if one_in == 0 {
        return;
    }
    for v in col.iter_mut() {
        if rng.below(one_in) == 0 {
            *v = None;
        }
    }
}

/// The corpus. Ten families, each of which breaks a different planner bug;
/// `i` selects the family and the sizes so that fifteen layouts are not
/// fifteen copies of one table.
fn make_layout(rng: &mut Rng, i: usize) -> Layout {
    let rpb = [16usize, 32, 64, 128][i % 4];
    let nblocks = 4 + (i * 3) % 13;
    let n = rpb * nblocks;
    match i % 10 {
        // clustered on col0, uncorrelated col1: one physical order, two
        // predicates, and only one of them prunes
        0 => {
            let cols = vec![col_ts(rng, n), col_ids(rng, n, 64)];
            Layout::new(format!("clustered ts (depth 1), {nblocks}×{rpb}"), &cols, rpb)
        }
        // the same values, shuffled: every block spans the whole range
        1 => {
            let mut ts = col_ts(rng, n);
            shuffle_within(rng, &mut ts, n);
            let cols = vec![ts, col_ids(rng, n, 64)];
            Layout::new(format!("shuffled ts (depth {nblocks}), {nblocks}×{rpb}"), &cols, rpb)
        }
        // clustering depth 4: partial pruning, the realistic middle
        2 => {
            let mut ts = col_ts(rng, n);
            shuffle_within(rng, &mut ts, rpb * 4);
            let cols = vec![ts, col_flags(rng, n)];
            Layout::new(format!("ts at clustering depth 4, {nblocks}×{rpb}"), &cols, rpb)
        }
        // an all-null column beside a live one: comparisons prune it,
        // IS NULL emphatically does not
        3 => {
            let cols = vec![col_all_null(n), col_ts(rng, n)];
            Layout::new(format!("col0 all null, {nblocks}×{rpb}"), &cols, rpb)
        }
        // nulls in long runs over a clustered column
        4 => {
            let mut ts = col_ts(rng, n);
            sprinkle_nulls(rng, &mut ts, 6);
            let cols = vec![ts, col_null_runs(rng, n)];
            Layout::new(format!("clustered ts with 1-in-6 nulls, {nblocks}×{rpb}"), &cols, rpb)
        }
        // a constant column: min == max, every equality either hits every
        // block or none of them
        5 => {
            let cols = vec![col_constant(rng, n), col_ids(rng, n, 8)];
            Layout::new(format!("constant col0, {nblocks}×{rpb}"), &cols, rpb)
        }
        // i64 edges
        6 => {
            let cols = vec![col_extremes(rng, n), col_ts(rng, n)];
            Layout::new(format!("i64 extremes, {nblocks}×{rpb}"), &cols, rpb)
        }
        // descending: sorted, but the other way, which catches a min/max
        // swap that ascending data hides
        7 => {
            let mut ts = col_ts(rng, n);
            ts.reverse();
            let cols = vec![ts, col_null_runs(rng, n)];
            Layout::new(format!("descending ts, {nblocks}×{rpb}"), &cols, rpb)
        }
        // three columns, clustered on col1 rather than col0
        8 => {
            let cols = vec![col_ids(rng, n, 1000), col_ts(rng, n), col_all_null(n)];
            Layout::new(format!("3 cols, clustered on col1, {nblocks}×{rpb}"), &cols, rpb)
                .with_empty_block(1)
        }
        // one row per block, plus an empty block: every off-by-one lives here
        _ => {
            let mut ts = col_ts(rng, 24);
            sprinkle_nulls(rng, &mut ts, 4);
            let cols = vec![ts, col_flags(rng, 24)];
            Layout::new("1 row per block + an empty block".to_string(), &cols, 1)
                .with_empty_block(3)
        }
    }
}

/// A predicate over `layout`, drawn so that the mix contains selective
/// windows, predicates no block can satisfy, and predicates every block
/// satisfies. All eight shapes appear.
fn make_predicate(rng: &mut Rng, layout: &Layout, i: usize) -> Predicate {
    let ncols = layout.ncols().max(1);
    let col = rng.below(ncols);
    let (min, max) = layout.col_range(col);
    let pick = |rng: &mut Rng| -> i64 {
        match (min, max) {
            (Some(min), Some(max)) => {
                let span = (max as u64).wrapping_sub(min as u64);
                match rng.below(8) {
                    // outside the range on either side: everything prunes
                    0 => min.wrapping_sub(1 + rng.below(1000) as i64),
                    1 => max.wrapping_add(1 + rng.below(1000) as i64),
                    // a boundary value: the off-by-one in every range test
                    2 => min,
                    3 => max,
                    _ => {
                        let off = if span == u64::MAX { rng.next() } else { rng.next() % (span + 1) };
                        (min as u64).wrapping_add(off) as i64
                    }
                }
            }
            // an all-null column has no range to draw from
            _ => rng.next() as i64,
        }
    };
    match i % 8 {
        0 => Predicate::Ge(col, pick(rng)),
        1 => Predicate::Gt(col, pick(rng)),
        2 => Predicate::Le(col, pick(rng)),
        3 => Predicate::Lt(col, pick(rng)),
        4 => Predicate::Eq(col, pick(rng)),
        5 => {
            let (a, b) = (pick(rng), pick(rng));
            // one in eight is deliberately self-contradicting (hi < lo)
            if rng.below(8) == 0 { Predicate::Between(col, a.max(b), a.min(b)) } else { Predicate::Between(col, a.min(b), a.max(b)) }
        }
        6 => Predicate::IsNull(col),
        _ => Predicate::IsNotNull(col),
    }
}

/* ------------------------------ checks ------------------------------ */

/// 1. stats_exact: min, max and null count are facts about the ROWS of a
///    block, computed from its encoded runs. All-null blocks have no min or
///    max — and `None` there means "there is no such value", never "I did
///    not look".
pub fn check_stats_exact() -> Check {
    const ID: &str = "stats_exact";
    const LABEL: &str = "per-block min/max/null-count exact, including all-null blocks";
    let mut rng = Rng(0x2011_5747);

    // hand cases, where the expected numbers are obvious by eye
    let hand: Vec<(&str, Vec<Run>)> = vec![
        ("no runs", vec![]),
        ("one value", vec![(Some(42), 1)]),
        ("one null", vec![(None, 1)]),
        ("all null (64 rows, one run)", vec![(None, 64)]),
        ("all null (many runs)", vec![(None, 5), (None, 7), (None, 1)]),
        ("constant", vec![(Some(-9), 300)]),
        ("ascending", vec![(Some(1), 2), (Some(5), 3), (Some(9), 1)]),
        ("descending", vec![(Some(9), 1), (Some(5), 3), (Some(1), 2)]),
        ("min last, max first", vec![(Some(100), 1), (Some(50), 1), (Some(-7), 1)]),
        ("values around a null run", vec![(Some(3), 2), (None, 40), (Some(-3), 2)]),
        ("negative only", vec![(Some(-100), 3), (Some(-5), 4)]),
        ("i64 edges", vec![(Some(i64::MAX), 1), (None, 2), (Some(i64::MIN), 1)]),
        ("count-0 run below the min", vec![(Some(-999_999), 0), (Some(10), 3), (Some(20), 2)]),
        ("count-0 run above the max", vec![(Some(10), 3), (Some(999_999), 0)]),
        ("count-0 null run", vec![(None, 0), (Some(7), 4)]),
        ("only count-0 runs", vec![(Some(1), 0), (None, 0)]),
        ("null run of 1000", vec![(Some(0), 1), (None, 1000)]),
    ];
    for (name, runs) in &hand {
        let rows = expand(runs);
        let want = ref_stats(&rows);
        let got = zone_maps::column_stats(runs);
        if got.min != want.min {
            return Check::fail(ID, LABEL, format!(
                "{name}: min is {:?}, want {:?} — min is the SMALLEST non-null value in the block, over rows and not over runs (a run with count 0 holds no rows), and it is None only when there is no non-null value at all. A min that is not a true lower bound is a false-negative generator: the planner will prove a block impossible with a bound that was never a bound.",
                got.min, want.min));
        }
        if got.max != want.max {
            return Check::fail(ID, LABEL, format!(
                "{name}: max is {:?}, want {:?} — max is the LARGEST non-null value in the block; runs of count 0 contribute nothing",
                got.max, want.max));
        }
        if got.null_count != want.null_count {
            return Check::fail(ID, LABEL, format!(
                "{name}: null_count is {}, want {} — it counts null ROWS, so a null run of count c contributes c (and a run of count 0 contributes nothing)",
                got.null_count, want.null_count));
        }
        if got.min.is_some() != got.max.is_some() {
            return Check::fail(ID, LABEL, format!(
                "{name}: min {:?} and max {:?} disagree about whether the block has any non-null value — they are absent together or present together",
                got.min, got.max));
        }
    }

    // and over real blocks, through block_meta
    let mut blocks_checked = 0usize;
    for i in 0..10 {
        let layout = make_layout(&mut rng, i);
        let encoded = layout.encoded();
        let want = layout.ref_metas();
        for (b, block) in encoded.iter().enumerate() {
            let got = zone_maps::block_meta(block);
            let w = &want[b];
            if got.row_count != w.row_count {
                return Check::fail(ID, LABEL, format!(
                    "{} block {b}: row_count {} , want {} — every column of a block expands to the same number of rows, and the count is the sum of the run counts",
                    layout.name, got.row_count, w.row_count));
            }
            if got.stats.len() != w.stats.len() {
                return Check::fail(ID, LABEL, format!(
                    "{} block {b}: {} column stats for {} columns — the planner indexes this by column id, so a short vector means later columns silently have no statistics",
                    layout.name, got.stats.len(), w.stats.len()));
            }
            for (c, (g, wa)) in got.stats.iter().zip(&w.stats).enumerate() {
                match g {
                    None => {
                        return Check::fail(ID, LABEL, format!(
                            "{} block {b} col{c}: stats recorded as None. None means \"the writer recorded nothing\", which forbids the planner from ever pruning this column — you computed the statistics, so record Some(..). (Being unable to prune is not a correctness bug; it is the bill, which is what prunes_target measures.)",
                            layout.name));
                    }
                    Some(g) if g != wa.as_ref().unwrap() => {
                        return Check::fail(ID, LABEL, format!(
                            "{} block {b} col{c}: {:?}, want {:?}",
                            layout.name, g, wa.unwrap()));
                    }
                    _ => {}
                }
            }
            blocks_checked += 1;
        }
    }
    Check::pass(ID, LABEL, format!(
        "{} hand columns and {blocks_checked} real blocks exact — all-null blocks report min/max absent with null_count == row_count, count-0 runs contribute nothing",
        hand.len()))
}

/// 2. no_false_negatives: the absolute. Every block that contains a row
///    satisfying the predicate must be read, under every predicate shape,
///    including metadata that cannot speak to the question at all.
pub fn check_no_false_negatives() -> Check {
    const ID: &str = "no_false_negatives";
    const LABEL: &str = "never skips a block that contains a matching row — under every predicate";
    let mut rng = Rng(0xFA15_E1FF);

    // the planner and the per-block decision are two answers to one
    // question; they must never disagree
    let probe = make_layout(&mut rng, 0);
    let metas = probe.student_metas();
    for p in [Predicate::Ge(0, 0), Predicate::IsNull(1), Predicate::Between(0, -5, 5)] {
        let plan = zone_maps::plan(&metas, &p);
        if plan.read.len() != metas.len() {
            return Check::fail(ID, LABEL, format!(
                "plan returned {} decisions for {} blocks — a block with no decision is a block that is never read, which is a false negative by omission",
                plan.read.len(), metas.len()));
        }
        for (b, meta) in metas.iter().enumerate() {
            if plan.read[b] != zone_maps::might_read(meta, &p) {
                return Check::fail(ID, LABEL, format!(
                    "{}: plan and might_read disagree about block {b} under {} — two answers to the same question is how a fast path and a correct path drift apart",
                    probe.name, pred_str(&p)));
            }
        }
    }
    if !zone_maps::plan(&[], &Predicate::Ge(0, 0)).read.is_empty() {
        return Check::fail(ID, LABEL, "plan over zero blocks must return zero decisions");
    }

    // metadata that cannot speak to the predicate: nothing is provable, so
    // the block is read. Both cases are graded against a block that DOES
    // contain a match, so a wrong answer here is a genuine lost row.
    let rows = vec![Some(1), None, Some(9)];
    let full = ref_stats(&rows);
    let cases: Vec<(&str, BlockMeta)> = vec![
        ("the writer recorded no statistics for the column", BlockMeta { row_count: 3, stats: vec![None] }),
        ("the metadata has no entry for the column at all", BlockMeta { row_count: 3, stats: vec![] }),
        ("statistics for col0 only, predicate on col1", BlockMeta { row_count: 3, stats: vec![Some(full)] }),
    ];
    for (name, meta) in &cases {
        let col = if meta.stats.len() > 1 { 0 } else { meta.stats.len() };
        for p in [
            Predicate::Ge(col, 0),
            Predicate::Gt(col, -100),
            Predicate::Le(col, 100),
            Predicate::Lt(col, 100),
            Predicate::Eq(col, 9),
            Predicate::Between(col, -100, 100),
            Predicate::IsNull(col),
            Predicate::IsNotNull(col),
        ] {
            if !zone_maps::might_read(meta, &p) {
                return Check::fail(ID, LABEL, format!(
                    "{name}: skipped under {} — no statistics is NOT a proof of absence. The block holds {rows:?}, every one of these predicates matches one of those rows, and the skip returns a wrong answer with no error. When the metadata cannot speak, you read the block and pay the bill.",
                    pred_str(&p)));
            }
        }
    }

    // the corpus: every block of every layout, against every predicate,
    // judged by scanning the rows
    let mut shapes: BTreeMap<&'static str, usize> = BTreeMap::new();
    let (mut decisions, mut must_read, mut read) = (0usize, 0usize, 0usize);
    for i in 0..15 {
        let layout = make_layout(&mut rng, i);
        let metas = layout.student_metas();
        let refs = layout.ref_metas();
        for j in 0..40 {
            let pred = make_predicate(&mut rng, &layout, j);
            *shapes.entry(shape(&pred)).or_insert(0) += 1;
            let plan = zone_maps::plan(&metas, &pred);
            if plan.read.len() != metas.len() {
                return Check::fail(ID, LABEL, format!(
                    "{}: plan returned {} decisions for {} blocks", layout.name, plan.read.len(), metas.len()));
            }
            for b in 0..metas.len() {
                decisions += 1;
                if plan.read[b] {
                    read += 1;
                }
                let truth = layout.first_match(b, &pred);
                // the harness auditing itself: a reference false negative
                // would silently excuse a student's
                if truth.is_some() && !ref_might_read(&refs[b], &pred) {
                    return Check::fail(ID, LABEL, format!(
                        "HARNESS BUG: the reference planner would skip {} block {b} under {} even though it contains a match — please report this",
                        layout.name, pred_str(&pred)));
                }
                if let Some((row, value)) = truth {
                    must_read += 1;
                    if !plan.read[b] {
                        return Check::fail(ID, LABEL, format!(
                            "FALSE NEGATIVE — {}: block {b} was skipped under {}, but row {row} of that block holds {value:?}, which matches. Your metadata for the block: row_count {}, col{} stats {:?} (the truth is {:?}). This is not a cost bug: the query returns a plausible wrong number and nothing anywhere reports an error. Skip only when the statistics PROVE the block impossible.",
                            layout.name, pred_str(&pred),
                            metas[b].row_count, pred.column(),
                            metas[b].stats.get(pred.column()),
                            refs[b].stats.get(pred.column())));
                    }
                }
            }
        }
    }
    let mix: Vec<String> = shapes.iter().map(|(k, v)| format!("{k} {v}")).collect();
    Check::pass(ID, LABEL, format!(
        "{decisions} block decisions, {must_read} of them mandatory, {read} blocks read — zero false negatives. Predicate mix: {}. Metadata with no statistics, and metadata missing the column, are read rather than skipped.",
        mix.join(", ")))
}

/// 3. prunes_target: the band. A planner that never skips has no false
///    negatives and is still useless, so the pruning ratio on clustered
///    data is graded against the reference planner — from below (you must
///    prune what is provable) and from above (you may not skip what is not).
pub fn check_prunes_target() -> Check {
    const ID: &str = "prunes_target";
    const LABEL: &str = "pruning ratio within band of the reference planner on clustered data";
    let mut rng = Rng(0x9805_C0DE);

    // what is provably impossible must actually be pruned — these four are
    // where "never skip" dies
    let sorted: Vec<Option<i64>> = (0..64).map(|i| Some(i as i64)).collect();
    let nulls = col_all_null(64);
    let mixed: Vec<Option<i64>> = (0..64).map(|i| if i % 2 == 0 { None } else { Some(i as i64) }).collect();
    let must_prune: Vec<(&str, Vec<Vec<Option<i64>>>, Predicate, &str)> = vec![
        ("values 0..63, predicate above all of them", vec![sorted.clone()], Predicate::Gt(0, 63),
         "max is 63, so no row can exceed it"),
        ("values 0..63, predicate below all of them", vec![sorted.clone()], Predicate::Lt(0, 0),
         "min is 0, so no row can be smaller"),
        ("values 0..63, equality outside the range", vec![sorted.clone()], Predicate::Eq(0, 100),
         "100 is outside [0, 63]"),
        ("values 0..63, a self-contradicting range", vec![sorted.clone()], Predicate::Between(0, 40, 10),
         "BETWEEN 40 AND 10 matches nothing, anywhere: hi < lo"),
        ("values 0..63, a range entirely above them", vec![sorted.clone()], Predicate::Between(0, 64, 200),
         "the block's range [0, 63] does not intersect [64, 200]"),
        ("an all-null block, comparison", vec![nulls.clone()], Predicate::Ge(0, 0),
         "no non-null value exists, and NULL >= 0 is UNKNOWN, which is not a match"),
        ("an all-null block, equality", vec![nulls.clone()], Predicate::Eq(0, 0),
         "same proof: min and max are absent because there is nothing to compare"),
        ("an all-null block, IS NOT NULL", vec![nulls.clone()], Predicate::IsNotNull(0),
         "null_count == row_count, so no row is non-null"),
        ("a block with no nulls, IS NULL", vec![sorted.clone()], Predicate::IsNull(0),
         "null_count == 0"),
        ("an empty block, IS NULL", vec![Vec::new()], Predicate::IsNull(0),
         "no rows means no null rows"),
        ("half-null block, predicate above the max", vec![mixed.clone()], Predicate::Gt(0, 63),
         "the nulls do not extend the range: max is 63"),
    ];
    for (name, block, pred, why) in &must_prune {
        let layout = Layout { name: name.to_string(), blocks: vec![block.clone()] };
        let metas = layout.student_metas();
        if zone_maps::might_read(&metas[0], pred) {
            return Check::fail(ID, LABEL, format!(
                "{name}: read under {} — {why}, so this block is PROVABLY impossible and its bytes should never be requested. Reading it is not a wrong answer, it is a wrong bill; a planner that reads everything has no false negatives and no purpose. Your stats: {:?}, row_count {}.",
                pred_str(pred), metas[0].stats.first(), metas[0].row_count));
        }
    }

    // the C0.L4 measurement, rebuilt: the same values in two physical
    // orders, one predicate, and the ratio between the rows each reads
    let (nblocks, rpb) = (64usize, 64usize);
    let n = nblocks * rpb;
    let ts = col_ts(&mut rng, n);
    let mut shuffled = ts.clone();
    shuffle_within(&mut rng, &mut shuffled, n);
    let ids = col_ids(&mut rng, n, 128);
    let clustered = Layout::new("clustered by timestamp".into(), &[ts.clone(), ids.clone()], rpb);
    let scattered = Layout::new("the same rows, written shuffled".into(), &[shuffled, ids], rpb);

    // 40 selective windows over the clustered layout: each covers roughly
    // one block's worth of the range, which is what a seven-day predicate
    // over two years of data looks like
    let (lo_ts, hi_ts) = (ts[0].unwrap(), ts[n - 1].unwrap());
    let span = (hi_ts - lo_ts) as u64;
    let window = span / nblocks as u64;
    let mut preds = Vec::new();
    for j in 0..40usize {
        let start = lo_ts + (rng.next() % span.max(1)) as i64;
        preds.push(match j % 4 {
            0 => Predicate::Between(0, start, start + window as i64),
            1 => Predicate::Ge(0, hi_ts - window as i64),
            2 => Predicate::Lt(0, lo_ts + window as i64),
            _ => Predicate::Eq(0, start),
        });
    }

    let totals = |layout: &Layout| -> Result<(usize, usize, u64, u64), String> {
        let metas = layout.student_metas();
        let refs = layout.ref_metas();
        let (mut you, mut theirs, mut your_rows, mut their_rows) = (0usize, 0usize, 0u64, 0u64);
        for pred in &preds {
            let plan = zone_maps::plan(&metas, pred);
            if plan.read.len() != metas.len() {
                return Err(format!("plan returned {} decisions for {} blocks", plan.read.len(), metas.len()));
            }
            let ref_read: Vec<bool> = refs.iter().map(|m| ref_might_read(m, pred)).collect();
            for b in 0..metas.len() {
                if ref_read[b] && !plan.read[b] {
                    return Err(format!(
                        "{}: block {b} was skipped under {}, but its statistics do not prove it impossible (col{} range {:?}, null_count {}). That block happens {} to contain a match — but a skip that is not backed by a proof is a false negative waiting for different data, so it fails here too.",
                        layout.name, pred_str(pred), pred.column(),
                        refs[b].stats[pred.column()].map(|s| (s.min, s.max)),
                        refs[b].stats[pred.column()].map(|s| s.null_count).unwrap_or(0),
                        if layout.first_match(b, pred).is_some() { "in fact" } else { "not" }));
                }
            }
            you += plan.blocks_read();
            theirs += ref_read.iter().filter(|&&r| r).count();
            your_rows += plan.rows_read(&metas);
            their_rows += ref_read
                .iter()
                .zip(&refs)
                .filter(|(r, _)| **r)
                .map(|(_, m)| m.row_count as u64)
                .sum::<u64>();
        }
        Ok((you, theirs, your_rows, their_rows))
    };

    let (you, theirs, your_rows, their_rows) = match totals(&clustered) {
        Ok(t) => t,
        Err(msg) => return Check::fail(ID, LABEL, msg),
    };
    let all_blocks = nblocks * preds.len();
    // the ceiling: conservative is allowed, 20% plus slack of conservative
    // is not. The reference is the maximally-pruning SOUND planner, so this
    // band is entirely about your proofs being sharp enough.
    let budget = theirs + theirs / 5 + 2;
    if you > budget {
        return Check::fail(ID, LABEL, format!(
            "clustered by timestamp, {} selective predicates over {nblocks} blocks: you read {you} blocks ({your_rows} rows), the reference planner reads {theirs} ({their_rows} rows), and the band ends at {budget}. You fetch {} of all {all_blocks} block-decisions where the reference fetches {}. If you read all {all_blocks}, you have written a planner that never skips: that has zero false negatives and zero value — the whole mechanism is the proof by contradiction against min/max. Check the boundary cases (max < k versus max <= k) and that Between uses BOTH bounds.",
            preds.len(), percent(you, all_blocks), percent(theirs, all_blocks)));
    }

    let (s_you, s_theirs, s_rows, _) = match totals(&scattered) {
        Ok(t) => t,
        Err(msg) => return Check::fail(ID, LABEL, msg),
    };
    Check::pass(ID, LABEL, format!(
        "{} provably-impossible blocks pruned; {} selective predicates over the same {n} rows in two physical orders — clustered: {you} of {all_blocks} blocks read ({} pruned, reference {}); shuffled: {s_you} of {all_blocks} ({} pruned, reference {}) — {}× the rows ({s_rows} vs {your_rows}) for an identical answer, from write order alone",
        must_prune.len(), preds.len(),
        percent(all_blocks - you, all_blocks), percent(all_blocks - theirs, all_blocks),
        percent(all_blocks - s_you, all_blocks), percent(all_blocks - s_theirs, all_blocks),
        ratio(s_rows, your_rows.max(1))))
}

/// 4. null_semantics: NULL is not comparable. `IS NULL` consults the null
///    count, `IS NOT NULL` compares it against the row count, and every
///    other shape needs a non-null value to exist before it can match.
pub fn check_null_semantics() -> Check {
    const ID: &str = "null_semantics";
    const LABEL: &str = "IS NULL / IS NOT NULL and null-vs-predicate handled correctly";

    // row-level three-valued logic, exhaustively over a small grid
    let values = [None, Some(i64::MIN), Some(-1), Some(0), Some(5), Some(6), Some(i64::MAX)];
    let ks = [i64::MIN, -1, 0, 5, 6, i64::MAX];
    let mut preds: Vec<Predicate> = Vec::new();
    for &k in &ks {
        preds.extend([
            Predicate::Ge(0, k),
            Predicate::Gt(0, k),
            Predicate::Le(0, k),
            Predicate::Lt(0, k),
            Predicate::Eq(0, k),
        ]);
        for &k2 in &ks {
            preds.push(Predicate::Between(0, k, k2));
        }
    }
    preds.push(Predicate::IsNull(0));
    preds.push(Predicate::IsNotNull(0));
    for &v in &values {
        for p in &preds {
            let (got, want) = (zone_maps::row_matches(v, p), ref_matches(v, p));
            if got != want {
                let why = match (v, p) {
                    (None, Predicate::IsNull(_)) => "a null row is exactly what IS NULL matches",
                    (None, Predicate::IsNotNull(_)) => "a null row is not a non-null row",
                    (None, _) => "every comparison against NULL is UNKNOWN, and UNKNOWN is not a match — treating NULL as a very small (or very large) number is how null rows leak into a range answer",
                    (Some(_), Predicate::IsNull(_)) => "a non-null row does not satisfy IS NULL",
                    (Some(_), Predicate::Between(_, lo, hi)) if hi < lo => "BETWEEN hi < lo is a self-contradicting predicate: lo <= v && v <= hi is false for every v",
                    _ => "compare the value against the bound with the operator the shape names, and nothing else",
                };
                return Check::fail(ID, LABEL, format!(
                    "row_matches({v:?}, {}) is {got}, want {want} — {why}",
                    pred_str(p)));
            }
        }
    }

    // block-level: the same semantics, one level up, against synthesized
    // metadata so that "no statistics" is distinguishable from "no values"
    let all_null = Stats { min: None, max: None, null_count: 64 };
    let no_nulls = Stats { min: Some(1), max: Some(9), null_count: 0 };
    let some_nulls = Stats { min: Some(1), max: Some(9), null_count: 7 };
    let empty = Stats { min: None, max: None, null_count: 0 };
    let cases: Vec<(&str, BlockMeta, Predicate, bool, &str)> = vec![
        ("all-null block", BlockMeta { row_count: 64, stats: vec![Some(all_null)] }, Predicate::IsNull(0), true,
         "null_count is 64: every row satisfies IS NULL. A planner that returns early on min.is_none() skips exactly the blocks IS NULL is looking for, and drops every null row in the table."),
        ("all-null block", BlockMeta { row_count: 64, stats: vec![Some(all_null)] }, Predicate::IsNotNull(0), false,
         "null_count == row_count, so no row is non-null: provably impossible"),
        ("all-null block", BlockMeta { row_count: 64, stats: vec![Some(all_null)] }, Predicate::Gt(0, 5), false,
         "there is no non-null value to compare, and NULL > 5 is UNKNOWN: provably impossible"),
        ("all-null block", BlockMeta { row_count: 64, stats: vec![Some(all_null)] }, Predicate::Between(0, i64::MIN, i64::MAX), false,
         "even the widest range matches no null row"),
        ("no-null block", BlockMeta { row_count: 64, stats: vec![Some(no_nulls)] }, Predicate::IsNull(0), false,
         "null_count is 0: provably impossible"),
        ("no-null block", BlockMeta { row_count: 64, stats: vec![Some(no_nulls)] }, Predicate::IsNotNull(0), true,
         "64 rows, none of them null"),
        ("part-null block", BlockMeta { row_count: 64, stats: vec![Some(some_nulls)] }, Predicate::IsNull(0), true,
         "null_count is 7"),
        ("part-null block", BlockMeta { row_count: 64, stats: vec![Some(some_nulls)] }, Predicate::IsNotNull(0), true,
         "57 of the 64 rows are non-null"),
        ("part-null block", BlockMeta { row_count: 64, stats: vec![Some(some_nulls)] }, Predicate::Gt(0, 9), false,
         "the seven nulls do not widen the range: max is 9"),
        ("part-null block", BlockMeta { row_count: 64, stats: vec![Some(some_nulls)] }, Predicate::Ge(0, 9), true,
         "max is 9 and the predicate is inclusive — this is the >= versus > boundary"),
        ("part-null block", BlockMeta { row_count: 64, stats: vec![Some(some_nulls)] }, Predicate::Lt(0, 1), false,
         "min is 1 and the predicate is strict"),
        ("part-null block", BlockMeta { row_count: 64, stats: vec![Some(some_nulls)] }, Predicate::Le(0, 1), true,
         "min is 1 and the predicate is inclusive"),
        ("empty block", BlockMeta { row_count: 0, stats: vec![Some(empty)] }, Predicate::IsNull(0), false,
         "no rows means no null rows"),
        ("empty block", BlockMeta { row_count: 0, stats: vec![Some(empty)] }, Predicate::IsNotNull(0), false,
         "null_count == row_count == 0"),
        ("block with no statistics", BlockMeta { row_count: 64, stats: vec![None] }, Predicate::IsNull(0), true,
         "None is not a null count of zero — it is no information, and no information proves nothing"),
        ("block with no statistics", BlockMeta { row_count: 64, stats: vec![None] }, Predicate::IsNotNull(0), true,
         "same: the writer recorded nothing, so the bytes get fetched"),
    ];
    for (name, meta, pred, want, why) in &cases {
        let got = zone_maps::might_read(meta, pred);
        if got != *want {
            let verb = if *want { "read" } else { "pruned" };
            return Check::fail(ID, LABEL, format!(
                "{name} under {}: you {} it, it must be {verb} — {why}",
                pred_str(pred), if got { "read" } else { "pruned" }));
        }
    }

    // and against ground truth on null-heavy layouts, where IS NULL and
    // IS NOT NULL are asked about every block
    let mut rng = Rng(0x4E55_4C4C);
    let (mut is_null_read, mut is_null_total) = (0usize, 0usize);
    for i in [3usize, 4, 7, 9, 6] {
        let layout = make_layout(&mut rng, i);
        let metas = layout.student_metas();
        for col in 0..layout.ncols() {
            for pred in [Predicate::IsNull(col), Predicate::IsNotNull(col)] {
                let plan = zone_maps::plan(&metas, &pred);
                if plan.read.len() != metas.len() {
                    return Check::fail(ID, LABEL, format!(
                        "{}: plan returned {} decisions for {} blocks", layout.name, plan.read.len(), metas.len()));
                }
                for b in 0..metas.len() {
                    let truth = layout.first_match(b, &pred);
                    if truth.is_some() && !plan.read[b] {
                        let (row, value) = truth.unwrap();
                        return Check::fail(ID, LABEL, format!(
                            "FALSE NEGATIVE — {}: block {b} skipped under {}, but row {row} holds {value:?}. Your stats for col{col}: {:?}, row_count {}.",
                            layout.name, pred_str(&pred),
                            metas[b].stats.get(col), metas[b].row_count));
                    }
                    if matches!(pred, Predicate::IsNull(_)) {
                        is_null_total += 1;
                        if plan.read[b] {
                            is_null_read += 1;
                        }
                    }
                }
            }
        }
    }
    Check::pass(ID, LABEL, format!(
        "{} row-level (value, predicate) pairs and {} block-level cases exact; IS NULL read {is_null_read} of {is_null_total} blocks across five null-heavy layouts — all-null blocks are pruned by comparisons and read by IS NULL, which is the pair of answers that cannot come from one branch",
        values.len() * preds.len(), cases.len()))
}

/// 5. storm: 1500 seeded predicate/layout combinations. Zero false
///    negatives against ground truth, no skip that the reference cannot
///    prove, and a total read count within 2% of the reference planner's.
pub fn check_storm() -> Check {
    const ID: &str = "storm";
    const LABEL: &str = "1500 seeded predicate/layout combinations vs a reference planner";
    let mut rng = Rng(0x5EED_2011);
    const LAYOUTS: usize = 15;
    const PREDS: usize = 100;

    let mut shapes: BTreeMap<&'static str, usize> = BTreeMap::new();
    let (mut you, mut theirs, mut all) = (0usize, 0usize, 0usize);
    let (mut your_rows, mut their_rows, mut total_rows) = (0u64, 0u64, 0u64);
    let (mut must_read, mut combos) = (0usize, 0usize);
    let mut overread: BTreeMap<&'static str, usize> = BTreeMap::new();

    for i in 0..LAYOUTS {
        let layout = make_layout(&mut rng, i);
        let metas = layout.student_metas();
        let refs = layout.ref_metas();
        // the student's statistics must agree with the reference's before
        // their planner's decisions mean anything
        if metas != refs {
            let b = (0..metas.len().min(refs.len())).find(|&b| metas[b] != refs[b]);
            return Check::fail(ID, LABEL, format!(
                "{}: block_meta disagrees with the reference{} — fix stats_exact first; a planner reasoning from wrong statistics is not a planner",
                layout.name,
                b.map(|b| format!(" at block {b}: {:?} vs {:?}", metas[b], refs[b])).unwrap_or_default()));
        }
        let layout_rows: u64 = layout.rows() as u64;
        for j in 0..PREDS {
            let pred = make_predicate(&mut rng, &layout, j);
            *shapes.entry(shape(&pred)).or_insert(0) += 1;
            combos += 1;
            let plan = zone_maps::plan(&metas, &pred);
            if plan.read.len() != metas.len() {
                return Check::fail(ID, LABEL, format!(
                    "{}: plan returned {} decisions for {} blocks", layout.name, plan.read.len(), metas.len()));
            }
            for b in 0..metas.len() {
                let ref_read = ref_might_read(&refs[b], &pred);
                let truth = layout.first_match(b, &pred);
                if truth.is_some() && !ref_read {
                    return Check::fail(ID, LABEL, format!(
                        "HARNESS BUG: the reference planner would skip {} block {b} under {} despite a match — please report this",
                        layout.name, pred_str(&pred)));
                }
                if let Some((row, value)) = truth {
                    must_read += 1;
                    if !plan.read[b] {
                        return Check::fail(ID, LABEL, format!(
                            "FALSE NEGATIVE — {}: block {b} skipped under {}, but row {row} holds {value:?}. Statistics for col{}: {:?}. A skipped block that held a match is a silent wrong answer, and no amount of pruning ratio buys it back.",
                            layout.name, pred_str(&pred), pred.column(),
                            refs[b].stats.get(pred.column())));
                    }
                }
                if ref_read && !plan.read[b] {
                    return Check::fail(ID, LABEL, format!(
                        "UNPROVABLE SKIP — {}: block {b} skipped under {}, and its statistics (col{} range {:?}, null_count {:?}, row_count {}) do not prove it impossible. It held no match this time; the same code on tomorrow's data returns the wrong answer. Skipping is only legal as a proof.",
                        layout.name, pred_str(&pred), pred.column(),
                        refs[b].stats.get(pred.column()).and_then(|s| s.map(|s| (s.min, s.max))),
                        refs[b].stats.get(pred.column()).and_then(|s| s.map(|s| s.null_count)),
                        refs[b].row_count));
                }
                if plan.read[b] && !ref_read {
                    *overread.entry(shape(&pred)).or_insert(0) += 1;
                }
                all += 1;
            }
            you += plan.blocks_read();
            theirs += refs.iter().filter(|m| ref_might_read(m, &pred)).count();
            your_rows += plan.rows_read(&metas);
            their_rows += refs
                .iter()
                .filter(|m| ref_might_read(m, &pred))
                .map(|m| m.row_count as u64)
                .sum::<u64>();
            total_rows += layout_rows;
        }
    }

    // the band: conservative is correct, so this is generous — but 2% over
    // the reference across 1500 combinations means a proof is missing, not
    // that you were careful once.
    let budget = theirs + theirs / 50 + 2;
    if you > budget {
        let worst = overread.iter().max_by_key(|(_, v)| **v).map(|(k, v)| format!("{k} ({v} blocks)")).unwrap_or_default();
        return Check::fail(ID, LABEL, format!(
            "{combos} combinations: you read {you} blocks, the reference planner reads {theirs}, and the band ends at {budget}. Most of the excess is on the {worst} shape. Every block in the excess is one your statistics could have proven impossible — a bill, not a wrong answer, which is why this is a band and no_false_negatives is not."));
    }
    let mix: Vec<String> = shapes.iter().map(|(k, v)| format!("{k} {v}")).collect();
    Check::pass(ID, LABEL, format!(
        "{combos} combinations over {LAYOUTS} layouts / {all} block decisions model-exact — {must_read} mandatory reads all honoured, {you} blocks read against the reference's {theirs}, {your_rows} of {total_rows} rows touched ({} pruned; the reference touches {their_rows}). Mix: {}.",
        percent((total_rows - your_rows) as usize, total_rows as usize), mix.join(", ")))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_stats_exact(),
        check_no_false_negatives(),
        check_prunes_target(),
        check_null_semantics(),
        check_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "zone-maps", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
