//! parquet-reader — forge lab 04 (columnspaces).
//!
//! A footer parser and column-chunk reader over KSPQ: a small,
//! Parquet-SHAPED teaching format that this harness defines, writes and
//! reads. **It is not Parquet.** The format spec, and the list of what real
//! Parquet has that KSPQ deliberately omits (Thrift metadata, pages,
//! definition/repetition levels, codecs, several physical types, a schema
//! tree, column/offset indexes, the trailing magic), is in the header of
//! `src/parquet_reader.rs`. The course does not overclaim: what this lab
//! teaches is the SHAPE — metadata at the end, byte ranges per column
//! chunk, projection as arithmetic, and refusing malformed input.
//!
//! ┌──────────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/parquet_reader.rs  (the only file with TODO(you))   │
//! │  DO NOT EDIT this file — it is the grading harness.                   │
//! └──────────────────────────────────────────────────────────────────────┘
//!
//! What the harness is:
//!
//!   * a WRITER that generates files deterministically and keeps a ledger:
//!     the exact byte range of every column chunk, and the exact values it
//!     encoded there. Expectations come from the ledger, not from the
//!     student's parser;
//!   * a second, independent READER, used by `storm` — and audited against
//!     the ledger on every fixture, failing with "HARNESS BUG" if the two
//!     disagree;
//!   * an INSTRUMENTED `Source` that records every `(offset, len)` the
//!     student requests. `projection_reads_minimum` is graded from that
//!     recording as a COUNT of bytes and ranges — never a time. The
//!     assertion is not "fewer bytes than the whole file": it is ZERO bytes
//!     of any chunk the projection did not name.
//!
//! BTreeMap only, never HashMap: std's HashMap seeds itself from OS
//! randomness that does not exist on `wasm32-unknown-unknown`.

mod parquet_reader;

use kslab::{Check, Report};
use parquet_reader::{
    ChunkMeta, ChunkStats, ColumnMeta, Error, FileMeta, Logical, RowGroupMeta, Source,
};
use std::cell::RefCell;
use std::collections::BTreeMap;

/* --------------------------- determinism ---------------------------- */

/// xorshift64* — the same files and the same read plans on every machine,
/// every run, in both wasm and native.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        if n == 0 { 0 } else { (self.next() % n as u64) as usize }
    }
}

/* ------------------------------ the writer -------------------------- */

const MAGIC: [u8; 4] = *b"KSPQ";
const VERSION: u16 = 1;

fn put_u16(out: &mut Vec<u8>, v: u16) {
    out.extend_from_slice(&v.to_le_bytes());
}
fn put_u32(out: &mut Vec<u8>, v: u32) {
    out.extend_from_slice(&v.to_le_bytes());
}
fn put_u64(out: &mut Vec<u8>, v: u64) {
    out.extend_from_slice(&v.to_le_bytes());
}
fn put_i64(out: &mut Vec<u8>, v: i64) {
    out.extend_from_slice(&v.to_le_bytes());
}

/// The payload of one column chunk: `u32 n`, a null bitmap, then `n` i64s.
/// A null row stores 0, which is why the bitmap and not the value decides
/// nullity — and why a reader that infers nulls from zeros turns every
/// legitimate zero in the file into a NULL.
fn encode_chunk(values: &[Option<i64>]) -> Vec<u8> {
    let n = values.len();
    let mut out = Vec::with_capacity(4 + (n + 7) / 8 + n * 8);
    put_u32(&mut out, n as u32);
    let mut bitmap = vec![0u8; (n + 7) / 8];
    for (i, v) in values.iter().enumerate() {
        if v.is_none() {
            bitmap[i / 8] |= 1 << (i % 8);
        }
    }
    out.extend_from_slice(&bitmap);
    for v in values {
        put_i64(&mut out, v.unwrap_or(0));
    }
    out
}

/// The zone map a writer records, over non-null values. `None` when the
/// chunk holds no non-null value: there is nothing to bound.
fn chunk_stats(values: &[Option<i64>]) -> Option<ChunkStats> {
    let live: Vec<i64> = values.iter().filter_map(|v| *v).collect();
    let null_count = (values.len() - live.len()) as u32;
    Some(ChunkStats { min: *live.iter().min()?, max: *live.iter().max()?, null_count })
}

/// A generated file, plus the ledger that makes it gradeable.
struct Fixture {
    name: String,
    bytes: Vec<u8>,
    /// GROUND TRUTH metadata, as written.
    meta: FileMeta,
    /// GROUND TRUTH values: `[row_group][column][row]`.
    values: Vec<Vec<Vec<Option<i64>>>>,
    /// Where the footer begins — the whole tail region is legal to read.
    footer_start: u64,
}

impl Fixture {
    /// The full column, concatenated across row groups: what `project`
    /// must return for that column.
    fn column(&self, c: usize) -> Vec<Option<i64>> {
        self.values.iter().flat_map(|rg| rg[c].iter().copied()).collect()
    }

    fn ncols(&self) -> usize {
        self.meta.schema.len()
    }

    /// The byte ranges a projection is allowed to touch: the magic, the
    /// whole footer region, and the named columns' chunks. Everything else
    /// in the file is forbidden — including other columns' chunks, which is
    /// the point of the check.
    fn allowed(&self, columns: &[usize]) -> Vec<(u64, u64)> {
        let mut out = vec![(0u64, 4u64), (self.footer_start, self.bytes.len() as u64)];
        for rg in &self.meta.row_groups {
            for &c in columns {
                if let Some(ch) = rg.chunks.get(c) {
                    out.push((ch.offset, ch.offset + ch.len));
                }
            }
        }
        out
    }

    /// Bytes of the chunks a projection must NOT touch, as ranges.
    fn forbidden(&self, columns: &[usize]) -> Vec<(usize, usize, u64, u64)> {
        let mut out = Vec::new();
        for (g, rg) in self.meta.row_groups.iter().enumerate() {
            for (c, ch) in rg.chunks.iter().enumerate() {
                if !columns.contains(&c) {
                    out.push((g, c, ch.offset, ch.offset + ch.len));
                }
            }
        }
        out
    }
}

/// Write a KSPQ file from `[row_group][column][row]` values and a schema.
/// Data first (row-group-major), then the footer, then the footer length.
fn write_file(name: String, schema: Vec<ColumnMeta>, values: Vec<Vec<Vec<Option<i64>>>>, stats: bool) -> Fixture {
    let ncols = schema.len();
    let mut bytes = Vec::new();
    bytes.extend_from_slice(&MAGIC);
    let mut row_groups: Vec<RowGroupMeta> = Vec::new();
    let mut num_rows = 0u64;
    for rg in &values {
        let row_count = rg.first().map(|c| c.len()).unwrap_or(0);
        num_rows += row_count as u64;
        let mut chunks = Vec::with_capacity(ncols);
        for col in rg.iter() {
            let payload = encode_chunk(col);
            let offset = bytes.len() as u64;
            bytes.extend_from_slice(&payload);
            chunks.push(ChunkMeta {
                offset,
                len: payload.len() as u64,
                stats: if stats { chunk_stats(col) } else { None },
            });
        }
        row_groups.push(RowGroupMeta { row_count: row_count as u32, chunks });
    }

    let meta = FileMeta { version: VERSION, num_rows, schema, row_groups };
    let footer = encode_footer(&meta);
    let footer_start = bytes.len() as u64;
    bytes.extend_from_slice(&footer);
    put_u32(&mut bytes, footer.len() as u32);
    Fixture { name, bytes, meta, values, footer_start }
}

fn encode_footer(meta: &FileMeta) -> Vec<u8> {
    let mut f = Vec::new();
    put_u16(&mut f, meta.version);
    put_u64(&mut f, meta.num_rows);
    put_u16(&mut f, meta.schema.len() as u16);
    for col in &meta.schema {
        f.push(col.name.len() as u8);
        f.extend_from_slice(col.name.as_bytes());
        f.push(match col.logical {
            Logical::Int64 => 1,
            Logical::Timestamp => 2,
            Logical::Bool => 3,
        });
    }
    put_u16(&mut f, meta.row_groups.len() as u16);
    for rg in &meta.row_groups {
        put_u32(&mut f, rg.row_count);
        for ch in &rg.chunks {
            put_u64(&mut f, ch.offset);
            put_u64(&mut f, ch.len);
            match ch.stats {
                None => f.push(0),
                Some(s) => {
                    f.push(1);
                    put_i64(&mut f, s.min);
                    put_i64(&mut f, s.max);
                    put_u32(&mut f, s.null_count);
                }
            }
        }
    }
    f
}

/* -------------------------- reference reader ------------------------ */
/* A second implementation, used by storm and audited against the writer's  */
/* ledger on every fixture.                                                */

struct RefCursor<'a> {
    b: &'a [u8],
    p: usize,
}

impl<'a> RefCursor<'a> {
    fn new(b: &'a [u8]) -> RefCursor<'a> {
        RefCursor { b, p: 0 }
    }
    fn take(&mut self, n: usize) -> Result<&'a [u8], String> {
        if self.b.len() - self.p.min(self.b.len()) < n {
            return Err(format!("truncated: need {n}, have {}", self.b.len().saturating_sub(self.p)));
        }
        let o = &self.b[self.p..self.p + n];
        self.p += n;
        Ok(o)
    }
    fn u8(&mut self) -> Result<u8, String> {
        Ok(self.take(1)?[0])
    }
    fn u16(&mut self) -> Result<u16, String> {
        let b = self.take(2)?;
        Ok(u16::from_le_bytes([b[0], b[1]]))
    }
    fn u32(&mut self) -> Result<u32, String> {
        let b = self.take(4)?;
        Ok(u32::from_le_bytes([b[0], b[1], b[2], b[3]]))
    }
    fn u64(&mut self) -> Result<u64, String> {
        let b = self.take(8)?;
        let mut a = [0u8; 8];
        a.copy_from_slice(b);
        Ok(u64::from_le_bytes(a))
    }
}

fn ref_read_footer(bytes: &[u8]) -> Result<FileMeta, String> {
    if (bytes.len() as u64) < 8 {
        return Err("too short".into());
    }
    if bytes[..4] != MAGIC {
        return Err("bad magic".into());
    }
    let len_at = bytes.len() - 4;
    let footer_len = u32::from_le_bytes([bytes[len_at], bytes[len_at + 1], bytes[len_at + 2], bytes[len_at + 3]]) as u64;
    if 4 + footer_len + 4 > bytes.len() as u64 {
        return Err("footer_len does not fit".into());
    }
    let start = bytes.len() as u64 - 4 - footer_len;
    let f = &bytes[start as usize..len_at];
    let mut c = RefCursor::new(f);
    let version = c.u16()?;
    if version != VERSION {
        return Err(format!("bad version {version}"));
    }
    let num_rows = c.u64()?;
    let ncols = c.u16()? as usize;
    let mut schema = Vec::with_capacity(ncols);
    for _ in 0..ncols {
        let nlen = c.u8()? as usize;
        let name = String::from_utf8(c.take(nlen)?.to_vec()).map_err(|_| "bad name".to_string())?;
        let logical = match c.u8()? {
            1 => Logical::Int64,
            2 => Logical::Timestamp,
            3 => Logical::Bool,
            t => return Err(format!("unknown type {t}")),
        };
        schema.push(ColumnMeta { name, logical });
    }
    let ngroups = c.u16()? as usize;
    let mut row_groups = Vec::with_capacity(ngroups);
    for _ in 0..ngroups {
        let row_count = c.u32()?;
        let mut chunks = Vec::with_capacity(ncols);
        for _ in 0..ncols {
            let offset = c.u64()?;
            let len = c.u64()?;
            let stats = match c.u8()? {
                0 => None,
                1 => {
                    let min = c.u64()? as i64;
                    let max = c.u64()? as i64;
                    let null_count = c.u32()?;
                    Some(ChunkStats { min, max, null_count })
                }
                other => return Err(format!("bad has_stats {other}")),
            };
            chunks.push(ChunkMeta { offset, len, stats });
        }
        row_groups.push(RowGroupMeta { row_count, chunks });
    }
    Ok(FileMeta { version, num_rows, schema, row_groups })
}

fn ref_read_chunk(bytes: &[u8], chunk: &ChunkMeta) -> Result<Vec<Option<i64>>, String> {
    let end = chunk.offset.checked_add(chunk.len).ok_or("offset+len overflows")?;
    if end > bytes.len() as u64 {
        return Err("chunk out of bounds".into());
    }
    let payload = &bytes[chunk.offset as usize..end as usize];
    let mut c = RefCursor::new(payload);
    let n = c.u32()? as usize;
    let bitmap = c.take((n + 7) / 8)?.to_vec();
    let mut out = Vec::with_capacity(n);
    for i in 0..n {
        let raw = c.u64()? as i64;
        let null = bitmap[i / 8] & (1 << (i % 8)) != 0;
        out.push(if null { None } else { Some(raw) });
    }
    Ok(out)
}

fn ref_project(bytes: &[u8], meta: &FileMeta, columns: &[usize]) -> Result<Vec<Vec<Option<i64>>>, String> {
    for &c in columns {
        if c >= meta.schema.len() {
            return Err(format!("no such column {c}"));
        }
    }
    let mut out = Vec::with_capacity(columns.len());
    for &c in columns {
        let mut col = Vec::new();
        for rg in &meta.row_groups {
            col.extend(ref_read_chunk(bytes, &rg.chunks[c])?);
        }
        out.push(col);
    }
    Ok(out)
}

/* ------------------------ the instrumented source ------------------- */

/// The grading instrument: a `Source` that answers honestly and remembers
/// every question. `RefCell` because wasm is single threaded and a lock
/// would be theatre.
struct Recording<'a> {
    bytes: &'a [u8],
    reads: RefCell<Vec<(u64, u64)>>,
}

impl<'a> Recording<'a> {
    fn new(bytes: &'a [u8]) -> Recording<'a> {
        Recording { bytes, reads: RefCell::new(Vec::new()) }
    }
    fn reset(&self) {
        self.reads.borrow_mut().clear();
    }
    fn ranges(&self) -> Vec<(u64, u64)> {
        self.reads.borrow().clone()
    }
    fn bytes_requested(&self) -> u64 {
        self.reads.borrow().iter().map(|(_, l)| *l).sum()
    }
    /// Distinct bytes of the file that were touched at least once — a
    /// re-read of the same range is a second request but not a second byte.
    fn distinct_bytes(&self) -> u64 {
        let mut marks = vec![false; self.bytes.len()];
        for (o, l) in self.reads.borrow().iter() {
            for i in *o..(*o + *l).min(self.bytes.len() as u64) {
                marks[i as usize] = true;
            }
        }
        marks.iter().filter(|m| **m).count() as u64
    }
}

impl Source for Recording<'_> {
    fn len(&self) -> u64 {
        self.bytes.len() as u64
    }
    fn read(&self, offset: u64, len: u64) -> Result<Vec<u8>, Error> {
        // recorded FIRST: an out-of-range request is still a request, and a
        // reader that gropes past the end should be visible
        self.reads.borrow_mut().push((offset, len));
        let end = match offset.checked_add(len) {
            Some(e) => e,
            None => return Err(Error::OutOfBounds { offset, len, file_len: self.bytes.len() as u64 }),
        };
        if end > self.bytes.len() as u64 {
            return Err(Error::OutOfBounds { offset, len, file_len: self.bytes.len() as u64 });
        }
        Ok(self.bytes[offset as usize..end as usize].to_vec())
    }
}

/// Bytes the student requested that fall inside a forbidden range, with the
/// first offender named.
fn forbidden_hits(rec: &Recording, fx: &Fixture, columns: &[usize]) -> Option<(usize, usize, u64, u64, u64)> {
    let forbidden = fx.forbidden(columns);
    for (o, l) in rec.ranges() {
        let (rs, re) = (o, o.saturating_add(l));
        for (g, c, fs, fe) in &forbidden {
            let lo = rs.max(*fs);
            let hi = re.min(*fe);
            if lo < hi {
                return Some((*g, *c, *fs, *fe, hi - lo));
            }
        }
    }
    None
}

/// Requested bytes outside the union of allowed ranges — padding, gaps, or
/// anything else nobody asked for. (In a KSPQ file there is no padding, so
/// this only fires on genuinely stray reads.)
fn stray_bytes(rec: &Recording, fx: &Fixture, columns: &[usize]) -> u64 {
    let allowed = fx.allowed(columns);
    let mut stray = 0u64;
    for (o, l) in rec.ranges() {
        for i in o..o.saturating_add(l) {
            if !allowed.iter().any(|(s, e)| i >= *s && i < *e) {
                stray += 1;
            }
        }
    }
    stray
}

/* ---------------------------- formatting ---------------------------- */

fn percent(part: u64, whole: u64) -> String {
    if whole == 0 {
        return "n/a".to_string();
    }
    let tenths = part * 1000 / whole;
    format!("{}.{}%", tenths / 10, tenths % 10)
}

fn vals_str(vs: &[Option<i64>]) -> String {
    if vs.len() <= 8 {
        format!("{vs:?}")
    } else {
        format!("[{:?}, … {} more]", &vs[..6], vs.len() - 6)
    }
}

fn ranges_str(rs: &[(u64, u64)]) -> String {
    let shown: Vec<String> = rs.iter().take(8).map(|(o, l)| format!("[{o}, {})", o + l)).collect();
    if rs.len() > 8 {
        format!("{} … and {} more", shown.join(" "), rs.len() - 8)
    } else if shown.is_empty() {
        "none".to_string()
    } else {
        shown.join(" ")
    }
}

/* --------------------------- column shapes -------------------------- */

fn col_values(rng: &mut Rng, n: usize, kind: usize) -> Vec<Option<i64>> {
    match kind % 7 {
        // monotone timestamps
        0 => {
            let mut t = 1_700_000_000_000i64 + rng.below(1 << 20) as i64;
            (0..n)
                .map(|_| {
                    t = t.wrapping_add(1 + rng.below(97) as i64);
                    Some(t)
                })
                .collect()
        }
        // small ids with 1-in-7 nulls
        1 => (0..n)
            .map(|_| if rng.below(7) == 0 { None } else { Some(rng.below(500) as i64) })
            .collect(),
        // all null: the chunk with no statistics to record
        2 => vec![None; n],
        // zeros and nulls together — the case a reader that infers nullity
        // from the value gets wrong
        3 => (0..n).map(|i| if i % 3 == 0 { None } else { Some(0) }).collect(),
        // booleans
        4 => (0..n).map(|_| Some(rng.below(2) as i64)).collect(),
        // i64 edges
        5 => (0..n)
            .map(|_| match rng.below(5) {
                0 => Some(i64::MIN),
                1 => Some(i64::MAX),
                2 => None,
                3 => Some(0),
                _ => Some(rng.next() as i64),
            })
            .collect(),
        // negative and large
        _ => (0..n).map(|_| Some(-(rng.below(1 << 30) as i64))).collect(),
    }
}

fn logical_for(kind: usize) -> Logical {
    match kind % 7 {
        0 => Logical::Timestamp,
        4 => Logical::Bool,
        _ => Logical::Int64,
    }
}

/// Ten file shapes: different column counts, row-group counts, partial
/// final row groups, all-null columns, statistics present or absent, and
/// the degenerate cases (one row, zero rows, one row group).
fn make_fixture(rng: &mut Rng, i: usize) -> Fixture {
    let ncols = [1usize, 2, 3, 4, 5, 6][i % 6];
    let ngroups = [1usize, 2, 3, 4, 5][i % 5];
    let rows_per_group = [1usize, 7, 32, 64, 100, 257][i % 6];
    // the final row group is deliberately partial in most shapes
    let last = if i % 3 == 0 { rows_per_group } else { 1 + rng.below(rows_per_group) };
    let stats = i % 4 != 3;
    let kinds: Vec<usize> = (0..ncols).map(|c| (i + c * 3) % 7).collect();
    let schema: Vec<ColumnMeta> = kinds
        .iter()
        .enumerate()
        .map(|(c, &k)| ColumnMeta { name: format!("col_{c}"), logical: logical_for(k) })
        .collect();
    let mut values = Vec::with_capacity(ngroups);
    for g in 0..ngroups {
        let rows = if g + 1 == ngroups { last } else { rows_per_group };
        values.push(kinds.iter().map(|&k| col_values(rng, rows, k)).collect());
    }
    let name = format!(
        "{ncols} cols × {ngroups} row groups of {rows_per_group} (last {last}){}",
        if stats { "" } else { ", no statistics recorded" }
    );
    write_file(name, schema, values, stats)
}

/// The awkward shapes, by hand: a file with no row groups at all, a file
/// with a zero-row row group, and a one-value file.
fn edge_fixtures() -> Vec<Fixture> {
    let int = |name: &str| ColumnMeta { name: name.to_string(), logical: Logical::Int64 };
    vec![
        write_file("no row groups (an empty table)".into(), vec![int("a"), int("b")], vec![], true),
        write_file("one row group of zero rows".into(), vec![int("a"), int("b")], vec![vec![vec![], vec![]]], true),
        write_file("one row, one column".into(), vec![int("only")], vec![vec![vec![Some(42)]]], true),
        write_file(
            "one column, all null (no statistics possible)".into(),
            vec![int("nothing")],
            vec![vec![vec![None, None, None]]],
            true,
        ),
        write_file(
            "16 columns, 2 row groups — projection has plenty to avoid".into(),
            (0..16).map(|c| int(&format!("c{c}"))).collect(),
            (0..2)
                .map(|g| (0..16).map(|c| (0..40).map(|r| Some((g * 1000 + c * 40 + r) as i64)).collect()).collect())
                .collect(),
            true,
        ),
    ]
}

/* --------------------------- harness audit -------------------------- */

/// The harness auditing itself: the reference reader must recover exactly
/// what the writer wrote, and the writer's declared chunk ranges must be
/// inside the file and not overlap the footer. If any of this fails, the
/// fixture is unsound and grading a student against it would be worse than
/// grading nothing.
fn audit(fx: &Fixture) -> Result<(), String> {
    let meta = ref_read_footer(&fx.bytes)
        .map_err(|e| format!("HARNESS BUG: the reference reader cannot read the fixture it just wrote ({}): {e} — please report this", fx.name))?;
    if meta != fx.meta {
        return Err(format!(
            "HARNESS BUG: reference footer != written footer for {} — please report this",
            fx.name));
    }
    for (g, rg) in fx.meta.row_groups.iter().enumerate() {
        if rg.chunks.len() != fx.meta.schema.len() {
            return Err(format!("HARNESS BUG: row group {g} of {} has the wrong chunk count — please report this", fx.name));
        }
        for (c, ch) in rg.chunks.iter().enumerate() {
            if ch.offset + ch.len > fx.footer_start {
                return Err(format!(
                    "HARNESS BUG: chunk ({g},{c}) of {} overlaps the footer — please report this",
                    fx.name));
            }
            let got = ref_read_chunk(&fx.bytes, ch)
                .map_err(|e| format!("HARNESS BUG: reference chunk read failed on {} ({g},{c}): {e} — please report this", fx.name))?;
            if got != fx.values[g][c] {
                return Err(format!(
                    "HARNESS BUG: reference chunk ({g},{c}) of {} decodes to something other than what was written — please report this",
                    fx.name));
            }
        }
    }
    Ok(())
}

/* --------------------------- malformed files ------------------------ */

/// A malformed file, the reason it is malformed, and which of the student's
/// entry points must refuse it.
struct Broken {
    name: &'static str,
    why: &'static str,
    bytes: Vec<u8>,
    /// true: `read_footer` must fail. false: the footer is fine and the
    /// failure must appear when the data is read.
    footer_must_fail: bool,
}

fn set_u32(bytes: &mut [u8], at: usize, v: u32) {
    bytes[at..at + 4].copy_from_slice(&v.to_le_bytes());
}
fn set_u64(bytes: &mut [u8], at: usize, v: u64) {
    bytes[at..at + 8].copy_from_slice(&v.to_le_bytes());
}

/// Where the footer's per-row-group chunk table starts, for a fixture whose
/// shape the harness knows: version(2) + num_rows(8) + num_columns(2) +
/// per-column (1 + name + 1) + num_row_groups(2) + row_count(4).
fn first_chunk_field(fx: &Fixture) -> usize {
    let mut p = fx.footer_start as usize + 2 + 8 + 2;
    for col in &fx.meta.schema {
        p += 1 + col.name.len() + 1;
    }
    p + 2 + 4
}

fn broken_files(base: &Fixture) -> Vec<Broken> {
    let ok = &base.bytes;
    let footer_len = (ok.len() as u64 - 4 - base.footer_start) as u32;
    let len_at = ok.len() - 4;
    let mut out = Vec::new();

    out.push(Broken {
        name: "an empty file",
        why: "zero bytes cannot hold magic and a footer length",
        bytes: Vec::new(),
        footer_must_fail: true,
    });
    out.push(Broken {
        name: "a 3-byte file",
        why: "shorter than the magic alone",
        bytes: ok[..3].to_vec(),
        footer_must_fail: true,
    });
    out.push(Broken {
        name: "a 7-byte file (magic, but no room for a footer length)",
        why: "MIN_FILE_LEN is 8: magic plus the length field",
        bytes: ok[..7].to_vec(),
        footer_must_fail: true,
    });
    out.push(Broken {
        name: "wrong magic",
        why: "the first four bytes are not KSPQ — this is how you notice you were handed a CSV, or a Parquet file, or an HTML error page that a proxy substituted for your download",
        bytes: {
            let mut b = ok.clone();
            b[1] = b'X';
            b
        },
        footer_must_fail: true,
    });
    out.push(Broken {
        name: "truncated: the last 40 bytes are gone",
        why: "the classic interrupted upload. The last four bytes are now footer bytes reinterpreted as a length, which will not fit — and if you skip that check you subtract it from the file length and underflow into an enormous offset",
        bytes: ok[..ok.len() - 40].to_vec(),
        footer_must_fail: true,
    });
    out.push(Broken {
        name: "footer_len longer than the file",
        why: "the declared footer does not fit between the magic and the length field",
        bytes: {
            let mut b = ok.clone();
            set_u32(&mut b, len_at, ok.len() as u32 + 1000);
            b
        },
        footer_must_fail: true,
    });
    out.push(Broken {
        name: "footer_len = u32::MAX",
        why: "the arithmetic 4 + footer_len + 4 overflows a u32 and file_len - 4 - footer_len underflows: check with the same width you subtract in, or in u64",
        bytes: {
            let mut b = ok.clone();
            set_u32(&mut b, len_at, u32::MAX);
            b
        },
        footer_must_fail: true,
    });
    out.push(Broken {
        name: "footer_len = 0",
        why: "an empty footer cannot even hold a version",
        bytes: {
            let mut b = ok.clone();
            set_u32(&mut b, len_at, 0);
            b
        },
        footer_must_fail: true,
    });
    out.push(Broken {
        name: "footer_len 5 bytes short of the real footer",
        why: "the footer now starts in the middle of itself: the fields decode into nonsense and then run out. Refuse; do not return the row groups you managed to read",
        bytes: {
            let mut b = ok.clone();
            set_u32(&mut b, len_at, footer_len - 5);
            b
        },
        footer_must_fail: true,
    });
    out.push(Broken {
        name: "version 7",
        why: "a version this reader does not know: the fields after it may mean anything, so a best effort is a guess",
        bytes: {
            let mut b = ok.clone();
            let at = base.footer_start as usize;
            b[at..at + 2].copy_from_slice(&7u16.to_le_bytes());
            b
        },
        footer_must_fail: true,
    });
    out.push(Broken {
        name: "an unknown logical type tag",
        why: "tag 9 is not one of 1..=3 — Logical::from_tag already refuses it, as long as you call it",
        bytes: {
            let mut b = ok.clone();
            // the first column's type tag: after version(2), num_rows(8),
            // num_columns(2), name_len(1) and the name itself
            let at = base.footer_start as usize + 2 + 8 + 2 + 1 + base.meta.schema[0].name.len();
            b[at] = 9;
            b
        },
        footer_must_fail: true,
    });
    out.push(Broken {
        name: "num_columns inflated to 200",
        why: "the footer promises 200 columns and holds a handful: the declaration and the bytes disagree, and the bytes are the authority",
        bytes: {
            let mut b = ok.clone();
            let at = base.footer_start as usize + 2 + 8;
            b[at..at + 2].copy_from_slice(&200u16.to_le_bytes());
            b
        },
        footer_must_fail: true,
    });
    out.push(Broken {
        name: "num_row_groups inflated by 50",
        why: "same disagreement one level down — the chunk table ends before the row groups the footer claims",
        bytes: {
            let mut b = ok.clone();
            let mut at = base.footer_start as usize + 2 + 8 + 2;
            for col in &base.meta.schema {
                at += 1 + col.name.len() + 1;
            }
            let n = base.meta.row_groups.len() as u16 + 50;
            b[at..at + 2].copy_from_slice(&n.to_le_bytes());
            b
        },
        footer_must_fail: true,
    });
    out.push(Broken {
        name: "a chunk offset past the end of the file",
        why: "the footer is well-formed and the DATA pointer is not. Nothing is wrong until you follow it, and following it must be a refusal rather than a read of whatever happens to be there",
        bytes: {
            let mut b = ok.clone();
            set_u64(&mut b, first_chunk_field(base), ok.len() as u64 + 4096);
            b
        },
        footer_must_fail: false,
    });
    out.push(Broken {
        name: "a chunk length that runs past the end of the file",
        why: "offset is fine, offset + len is not — and on a 64-bit offset that addition can overflow, which is why the check is checked arithmetic",
        bytes: {
            let mut b = ok.clone();
            set_u64(&mut b, first_chunk_field(base) + 8, u64::MAX - 8);
            b
        },
        footer_must_fail: false,
    });
    out.push(Broken {
        name: "a chunk whose declared value count needs more bytes than the chunk has",
        why: "n says 100000 values; the chunk is a few hundred bytes. The payload contradicts its own header, so refuse — a reader that returns the values it could decode returns a short column, and a short column silently misaligns every other column in the row",
        bytes: {
            let mut b = ok.clone();
            let chunk_offset = base.meta.row_groups[0].chunks[0].offset as usize;
            set_u32(&mut b, chunk_offset, 100_000);
            b
        },
        footer_must_fail: false,
    });
    out
}

/* ------------------------------ checks ------------------------------ */

/// 1. footer_parse: the magic, the footer length at the end of the file,
///    and the schema — read from files the harness wrote, and compared
///    against the writer's ledger rather than against a second parse.
pub fn check_footer_parse() -> Check {
    const ID: &str = "footer_parse";
    const LABEL: &str = "magic, footer length and schema parsed from a generated fixture";
    let mut rng = Rng(0x04F0_07E5);

    let mut fixtures: Vec<Fixture> = edge_fixtures();
    for i in 0..12 {
        fixtures.push(make_fixture(&mut rng, i));
    }

    let mut cols_seen = 0usize;
    let mut files = 0usize;
    for fx in &fixtures {
        if let Err(msg) = audit(fx) {
            return Check::fail(ID, LABEL, msg);
        }
        let rec = Recording::new(&fx.bytes);
        let meta = match parquet_reader::read_footer(&rec) {
            Ok(m) => m,
            Err(e) => {
                return Check::fail(ID, LABEL, format!(
                    "{}: read_footer refused a VALID {}-byte file with {e:?}. The footer is the last {} bytes before the 4-byte length field, which holds {}. (KSPQ is the Parquet-shaped teaching format documented in your file's header — magic at the front, footer length as the final four bytes.)",
                    fx.name, fx.bytes.len(),
                    fx.bytes.len() as u64 - 4 - fx.footer_start,
                    fx.bytes.len() as u64 - 4 - fx.footer_start));
            }
        };
        if meta.version != fx.meta.version {
            return Check::fail(ID, LABEL, format!(
                "{}: version {} , want {} — it is the first u16 of the footer",
                fx.name, meta.version, fx.meta.version));
        }
        if meta.num_rows != fx.meta.num_rows {
            return Check::fail(ID, LABEL, format!(
                "{}: num_rows {}, want {} — a u64 immediately after the version, and the number that answers SELECT count(*) with no data read at all",
                fx.name, meta.num_rows, fx.meta.num_rows));
        }
        if meta.schema.len() != fx.meta.schema.len() {
            return Check::fail(ID, LABEL, format!(
                "{}: {} columns in the schema, want {} — num_columns is a u16, and each column is a u8 length, that many name bytes, then a one-byte logical type tag",
                fx.name, meta.schema.len(), fx.meta.schema.len()));
        }
        for (c, (got, want)) in meta.schema.iter().zip(&fx.meta.schema).enumerate() {
            if got.name != want.name {
                return Check::fail(ID, LABEL, format!(
                    "{}: column {c} is named {:?}, want {:?} — the name is length-prefixed and NOT null-terminated, so a trailing byte here means the type tag was read from inside the name",
                    fx.name, got.name, want.name));
            }
            if got.logical != want.logical {
                return Check::fail(ID, LABEL, format!(
                    "{}: column {c} ({}) has logical type {:?}, want {:?} — 1 = Int64, 2 = Timestamp, 3 = Bool",
                    fx.name, want.name, got.logical, want.logical));
            }
            cols_seen += 1;
        }
        if meta.row_groups.len() != fx.meta.row_groups.len() {
            return Check::fail(ID, LABEL, format!(
                "{}: {} row groups, want {}",
                fx.name, meta.row_groups.len(), fx.meta.row_groups.len()));
        }
        // reading the footer must not read the data region: the whole
        // premise of "seek to the end" is that you learn the shape of the
        // file without touching its contents
        let stray = stray_bytes(&rec, fx, &[]);
        if stray > 0 {
            return Check::fail(ID, LABEL, format!(
                "{}: read_footer requested {stray} bytes from the DATA region ({}). Ranges requested: {}. The footer is at the end of the file precisely so that a reader can learn the schema without touching a single value.",
                fx.name, ranges_str(&rec.ranges()), ranges_str(&rec.ranges())));
        }
        // parse_footer on its own must agree with read_footer: two entry
        // points, one answer
        let footer_bytes = &fx.bytes[fx.footer_start as usize..fx.bytes.len() - 4];
        match parquet_reader::parse_footer(footer_bytes) {
            Ok(direct) => {
                if direct != meta {
                    return Check::fail(ID, LABEL, format!(
                        "{}: parse_footer over the footer's bytes disagrees with read_footer over the file — read_footer is supposed to do the framing (magic, length, bounds) and then hand exactly those bytes to parse_footer",
                        fx.name));
                }
            }
            Err(e) => {
                return Check::fail(ID, LABEL, format!(
                    "{}: parse_footer refused the {} valid footer bytes read_footer accepted, with {e:?}",
                    fx.name, footer_bytes.len()));
            }
        }
        files += 1;
        let bytes_read = rec.distinct_bytes();
        if bytes_read > (fx.bytes.len() as u64 - fx.footer_start) + 8 {
            return Check::fail(ID, LABEL, format!(
                "{}: read_footer touched {bytes_read} distinct bytes; the magic plus the footer region is {} bytes. Ranges: {}",
                fx.name, (fx.bytes.len() as u64 - fx.footer_start) + 4, ranges_str(&rec.ranges())));
        }
    }
    Check::pass(ID, LABEL, format!(
        "{files} generated KSPQ files parsed exactly — {cols_seen} column definitions, and every footer read touched only the magic and the footer region (no byte of the data region). KSPQ is a Parquet-SHAPED teaching format, not Parquet: what carries over is metadata-at-the-end, and the omissions are listed in your file's header.",
        ))
}

/// 2. rowgroup_metadata: chunk offsets, lengths and statistics, exact
///    against the writer's ledger — including chunks the writer recorded no
///    statistics for, which is `None` and not "min 0, max 0".
pub fn check_rowgroup_metadata() -> Check {
    const ID: &str = "rowgroup_metadata";
    const LABEL: &str = "row-group and column-chunk offsets, sizes and statistics read correctly";
    let mut rng = Rng(0x2011_04C4);

    let mut fixtures: Vec<Fixture> = edge_fixtures();
    for i in 0..12 {
        fixtures.push(make_fixture(&mut rng, i));
    }

    let (mut chunks, mut with_stats, mut without) = (0u64, 0u64, 0u64);
    let (mut rows_declared, mut chunk_bytes) = (0u64, 0u64);
    for fx in &fixtures {
        if let Err(msg) = audit(fx) {
            return Check::fail(ID, LABEL, msg);
        }
        let rec = Recording::new(&fx.bytes);
        let meta = match parquet_reader::read_footer(&rec) {
            Ok(m) => m,
            Err(e) => return Check::fail(ID, LABEL, format!("{}: read_footer failed with {e:?} — fix footer_parse first", fx.name, )),
        };
        if meta.row_groups.len() != fx.meta.row_groups.len() {
            return Check::fail(ID, LABEL, format!(
                "{}: {} row groups, want {} — num_row_groups is the u16 after the schema",
                fx.name, meta.row_groups.len(), fx.meta.row_groups.len()));
        }
        for (g, (got, want)) in meta.row_groups.iter().zip(&fx.meta.row_groups).enumerate() {
            if got.row_count != want.row_count {
                return Check::fail(ID, LABEL, format!(
                    "{}: row group {g} declares {} rows, want {} — row groups are not all the same size, and the last one usually is not (this file's last group holds {} rows)",
                    fx.name, got.row_count, want.row_count,
                    fx.meta.row_groups.last().map(|r| r.row_count).unwrap_or(0)));
            }
            if got.chunks.len() != want.chunks.len() {
                return Check::fail(ID, LABEL, format!(
                    "{}: row group {g} has {} column chunks, want {} — every row group carries exactly one chunk per schema column, in schema order. A short list means column {} has no byte range and cannot be projected at all.",
                    fx.name, got.chunks.len(), want.chunks.len(), got.chunks.len()));
            }
            for (c, (gc, wc)) in got.chunks.iter().zip(&want.chunks).enumerate() {
                if gc.offset != wc.offset {
                    return Check::fail(ID, LABEL, format!(
                        "{}: chunk ({g},{c}) offset {} , want {} — offsets are absolute from the start of the file, u64, and the chunk table is (offset, len, has_stats[, min, max, null_count]) per column. A drift of {} bytes suggests the optional statistics were not skipped for a chunk that has none.",
                        fx.name, gc.offset, wc.offset,
                        (gc.offset as i128 - wc.offset as i128).abs()));
                }
                if gc.len != wc.len {
                    return Check::fail(ID, LABEL, format!(
                        "{}: chunk ({g},{c}) length {}, want {} — this is the number of bytes a projection of column {c} pays for, and getting it wrong makes every cost estimate wrong",
                        fx.name, gc.len, wc.len));
                }
                match (gc.stats, wc.stats) {
                    (Some(g_s), Some(w_s)) => {
                        if g_s != w_s {
                            return Check::fail(ID, LABEL, format!(
                                "{}: chunk ({g},{c}) statistics {:?}, want {:?} — min and max are i64 over NON-NULL values, then null_count as a u32",
                                fx.name, g_s, w_s));
                        }
                        with_stats += 1;
                    }
                    (None, None) => without += 1,
                    (Some(g_s), None) => {
                        return Check::fail(ID, LABEL, format!(
                            "{}: chunk ({g},{c}) reports statistics {:?}, but has_stats is 0 for it — inventing bounds nobody wrote is how a planner proves a chunk impossible with a number that was never a bound (lab 02's false negative, arriving from the file format)",
                            fx.name, g_s));
                    }
                    (None, Some(w_s)) => {
                        return Check::fail(ID, LABEL, format!(
                            "{}: chunk ({g},{c}) reports no statistics, but the file records {:?} — has_stats is 1 here, and dropping the numbers costs every skip they would have proven",
                            fx.name, w_s));
                    }
                }
                chunks += 1;
                chunk_bytes += wc.len;
            }
            rows_declared += want.row_count as u64;
        }
        // the sum of the row groups is the file's row count: a consistency
        // check a reader can make before touching data
        let summed: u64 = meta.row_groups.iter().map(|r| r.row_count as u64).sum();
        if summed != meta.num_rows {
            return Check::fail(ID, LABEL, format!(
                "{}: the row groups sum to {summed} rows but the footer's num_rows is {} — one of the two was misread (the file itself is consistent; the harness wrote it)",
                fx.name, meta.num_rows));
        }
    }
    Check::pass(ID, LABEL, format!(
        "{chunks} column chunks across {} files exact — {with_stats} with statistics, {without} where the writer recorded none (read as None, not as zeroes). {rows_declared} rows and {chunk_bytes} chunk bytes accounted for from metadata alone, before a single value was read.",
        fixtures.len()))
}

/// 3. projection_reads_minimum: THE CHECK. A two-column projection must
///    touch ZERO bytes of the other columns' chunks. Graded from a
///    recording of every byte range requested — a count, never a time.
pub fn check_projection_reads_minimum() -> Check {
    const ID: &str = "projection_reads_minimum";
    const LABEL: &str = "a two-column projection touches only those column chunks (counted)";
    let mut rng = Rng(0x9805_04C3);

    let mut fixtures: Vec<Fixture> = edge_fixtures();
    for i in 0..12 {
        fixtures.push(make_fixture(&mut rng, i));
    }

    let (mut plans, mut projected_bytes, mut requested_bytes, mut file_bytes) = (0u64, 0u64, 0u64, 0u64);
    let (mut ranges, mut skipped_chunks, mut skipped_bytes) = (0u64, 0u64, 0u64);
    for fx in &fixtures {
        if let Err(msg) = audit(fx) {
            return Check::fail(ID, LABEL, msg);
        }
        let ncols = fx.ncols();
        let rec = Recording::new(&fx.bytes);
        let meta = match parquet_reader::read_footer(&rec) {
            Ok(m) => m,
            Err(e) => return Check::fail(ID, LABEL, format!("{}: read_footer failed with {e:?} — fix footer_parse first", fx.name)),
        };

        // a projection of NO columns reads no chunk bytes at all
        rec.reset();
        match parquet_reader::project(&rec, &meta, &[]) {
            Ok(out) => {
                if !out.is_empty() {
                    return Check::fail(ID, LABEL, format!(
                        "{}: projecting no columns returned {} columns — the answer to \"no columns, please\" is no columns",
                        fx.name, out.len()));
                }
                let touched = rec.bytes_requested();
                if touched > 0 {
                    return Check::fail(ID, LABEL, format!(
                        "{}: projecting NO columns still requested {touched} bytes ({}). SELECT count(*) is the same shape: the footer already told you how many rows there are, so there is nothing left to read.",
                        fx.name, ranges_str(&rec.ranges())));
                }
            }
            Err(e) => {
                return Check::fail(ID, LABEL, format!(
                    "{}: projecting an empty column list failed with {e:?} — it is a legal projection with an empty answer",
                    fx.name));
            }
        }

        // a column that does not exist must be refused BEFORE any data is
        // read: paying for three chunks and then failing is the worst of
        // both outcomes. Tested twice — alone, and AFTER a valid column,
        // which is the ordering a reader that validates lazily gets wrong.
        for plan in [vec![ncols + 3], vec![0, ncols + 3]] {
            rec.reset();
            match parquet_reader::project(&rec, &meta, &plan) {
                Ok(_) => {
                    return Check::fail(ID, LABEL, format!(
                        "{}: projecting {plan:?} from a {ncols}-column schema returned data instead of NoSuchColumn — column {} does not exist, and inventing one (or quietly substituting another) is the guess this lab refuses",
                        fx.name, ncols + 3));
                }
                Err(_) => {
                    let touched = rec.bytes_requested();
                    if touched > 0 {
                        return Check::fail(ID, LABEL, format!(
                            "{}: projecting {plan:?} correctly failed, but only after requesting {touched} bytes ({}). Validate the whole column list against the schema BEFORE reading anything: a query that is going to fail should cost nothing, and here it has already paid for column 0.",
                            fx.name, ranges_str(&rec.ranges())));
                    }
                }
            }
        }

        // every two-column projection (or the single column, in a
        // one-column file)
        let pairs: Vec<Vec<usize>> = if ncols == 1 {
            vec![vec![0]]
        } else {
            let mut v = Vec::new();
            for a in 0..ncols {
                for b in (a + 1)..ncols {
                    v.push(vec![a, b]);
                }
            }
            v
        };
        for cols in &pairs {
            rec.reset();
            let out = match parquet_reader::project(&rec, &meta, cols) {
                Ok(o) => o,
                Err(e) => {
                    return Check::fail(ID, LABEL, format!(
                        "{}: projecting columns {cols:?} failed with {e:?}",
                        fx.name));
                }
            };
            // correctness first: a projection that reads nothing and
            // returns nothing is not a pass
            if out.len() != cols.len() {
                return Check::fail(ID, LABEL, format!(
                    "{}: projecting {cols:?} returned {} columns, want {} — one output column per requested column, in the order requested",
                    fx.name, out.len(), cols.len()));
            }
            for (k, &c) in cols.iter().enumerate() {
                let want = fx.column(c);
                if out[k] != want {
                    return Check::fail(ID, LABEL, format!(
                        "{}: projected column {c} is {} ({} values), want {} ({} values) — values are concatenated across row groups in row-group order",
                        fx.name, vals_str(&out[k]), out[k].len(), vals_str(&want), want.len()));
                }
            }

            // THE ASSERTION: not one byte of any other column's chunks
            if let Some((g, c, fs, fe, overlap)) = forbidden_hits(&rec, fx, cols) {
                return Check::fail(ID, LABEL, format!(
                    "{}: projecting {cols:?} touched {overlap} byte(s) of chunk ({g},{c}), which lives at [{fs}, {fe}) and belongs to column {c} — a column this query did not ask for. Ranges you requested: {}. This is the whole promise of columnar storage, expressed as a count: reading a whole row group (or the whole file) and slicing it in memory is simpler to write, passes every other check in this suite, and costs the same as a row-store scan.",
                    fx.name, ranges_str(&rec.ranges())));
            }
            let stray = stray_bytes(&rec, fx, cols);
            if stray > 0 {
                return Check::fail(ID, LABEL, format!(
                    "{}: projecting {cols:?} requested {stray} byte(s) that are neither the magic, nor the footer region, nor a chunk of a projected column. Ranges: {}",
                    fx.name, ranges_str(&rec.ranges())));
            }

            let want_bytes = fx
                .meta
                .row_groups
                .iter()
                .flat_map(|rg| cols.iter().map(move |&c| rg.chunks[c].len))
                .sum::<u64>();
            let got_bytes = rec.bytes_requested();
            // a small allowance for framing: the projection may re-read the
            // footer if it wants to, but it may not read data twice
            let chunk_only: u64 = rec
                .ranges()
                .iter()
                .filter(|(o, _)| *o < fx.footer_start)
                .map(|(_, l)| *l)
                .sum();
            if chunk_only > want_bytes {
                return Check::fail(ID, LABEL, format!(
                    "{}: projecting {cols:?} requested {chunk_only} bytes from the data region for chunks totalling {want_bytes} bytes — the extra {} bytes are the same bytes fetched twice. One request per chunk. Ranges: {}",
                    fx.name, chunk_only - want_bytes, ranges_str(&rec.ranges())));
            }
            plans += 1;
            projected_bytes += want_bytes;
            requested_bytes += got_bytes;
            ranges += rec.ranges().len() as u64;
            file_bytes += fx.bytes.len() as u64;
            let others: Vec<&ChunkMeta> = fx
                .meta
                .row_groups
                .iter()
                .flat_map(|rg| rg.chunks.iter().enumerate().filter(|(c, _)| !cols.contains(c)).map(|(_, ch)| ch))
                .collect();
            skipped_chunks += others.len() as u64;
            skipped_bytes += others.iter().map(|c| c.len).sum::<u64>();
        }
    }
    Check::pass(ID, LABEL, format!(
        "{plans} projections over {} files: {requested_bytes} bytes requested in {ranges} ranges, against {file_bytes} bytes of file — {}. The projected chunks are {projected_bytes} bytes; {skipped_chunks} chunks totalling {skipped_bytes} bytes were never touched, not one byte. Empty projections requested nothing at all, and a projection naming a missing column failed before paying for anything.",
        fixtures.len(),
        percent(requested_bytes, file_bytes)))
}

/// 4. rejects_malformed: sixteen broken files. Each one must produce an
///    error — not a guess, not a partial answer, and not a panic (a panic
///    traps the wasm module, and "not implemented yet" is not a diagnosis).
pub fn check_rejects_malformed() -> Check {
    const ID: &str = "rejects_malformed";
    const LABEL: &str = "truncated, wrong-magic and inconsistent-length files are rejected, not guessed at";
    let mut rng = Rng(0xBAD_F11E);

    let base = make_fixture(&mut rng, 4);
    if let Err(msg) = audit(&base) {
        return Check::fail(ID, LABEL, msg);
    }
    // the base file must itself be readable, or "it errored" proves nothing
    {
        let rec = Recording::new(&base.bytes);
        let meta = match parquet_reader::read_footer(&rec) {
            Ok(m) => m,
            Err(e) => {
                return Check::fail(ID, LABEL, format!(
                    "the VALID file these malformed variants are derived from was refused with {e:?} — a reader that rejects everything passes this check for the wrong reason, so it is tested first",
                    ));
            }
        };
        let cols: Vec<usize> = (0..base.ncols()).collect();
        if let Err(e) = parquet_reader::project(&rec, &meta, &cols) {
            return Check::fail(ID, LABEL, format!("the valid base file could not be projected: {e:?}"));
        }
    }

    let broken = broken_files(&base);
    let (mut footer_rejects, mut data_rejects) = (0u64, 0u64);
    for b in &broken {
        let rec = Recording::new(&b.bytes);
        match parquet_reader::read_footer(&rec) {
            Err(_) => {
                if !b.footer_must_fail {
                    // erroring early is acceptable — the file IS broken —
                    // but note it so the message stays honest
                    data_rejects += 1;
                    continue;
                }
                footer_rejects += 1;
            }
            Ok(meta) => {
                if b.footer_must_fail {
                    return Check::fail(ID, LABEL, format!(
                        "{}: read_footer ACCEPTED this file and returned {} columns / {} row groups / num_rows {}. {}. A reader that guesses here produces plausible garbage, and plausible garbage becomes a number in a report somebody makes a decision on. Refuse loudly instead.",
                        b.name, meta.schema.len(), meta.row_groups.len(), meta.num_rows, b.why));
                }
                // the footer is fine; the failure must arrive when the data
                // is read
                let cols: Vec<usize> = (0..meta.schema.len()).collect();
                match parquet_reader::project(&rec, &meta, &cols) {
                    Ok(out) => {
                        return Check::fail(ID, LABEL, format!(
                            "{}: the footer parsed (correctly — it is well-formed) and then project() SUCCEEDED, returning {} columns of {} values. {}.",
                            b.name, out.len(),
                            out.first().map(|c| c.len()).unwrap_or(0), b.why));
                    }
                    Err(_) => data_rejects += 1,
                }
                // and read_chunk on the offending chunk must refuse too
                if let Some(chunk) = meta.row_groups.first().and_then(|rg| rg.chunks.first()) {
                    if let Ok(vals) = parquet_reader::read_chunk(&rec, chunk) {
                        return Check::fail(ID, LABEL, format!(
                            "{}: read_chunk returned {} values for a chunk at [{}, {}) in a {}-byte file. {}. Bounds-check offset + len with CHECKED arithmetic against src.len() before you read.",
                            b.name, vals.len(), chunk.offset, chunk.offset.wrapping_add(chunk.len),
                            b.bytes.len(), b.why));
                    }
                }
            }
        }
    }

    // a well-formed file read with a hostile chunk descriptor: the reader
    // must not trust a ChunkMeta it did not get from a footer either
    let rec = Recording::new(&base.bytes);
    let hostile = [
        ChunkMeta { offset: base.bytes.len() as u64, len: 8, stats: None },
        ChunkMeta { offset: u64::MAX - 4, len: 8, stats: None },
        ChunkMeta { offset: 0, len: u64::MAX, stats: None },
        ChunkMeta { offset: 4, len: 3, stats: None },
        ChunkMeta { offset: 4, len: 0, stats: None },
    ];
    for chunk in &hostile {
        if let Ok(vals) = parquet_reader::read_chunk(&rec, chunk) {
            return Check::fail(ID, LABEL, format!(
                "read_chunk accepted {:?} against a {}-byte file and returned {} values — offset + len must be checked (with checked_add, because it overflows here) against src.len(), and a payload shorter than its own u32 header is a BadChunk",
                chunk, base.bytes.len(), vals.len()));
        }
    }

    Check::pass(ID, LABEL, format!(
        "{} malformed files all refused — {footer_rejects} at the footer (empty, 3-byte and 7-byte files, wrong magic, a 40-byte truncation, footer_len longer than the file, footer_len = u32::MAX, footer_len = 0, a 5-byte-short footer, version 7, an unknown type tag, inflated column and row-group counts) and {data_rejects} when the data was followed (a chunk offset past the end, a length that overflows, a value count the chunk cannot hold). {} hostile chunk descriptors refused as well, and the valid file this family is derived from still reads correctly.",
        broken.len(), hostile.len()))
}

/// 5. storm: 400 seeded read plans across seeded fixtures, every one of
///    them compared against an independent reference reader — with the
///    projection accounting re-checked on each plan.
pub fn check_storm() -> Check {
    const ID: &str = "storm";
    const LABEL: &str = "400 seeded read plans across fixtures vs a reference reader";
    let mut rng = Rng(0x5EED_0404);
    const PLANS: usize = 400;

    let mut fixtures: Vec<Fixture> = edge_fixtures();
    for i in 0..20 {
        fixtures.push(make_fixture(&mut rng, i));
    }
    for fx in &fixtures {
        if let Err(msg) = audit(fx) {
            return Check::fail(ID, LABEL, msg);
        }
    }

    let mut plan_kinds: BTreeMap<&'static str, usize> = BTreeMap::new();
    let (mut done, mut requested, mut projected, mut whole_file) = (0usize, 0u64, 0u64, 0u64);
    let (mut ranges, mut values_read, mut untouched) = (0u64, 0u64, 0u64);
    let mut i = 0usize;
    while done < PLANS {
        let fx = &fixtures[i % fixtures.len()];
        let ncols = fx.ncols();
        let rec = Recording::new(&fx.bytes);
        let meta = match parquet_reader::read_footer(&rec) {
            Ok(m) => m,
            Err(e) => return Check::fail(ID, LABEL, format!("{}: read_footer failed with {e:?}", fx.name)),
        };
        let want_meta = ref_read_footer(&fx.bytes).expect("audited above");
        if meta != want_meta {
            return Check::fail(ID, LABEL, format!(
                "{}: your footer differs from the reference reader's — fix footer_parse and rowgroup_metadata first",
                fx.name));
        }

        // a read plan: which columns, in which order, sometimes repeated
        let (kind, cols): (&'static str, Vec<usize>) = match i % 6 {
            0 => ("one column", vec![rng.below(ncols)]),
            1 => {
                let a = rng.below(ncols);
                let b = rng.below(ncols);
                ("two columns", if a == b { vec![a] } else { vec![a, b] })
            }
            2 => ("every column", (0..ncols).collect()),
            3 => ("reversed order", (0..ncols).rev().collect()),
            4 => {
                let a = rng.below(ncols);
                ("the same column twice", vec![a, a])
            }
            _ => ("a random subset", (0..ncols).filter(|_| rng.below(2) == 0).collect()),
        };
        *plan_kinds.entry(kind).or_insert(0) += 1;

        rec.reset();
        let got = match parquet_reader::project(&rec, &meta, &cols) {
            Ok(o) => o,
            Err(e) => {
                return Check::fail(ID, LABEL, format!(
                    "{}: projecting {cols:?} ({kind}) failed with {e:?} — every column index here is in range",
                    fx.name));
            }
        };
        let want = match ref_project(&fx.bytes, &want_meta, &cols) {
            Ok(w) => w,
            Err(e) => {
                return Check::fail(ID, LABEL, format!(
                    "HARNESS BUG: the reference reader failed on {} with {cols:?}: {e} — please report this",
                    fx.name));
            }
        };
        if got.len() != want.len() {
            return Check::fail(ID, LABEL, format!(
                "{}: projecting {cols:?} ({kind}) returned {} columns, want {} — one per entry of the request, including repeats",
                fx.name, got.len(), want.len()));
        }
        for (k, (g, w)) in got.iter().zip(&want).enumerate() {
            if g != w {
                let first = (0..g.len().max(w.len())).find(|&r| g.get(r) != w.get(r)).unwrap_or(0);
                return Check::fail(ID, LABEL, format!(
                    "{}: projecting {cols:?} ({kind}), output column {k} (schema column {}) differs from the reference at value {first}: {:?} vs {:?}. Yours has {} values, the reference has {}. Remember the null bitmap decides nullity — a null row stores the eight zero bytes of 0, so inferring nulls from the value turns every real zero into a NULL.",
                    fx.name, cols[k], g.get(first), w.get(first), g.len(), w.len()));
            }
            values_read += g.len() as u64;
        }
        if let Some((g2, c2, fs, fe, overlap)) = forbidden_hits(&rec, fx, &cols) {
            return Check::fail(ID, LABEL, format!(
                "{}: projecting {cols:?} ({kind}) touched {overlap} byte(s) of chunk ({g2},{c2}) at [{fs}, {fe}), which belongs to a column the plan did not name. Ranges: {}",
                fx.name, ranges_str(&rec.ranges())));
        }
        let stray = stray_bytes(&rec, fx, &cols);
        if stray > 0 {
            return Check::fail(ID, LABEL, format!(
                "{}: projecting {cols:?} ({kind}) requested {stray} stray byte(s) — outside the magic, the footer region and the projected chunks. Ranges: {}",
                fx.name, ranges_str(&rec.ranges())));
        }

        // and one direct read_chunk per plan, against the ledger
        if !fx.meta.row_groups.is_empty() {
            let g = rng.below(fx.meta.row_groups.len());
            let c = rng.below(ncols);
            let chunk = &meta.row_groups[g].chunks[c];
            match parquet_reader::read_chunk(&rec, chunk) {
                Ok(vals) => {
                    if vals != fx.values[g][c] {
                        return Check::fail(ID, LABEL, format!(
                            "{}: read_chunk({g},{c}) gave {} ({} values), the writer wrote {} ({} values)",
                            fx.name, vals_str(&vals), vals.len(),
                            vals_str(&fx.values[g][c]), fx.values[g][c].len()));
                    }
                }
                Err(e) => {
                    return Check::fail(ID, LABEL, format!(
                        "{}: read_chunk on the valid chunk ({g},{c}) at [{}, {}) failed with {e:?}",
                        fx.name, chunk.offset, chunk.offset + chunk.len));
                }
            }
        }

        requested += rec.bytes_requested();
        ranges += rec.ranges().len() as u64;
        projected += fx
            .meta
            .row_groups
            .iter()
            .flat_map(|rg| cols.iter().map(move |&c| rg.chunks[c].len))
            .sum::<u64>();
        whole_file += fx.bytes.len() as u64;
        untouched += fx
            .meta
            .row_groups
            .iter()
            .flat_map(|rg| rg.chunks.iter().enumerate().filter(|(c, _)| !cols.contains(c)).map(|(_, ch)| ch.len))
            .sum::<u64>();
        done += 1;
        i += 1;
    }

    let mix: Vec<String> = plan_kinds.iter().map(|(k, v)| format!("{k} {v}")).collect();
    Check::pass(ID, LABEL, format!(
        "{done} read plans over {} fixtures agree with an independent reference reader value for value — {values_read} values decoded. {requested} bytes requested in {ranges} ranges against {whole_file} bytes of file ({}); the plans' own chunks are {projected} bytes and the {untouched} bytes belonging to unprojected columns were never touched. Plan mix: {}. (KSPQ, the Parquet-shaped teaching format — pages, Thrift, levels and codecs are named as omissions in your file's header.)",
        fixtures.len(), percent(requested, whole_file), mix.join(", ")))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_footer_parse(),
        check_rowgroup_metadata(),
        check_projection_reads_minimum(),
        check_rejects_malformed(),
        check_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "parquet-reader", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
