//! parquet_reader.rs — forge lab 04 · THE ONLY FILE YOU EDIT
//!
//! Mission: read a file you did not write. Every lab so far let you choose
//! your own layout; this one hands you bytes and a specification, and the
//! only acceptable outcomes are the right answer or a refusal.
//!
//! ╔══════════════════════════════════════════════════════════════════╗
//! ║  WHAT THIS LAB IS, STATED PLAINLY                                ║
//! ║                                                                  ║
//! ║  You are NOT parsing Parquet. You are parsing KSPQ — a small,     ║
//! ║  Parquet-SHAPED teaching format defined below and generated by    ║
//! ║  the harness. It has the four things that make Parquet readable   ║
//! ║  (magic bytes, a footer at the END, per-column-chunk offsets and  ║
//! ║  lengths, per-chunk statistics) and none of the machinery that    ║
//! ║  makes real Parquet a week of work.                              ║
//! ║                                                                  ║
//! ║  Real Parquet additionally has, and this lab deliberately omits:  ║
//! ║    * a Thrift-compact-encoded `FileMetaData` structure — every    ║
//! ║      integer here is fixed-width little-endian instead;           ║
//! ║    * PAGES inside a column chunk: page headers, a dictionary      ║
//! ║      page, data pages, per-page statistics and CRCs. A KSPQ chunk ║
//! ║      is one flat payload;                                         ║
//! ║    * definition and repetition levels, which is how Parquet       ║
//! ║      encodes nulls AND nested/repeated fields. KSPQ has a flat    ║
//! ║      null bitmap and no nesting at all;                           ║
//! ║    * per-chunk encodings (PLAIN, RLE_DICTIONARY,                  ║
//! ║      DELTA_BINARY_PACKED …) and compression codecs (snappy,       ║
//! ║      zstd, gzip). KSPQ values are stored plain — you already      ║
//! ║      wrote the codecs in lab 01;                                  ║
//! ║    * six physical types (BOOLEAN, INT32, INT64, FLOAT, DOUBLE,    ║
//! ║      BYTE_ARRAY, FIXED_LEN_BYTE_ARRAY) with logical annotations   ║
//! ║      layered on top, and a schema that is a TREE. KSPQ has one    ║
//! ║      physical type (i64), three logical annotations, and a flat   ║
//! ║      list of columns;                                             ║
//! ║    * the ColumnIndex/OffsetIndex structures and bloom filters,    ║
//! ║      which push pruning below the row group to the page;          ║
//! ║    * the trailing magic. Real Parquet's last EIGHT bytes are      ║
//! ║      `[footer_len: u32 LE][PAR1]`; KSPQ's last four are just the  ║
//! ║      footer length, so the offset arithmetic lives in one place.  ║
//! ║                                                                  ║
//! ║  What transfers completely: seek to the END to find out what      ║
//! ║  the file contains, then fetch only the byte ranges the query     ║
//! ║  needs, and refuse a file that does not describe itself           ║
//! ║  consistently. Those three habits are the job. When you next read ║
//! ║  `arrow-rs`'s `SerializedFileReader`, you will recognise the      ║
//! ║  shape and the only new thing will be Thrift.                     ║
//! ╚══════════════════════════════════════════════════════════════════╝
//!
//! ═════════════════════════ THE KSPQ v1 FORMAT ════════════════════════
//!
//! Every integer is LITTLE-ENDIAN and fixed width. Offsets are absolute
//! from the start of the file.
//!
//! ```text
//!   ┌──────────────────────────────────────────────── file ───────────┐
//!   │ 0            magic "KSPQ"                             4 bytes   │
//!   │ 4            column chunk payloads, back to back                │
//!   │              (row-group-major, but you must NOT assume that:    │
//!   │               the footer says where each one is)                │
//!   │ footer_start footer                          footer_len bytes   │
//!   │ len-4        footer_len : u32                          4 bytes  │
//!   └─────────────────────────────────────────────────────────────────┘
//!
//!   footer_start = file_len - 4 - footer_len
//!
//!   footer:
//!     u16   version                     (1, and only 1)
//!     u64   num_rows                    total rows in the file
//!     u16   num_columns
//!       per column:
//!         u8            name_len
//!         name_len × u8 name            UTF-8
//!         u8            logical type    1 = Int64, 2 = Timestamp, 3 = Bool
//!     u16   num_row_groups
//!       per row group:
//!         u32  row_count
//!         per column, in SCHEMA ORDER:
//!           u64  chunk_offset
//!           u64  chunk_len
//!           u8   has_stats              0 or 1
//!           if has_stats == 1:
//!             i64  min                  over non-null values
//!             i64  max
//!             u32  null_count
//!
//!   chunk payload, at [chunk_offset, chunk_offset + chunk_len):
//!     u32              n                 values in this chunk
//!     ceil(n/8) × u8   null bitmap       bit (i % 8) of byte (i / 8),
//!                                        LSB first; 1 = row i is NULL
//!     n × i64          values            a null row stores 0 — which is
//!                                        why the bitmap, not the value,
//!                                        decides nullity
//! ```
//!
//! `has_stats == 0` means the writer recorded nothing, exactly as in
//! lab 02: no information, which proves nothing. It is not "min 0, max 0".
//!
//! ═══════════════════════ PROJECTION IS THE POINT ═════════════════════
//!
//! `projection_reads_minimum` is the check this lab exists for, and it is
//! graded as a COUNT: the harness wraps the file in a `Source` that records
//! every `(offset, len)` you request, and then asserts that a two-column
//! projection touched **zero bytes** of the chunks belonging to the other
//! columns. Not "fewer bytes". Zero.
//!
//! That is easy to fail by accident. Reading the whole file and slicing it
//! in memory is simpler to write and passes every other check in this
//! suite. It is also exactly the bug that makes a columnar reader cost the
//! same as a row-store scan, and it is invisible without instrumentation —
//! which is why the instrumentation is the lab.
//!
//! Note one honest simplification: a production reader usually fetches a
//! speculative tail (8–64 KiB) in ONE request rather than two, trading a
//! few wasted bytes for a saved round trip, because on object storage the
//! request count dominates. That trade is real and this lab does not model
//! it: here you read the 4-byte length, then the footer it describes. If
//! you fetch a speculative tail large enough to cover a chunk, the harness
//! will (correctly, by its own rules) call those chunk bytes untouched-work
//! you did not need.
//!
//! ═════════════════════ REFUSE, DO NOT GUESS ══════════════════════════
//!
//! Every function here returns `Result`. A reader that guesses at a
//! truncated footer produces plausible garbage, and plausible garbage in an
//! analytics platform becomes a number in a report that somebody makes a
//! decision on. So:
//!
//! ```text
//!   file shorter than 8 bytes            Err
//!   leading magic is not "KSPQ"          Err
//!   footer_len longer than the file       Err
//!   footer ends mid-structure             Err
//!   version != 1, unknown type tag        Err
//!   chunk offset/len outside the file     Err
//!   chunk payload disagrees with its len  Err
//!   projection names a column that does not exist   Err
//! ```
//!
//! **and never a panic.** A panic traps the wasm module: the browser shows
//! "not implemented yet" and your user learns nothing. This is why the
//! GIVEN `Cursor` below returns `Result` from every read instead of
//! slicing — with it, "the footer ended early" is an error you propagate
//! with `?` rather than an index out of range. Do not reach past it with
//! `bytes[i]` or `&bytes[a..b]`.
//!
//! ═══════════════════════════ COST IS A COUNT ═════════════════════════
//!
//! Bytes requested, ranges requested, chunks touched. Never a clock. The
//! same numbers appear in the terminal and in the browser, which is what
//! makes "reads the minimum" a gradeable claim rather than a vibe.

/* ------------------------------ the format --------------------------- */

/// The leading magic. Real Parquet writes `PAR1` here *and* at the end;
/// KSPQ writes it once (see the omissions list above).
#[allow(dead_code)] // yours to compare against in read_footer
pub const MAGIC: [u8; 4] = *b"KSPQ";

/// The only footer version this reader accepts. A version it does not know
/// is a refusal, not a best effort — the fields may mean anything.
#[allow(dead_code)]
pub const VERSION: u16 = 1;

/// magic (4) + the footer length field (4). A file smaller than this cannot
/// be a KSPQ file at all.
#[allow(dead_code)]
pub const MIN_FILE_LEN: u64 = 8;

/* ------------------------------- errors ------------------------------ */

/// Every way this reader is allowed to fail. The variants carry the numbers
/// that make the failure diagnosable — "invalid file" is not a bug report.
///
/// (`dead_code` is allowed because the template constructs none of these
/// yet; your finished reader constructs all of them.)
#[allow(dead_code)]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Error {
    /// A read that is not entirely inside the file. Returned by `Source`,
    /// so even a reader that forgets to bounds-check gets an error rather
    /// than a panic — but a reader that checks first gives a better one.
    OutOfBounds { offset: u64, len: u64, file_len: u64 },
    /// Too small to hold magic and a footer length.
    TooShort { file_len: u64 },
    /// The leading magic is not `KSPQ`.
    BadMagic { found: [u8; 4] },
    /// The declared footer length does not fit between the magic and the
    /// length field.
    BadFooterLen { footer_len: u32, file_len: u64 },
    /// The footer ran out of bytes in the middle of a structure it had
    /// already declared. Produced by `Cursor`.
    TruncatedFooter { need: usize, have: usize },
    /// A footer version this reader does not understand.
    BadVersion { found: u16 },
    /// A logical type tag outside 1..=3.
    UnknownType { tag: u8 },
    /// A column name that is not UTF-8.
    BadName,
    /// A chunk whose byte range is not inside the file.
    ChunkOutOfBounds { offset: u64, len: u64, file_len: u64 },
    /// A chunk payload that contradicts its own declared length: a value
    /// count that needs more bytes than the chunk has, or trailing bytes
    /// that no field claims.
    BadChunk { reason: &'static str },
    /// A projection naming a column the schema does not have.
    NoSuchColumn { column: usize, columns: usize },
}

/* ------------------------------- metadata ---------------------------- */

/// The three logical types KSPQ annotates its single physical type (i64)
/// with. Real Parquet has several physical types and a much larger set of
/// logical annotations; the *idea* — a physical representation plus an
/// interpretation — is the part worth carrying.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Logical {
    Int64,
    Timestamp,
    Bool,
}

#[allow(dead_code)] // yours to call from parse_footer
impl Logical {
    /// GIVEN. Tag → type, and the refusal for anything else.
    pub fn from_tag(tag: u8) -> Result<Logical, Error> {
        match tag {
            1 => Ok(Logical::Int64),
            2 => Ok(Logical::Timestamp),
            3 => Ok(Logical::Bool),
            tag => Err(Error::UnknownType { tag }),
        }
    }
}

/// One column of the schema. Flat: KSPQ has no nested groups.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ColumnMeta {
    pub name: String,
    pub logical: Logical,
}

/// The zone map of lab 02, written into a file by somebody else. `min` and
/// `max` are over non-null values; `null_count` counts null rows in this
/// chunk.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ChunkStats {
    pub min: i64,
    pub max: i64,
    pub null_count: u32,
}

/// Where one column's values for one row group live, and what the writer
/// claims about them. `stats: None` means the writer recorded nothing.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ChunkMeta {
    pub offset: u64,
    pub len: u64,
    pub stats: Option<ChunkStats>,
}

/// A row group: a horizontal slice of the table, with one chunk per column
/// in schema order. This is the unit a scan parallelises over and the unit
/// lab 02's pruning applies to.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RowGroupMeta {
    pub row_count: u32,
    pub chunks: Vec<ChunkMeta>,
}

/// The footer, parsed: everything you can learn about the file without
/// reading a single value.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FileMeta {
    pub version: u16,
    pub num_rows: u64,
    pub schema: Vec<ColumnMeta>,
    pub row_groups: Vec<RowGroupMeta>,
}

impl FileMeta {
    /// GIVEN. The chunk for (row group, column), or `None` if either index
    /// is out of range.
    #[allow(dead_code)]
    pub fn chunk(&self, row_group: usize, column: usize) -> Option<&ChunkMeta> {
        self.row_groups.get(row_group)?.chunks.get(column)
    }

    /// GIVEN. Total bytes of the chunks a projection would fetch — the
    /// number `projection_reads_minimum` is about. A count, computed from
    /// metadata, before any data is read: this is what makes a query
    /// planner able to price a scan.
    #[allow(dead_code)]
    pub fn projected_bytes(&self, columns: &[usize]) -> u64 {
        self.row_groups
            .iter()
            .flat_map(|rg| columns.iter().filter_map(|&c| rg.chunks.get(c)))
            .map(|c| c.len)
            .sum()
    }
}

/* ------------------------------- the source -------------------------- */

/// The file, as a reader is allowed to see it: a length, and the ability to
/// ask for a byte range. There is no `&[u8]` of the whole file, because
/// that is not what object storage gives you — and because a reader handed
/// the whole file cannot be measured.
///
/// Every request you make is recorded by the harness. That is the grading
/// instrument for `projection_reads_minimum`.
#[allow(dead_code)] // the harness implements this; your reader calls it
pub trait Source {
    /// Bytes in the file.
    fn len(&self) -> u64;

    /// Bytes `[offset, offset + len)`, or `Error::OutOfBounds` if that
    /// range is not entirely inside the file. One call is one request:
    /// prefer one range over two adjacent ones, and never a range you do
    /// not need.
    fn read(&self, offset: u64, len: u64) -> Result<Vec<u8>, Error>;
}

/* ------------------------------- the cursor -------------------------- */

/// GIVEN, and the reason a malformed footer is an error instead of a panic:
/// a bounds-checked forward reader over a byte slice. Every method returns
/// `Result`, so "the footer ended early" propagates with `?`.
///
/// Use this for all footer and chunk decoding. If you find yourself writing
/// `bytes[i]` or `&bytes[a..b]`, you have written the panic that
/// `rejects_malformed` is looking for.
pub struct Cursor<'a> {
    bytes: &'a [u8],
    pos: usize,
}

#[allow(dead_code)] // every method here is for your parser to call
impl<'a> Cursor<'a> {
    /// GIVEN.
    pub fn new(bytes: &'a [u8]) -> Cursor<'a> {
        Cursor { bytes, pos: 0 }
    }

    /// GIVEN. Bytes not yet consumed. Zero is not automatically an error —
    /// but a structure that declared more fields and finds zero left is.
    pub fn remaining(&self) -> usize {
        self.bytes.len().saturating_sub(self.pos)
    }

    /// GIVEN. Position within the slice, for error messages of your own.
    #[allow(dead_code)]
    pub fn pos(&self) -> usize {
        self.pos
    }

    fn take(&mut self, n: usize) -> Result<&'a [u8], Error> {
        if self.remaining() < n {
            return Err(Error::TruncatedFooter { need: n, have: self.remaining() });
        }
        let out = &self.bytes[self.pos..self.pos + n];
        self.pos += n;
        Ok(out)
    }

    /// GIVEN.
    pub fn u8(&mut self) -> Result<u8, Error> {
        Ok(self.take(1)?[0])
    }

    /// GIVEN.
    pub fn u16(&mut self) -> Result<u16, Error> {
        let b = self.take(2)?;
        Ok(u16::from_le_bytes([b[0], b[1]]))
    }

    /// GIVEN.
    pub fn u32(&mut self) -> Result<u32, Error> {
        let b = self.take(4)?;
        Ok(u32::from_le_bytes([b[0], b[1], b[2], b[3]]))
    }

    /// GIVEN.
    pub fn u64(&mut self) -> Result<u64, Error> {
        let b = self.take(8)?;
        Ok(u64::from_le_bytes([b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7]]))
    }

    /// GIVEN.
    pub fn i64(&mut self) -> Result<i64, Error> {
        Ok(self.u64()? as i64)
    }

    /// GIVEN. `n` raw bytes — for a column name or a null bitmap.
    pub fn bytes(&mut self, n: usize) -> Result<&'a [u8], Error> {
        self.take(n)
    }
}

/* ------------------------------ your work ---------------------------- */

/// TODO(you) 1/4 — the footer, from the file.
///
/// The whole reason Parquet-shaped formats put the metadata at the END: a
/// writer streams data and cannot know the offsets until it is finished, so
/// a reader seeks to the end first. In order:
///
/// ```text
///   1. the file must be at least MIN_FILE_LEN bytes            → TooShort
///   2. bytes [0, 4) must equal MAGIC                            → BadMagic
///   3. bytes [len-4, len) are footer_len : u32 LE
///   4. footer_len must fit: 4 + footer_len + 4 <= file_len      → BadFooterLen
///   5. read [file_len - 4 - footer_len, file_len - 4) and parse it
/// ```
///
/// Read the magic and the length field as SEPARATE small requests — this is
/// the tail of the file, and the harness allows the whole footer region.
/// Do not read the data region "just in case": `projection_reads_minimum`
/// counts every byte you ask for, and a chunk you never used is a chunk you
/// should never have fetched.
///
/// Step 4 is the one people skip, and it is the interesting failure: a
/// `footer_len` bigger than the file is what a truncated upload looks like,
/// and subtracting it from the length underflows into an enormous offset. A
/// reader that lets that through either errors far away from the cause or
/// reads somebody else's memory.
pub fn read_footer(src: &dyn Source) -> Result<FileMeta, Error> {
    let _ = src;
    todo!("length check, magic check, footer_len from the last 4 bytes, bounds-check footer_len against the file length (watch the underflow), then parse_footer over exactly the footer's bytes")
}

/// TODO(you) 2/4 — the footer, from its bytes.
///
/// Decode the structure documented in the module header, in order, using
/// `Cursor` so that a footer which stops mid-structure is a
/// `TruncatedFooter` rather than a panic. Reject:
///
/// ```text
///   version != VERSION                     → BadVersion
///   a logical type tag outside 1..=3        → UnknownType (Logical::from_tag)
///   a name that is not UTF-8                → BadName
/// ```
///
/// Trailing bytes after the last row group are suspicious but not fatal —
/// a later KSPQ version could add fields there, which is what a version
/// number is for. Do not reject them; do not read them either.
///
/// Every row group has exactly `num_columns` chunks, in schema order. That
/// is the invariant `project` relies on to turn a column index into a byte
/// range.
pub fn parse_footer(bytes: &[u8]) -> Result<FileMeta, Error> {
    let _ = bytes;
    todo!("Cursor::new(bytes); u16 version (check it), u64 num_rows, u16 num_columns, then per column a u8 length + name bytes + a type tag; then u16 num_row_groups and per row group a u32 row_count plus one (offset, len, has_stats[, min, max, null_count]) per column")
}

/// TODO(you) 3/4 — one column chunk, decoded.
///
/// Request EXACTLY `[chunk.offset, chunk.offset + chunk.len)` — one range,
/// no padding, no neighbouring chunk — and decode the payload:
///
/// ```text
///   u32              n
///   ceil(n/8) bytes  null bitmap, LSB-first, 1 = NULL
///   n × i64 LE       values (a null row stores 0)
/// ```
///
/// Return `n` values, with `None` wherever the bitmap says NULL. The
/// bitmap decides nullity, not the value: a legitimate 0 and a null are
/// both stored as eight zero bytes, and reading the value to decide would
/// turn every zero in the file into a NULL.
///
/// Refuse rather than guess:
///   * the range is not inside the file      → ChunkOutOfBounds
///   * `n` needs more bytes than `chunk.len` → BadChunk
///
/// Check the range against `src.len()` yourself before calling `read`:
/// `Source` will also refuse, but `ChunkOutOfBounds` names the cause and
/// `OutOfBounds` only names the symptom.
pub fn read_chunk(src: &dyn Source, chunk: &ChunkMeta) -> Result<Vec<Option<i64>>, Error> {
    let _ = (src, chunk);
    todo!("bounds-check offset+len against src.len() (checked arithmetic — offset+len can overflow), read that one range, then Cursor: u32 n, ceil(n/8) bitmap bytes, n i64s, and None wherever bit (i%8) of byte (i/8) is set")
}

/// TODO(you) 4/4 — a projection: some columns, every row.
///
/// For each entry of `columns`, in that order, return that column's values
/// concatenated across the row groups in row-group order. Repeats are
/// allowed and produce repeated output columns.
///
/// The rule, and the reason this lab exists: **touch nothing else.** Not
/// the other columns' chunks, not the whole row group, not the whole file.
/// The harness records every byte range you request and fails this check if
/// a single byte of an unprojected chunk was fetched.
///
/// An empty `columns` is legal and must read no chunk bytes at all: the
/// answer to "no columns, please" is available from metadata you already
/// have. `SELECT count(*)` is the same trick — see `RowGroupMeta::row_count`.
///
/// A column index that is not in the schema is `NoSuchColumn`, checked
/// BEFORE any data is read: a reader that fetches three chunks and then
/// discovers the fourth column does not exist has already paid for the
/// query it is about to fail.
pub fn project(src: &dyn Source, meta: &FileMeta, columns: &[usize]) -> Result<Vec<Vec<Option<i64>>>, Error> {
    let _ = (src, meta, columns);
    todo!("validate every column index against meta.schema.len() FIRST, then for each requested column walk the row groups in order and read_chunk that column's chunk, concatenating — and read nothing else")
}
