//! encodings — forge lab 01 (columnspaces).
//!
//! Four codecs and one chooser over a column of `Option<i64>`: dictionary,
//! run-length, bit-packing, frame-of-reference. Lab 02 puts statistics on
//! these blocks, lab 03 executes over them without decoding, lab 04 reads
//! the standardised version out of a Parquet file.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/encodings.rs   (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.             │
//! └────────────────────────────────────────────────────────────────┘
//!
//! What the harness is, in one paragraph: an independent second
//! implementation. It re-derives every distinct count, run count, width,
//! packed word and candidate size from the input column with its own code
//! and its own tape measure, so a student's `encoded_size` cannot flatter
//! their own chooser. Sizes are BYTE COUNTS — never a clock — which is why
//! this suite means the same thing in the terminal and in the browser.
//!
//! The two invariants everything reduces to:
//!   * `decode(encode(column)) == column`, byte-exact, nulls included. A
//!     codec that loses information is a data-loss bug, not a slow path.
//!   * `encoded_size(encode_column(c)) <= plain_size(c)` for EVERY column,
//!     because Plain is always a candidate. Compression is a claim you
//!     check, and when the claim fails you fall back.
//!
//! BTreeMap/BTreeSet only, never HashMap: std's HashMap seeds itself from
//! OS randomness that does not exist on `wasm32-unknown-unknown`.

mod encodings;

use encodings::{Encoded, HEADER};
use kslab::{Check, Report};
use std::collections::{BTreeMap, BTreeSet};

/* --------------------------- determinism ---------------------------- */

/// xorshift64* — the same column corpus on every machine, every run, in
/// both wasm and native. Seeded per check so one failure cannot move
/// another check's data.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/* ----------------------- the reference model ------------------------ */
/* A second implementation of the pinned format. Every number the checks   */
/* compare against comes from here, not from the student's crate.          */

fn ref_bits(max: u64) -> u32 {
    if max == 0 { 1 } else { 64 - max.leading_zeros() }
}

/// Words a `width`-bit stream of `n` values occupies: bits are contiguous
/// and values straddle word boundaries, so this is a ceiling divide and not
/// a per-value rounding.
fn ref_words(n: usize, width: u32) -> usize {
    (n * width as usize + 63) / 64
}

fn ref_pack(values: &[u64], width: u32) -> Vec<u64> {
    let mask = if width == 64 { u64::MAX } else { (1u64 << width) - 1 };
    let mut words = vec![0u64; ref_words(values.len(), width)];
    for (i, &v) in values.iter().enumerate() {
        let bit = i * width as usize;
        let (w, off) = (bit / 64, bit % 64);
        let v = v & mask;
        words[w] |= v << off;
        if off + width as usize > 64 {
            words[w + 1] |= v >> (64 - off);
        }
    }
    words
}

fn ref_bitmap(values: &[Option<i64>]) -> usize {
    if values.iter().any(|v| v.is_none()) { (values.len() + 7) / 8 } else { 0 }
}

fn ref_plain_size(values: &[Option<i64>]) -> usize {
    HEADER + 8 * values.len() + ref_bitmap(values)
}

/// The harness's own tape measure — the checks never call the student's.
fn ref_size(e: &Encoded) -> usize {
    match e {
        Encoded::Plain { values } => ref_plain_size(values),
        Encoded::Dict { dict, codes } => HEADER + 8 * dict.len() + 4 * codes.len(),
        Encoded::Rle { runs } => HEADER + 12 * runs.len(),
        Encoded::BitPack { words, .. } => HEADER + 8 * words.len(),
        Encoded::For { words, .. } => HEADER + 8 + 8 * words.len(),
    }
}

fn variant(e: &Encoded) -> &'static str {
    match e {
        Encoded::Plain { .. } => "Plain",
        Encoded::Dict { .. } => "Dict",
        Encoded::Rle { .. } => "Rle",
        Encoded::BitPack { .. } => "BitPack",
        Encoded::For { .. } => "For",
    }
}

fn ref_distinct(values: &[Option<i64>]) -> usize {
    values.iter().collect::<BTreeSet<_>>().len()
}

/// Maximal runs: the canonical form, so a run count is a fact about the
/// column and not about an implementation.
fn ref_runs(values: &[Option<i64>]) -> Vec<(Option<i64>, u32)> {
    let mut runs: Vec<(Option<i64>, u32)> = Vec::new();
    for &v in values {
        match runs.last_mut() {
            Some((last, count)) if *last == v => *count += 1,
            _ => runs.push((v, 1)),
        }
    }
    runs
}

/// (width, words) for the bit-packing codec, or None when the column
/// escapes its declared unsigned-32-bit domain.
fn ref_bitpack(values: &[i64]) -> Option<(u32, Vec<u64>)> {
    if values.iter().any(|&v| v < 0 || v > u32::MAX as i64) {
        return None;
    }
    let max = values.iter().map(|&v| v as u64).max().unwrap_or(0);
    let width = ref_bits(max);
    let raw: Vec<u64> = values.iter().map(|&v| v as u64).collect();
    Some((width, ref_pack(&raw, width)))
}

/// (base, width, words) for frame-of-reference. base is the column MINIMUM
/// and deltas are unsigned: `wrapping_sub` on u64 is the only subtraction
/// that survives a column holding both i64::MIN and i64::MAX, whose span
/// does not fit in i64 at all.
fn ref_for(values: &[i64]) -> (i64, u32, Vec<u64>) {
    if values.is_empty() {
        return (0, 1, Vec::new());
    }
    let base = *values.iter().min().unwrap();
    let deltas: Vec<u64> = values.iter().map(|&v| (v as u64).wrapping_sub(base as u64)).collect();
    let width = ref_bits(*deltas.iter().max().unwrap());
    let words = ref_pack(&deltas, width);
    (base, width, words)
}

/// The five candidate sizes the chooser must consider — Plain, Dict and Rle
/// always; BitPack and For only for a column with no nulls (the packed
/// stream has nowhere to put a null).
struct Cands {
    plain: usize,
    dict: usize,
    rle: usize,
    bitpack: Option<usize>,
    forr: Option<usize>,
}

impl Cands {
    fn of(values: &[Option<i64>]) -> Cands {
        let n = values.len();
        let plain = ref_plain_size(values);
        let dict = HEADER + 8 * ref_distinct(values) + 4 * n;
        let rle = HEADER + 12 * ref_runs(values).len();
        let (mut bitpack, mut forr) = (None, None);
        if values.iter().all(|v| v.is_some()) {
            let raw: Vec<i64> = values.iter().map(|v| v.unwrap()).collect();
            bitpack = ref_bitpack(&raw).map(|(w, _)| HEADER + 8 * ref_words(n, w));
            let (_, w, _) = ref_for(&raw);
            forr = Some(HEADER + 8 + 8 * ref_words(n, w));
        }
        Cands { plain, dict, rle, bitpack, forr }
    }
    fn best(&self) -> usize {
        let mut b = self.plain.min(self.dict).min(self.rle);
        if let Some(s) = self.bitpack {
            b = b.min(s);
        }
        if let Some(s) = self.forr {
            b = b.min(s);
        }
        b
    }
    fn table(&self) -> String {
        format!(
            "plain {} · dict {} · rle {} · bitpack {} · for {}",
            self.plain,
            self.dict,
            self.rle,
            self.bitpack.map(|s| s.to_string()).unwrap_or_else(|| "n/a".into()),
            self.forr.map(|s| s.to_string()).unwrap_or_else(|| "n/a".into()),
        )
    }
}

/* ------------------------- column generators ------------------------ */
/* The shapes named in the brief. Every one of them is a real column some   */
/* real table has, and each is designed to embarrass one codec.             */

fn col_all_null(n: usize) -> Vec<Option<i64>> {
    vec![None; n]
}

/// Random full-range i64: distinct values, no exploitable range. The
/// dictionary trap — a table of every value PLUS an index per row.
fn col_all_distinct(rng: &mut Rng, n: usize) -> Vec<Option<i64>> {
    let mut seen = BTreeSet::new();
    let mut out = Vec::with_capacity(n);
    while out.len() < n {
        let v = rng.next() as i64;
        if seen.insert(v) {
            out.push(Some(v));
        }
    }
    out
}

/// One value, n times: RLE's best case, one run.
fn col_single_value(rng: &mut Rng, n: usize) -> Vec<Option<i64>> {
    let v = rng.next() as i64;
    vec![Some(v); n]
}

/// Zipf(s=1) over `d` distinct values, by integer cumulative weights — no
/// floating point, so wasm and native draw the identical column.
fn col_zipf(rng: &mut Rng, n: usize, d: usize) -> Vec<Option<i64>> {
    const W: u64 = 1 << 20;
    let mut cum: Vec<u64> = Vec::with_capacity(d);
    let mut acc = 0u64;
    for k in 0..d {
        acc += W / (k as u64 + 1);
        cum.push(acc);
    }
    let total = acc as usize;
    (0..n)
        .map(|_| {
            let r = rng.below(total) as u64;
            let k = cum.iter().position(|&c| r < c).unwrap_or(d - 1);
            // spread out and negative: bit-packing cannot touch this, so the
            // dictionary and the frame have to argue it out
            Some((k as i64) * 104_729 - 50_000_000_000)
        })
        .collect()
}

/// Monotone timestamps: enormous values, tiny spread. Frame-of-reference's
/// reason to exist.
fn col_monotone(rng: &mut Rng, n: usize) -> Vec<Option<i64>> {
    let mut t = 1_700_000_000_000i64 + rng.below(1 << 20) as i64;
    (0..n)
        .map(|_| {
            t = t.wrapping_add(rng.below(60) as i64);
            Some(t)
        })
        .collect()
}

/// Clustered values with null runs: RLE territory, and the shape a
/// sorted-then-appended table actually has.
fn col_runs(rng: &mut Rng, n: usize) -> Vec<Option<i64>> {
    let mut out = Vec::with_capacity(n);
    while out.len() < n {
        let v = if rng.below(10) == 0 { None } else { Some(rng.below(8) as i64) };
        let len = (1 + rng.below(40)).min(n - out.len());
        for _ in 0..len {
            out.push(v);
        }
    }
    out
}

/// Narrow non-negative range with sparse nulls: dictionary and bit-packing
/// both apply, and the chooser has to do arithmetic rather than guess.
fn col_small(rng: &mut Rng, n: usize, span: usize, null_in: usize) -> Vec<Option<i64>> {
    (0..n)
        .map(|_| {
            if null_in > 0 && rng.below(null_in) == 0 {
                None
            } else {
                Some(rng.below(span) as i64)
            }
        })
        .collect()
}

/// A flag column: two values, width 1.
fn col_bool(rng: &mut Rng, n: usize) -> Vec<Option<i64>> {
    (0..n).map(|_| Some(rng.below(2) as i64)).collect()
}

/* ------------------------------ checks ------------------------------ */

/// 1. dict_roundtrip: the dictionary holds every distinct value exactly
///    once (NULL is a value, not a flag), every row carries a valid code,
///    and decode is byte-exact.
pub fn check_dict_roundtrip() -> Check {
    const ID: &str = "dict_roundtrip";
    const LABEL: &str = "dictionary encode/decode round-trips byte-exact";
    let mut rng = Rng(0x5EED_D1C7);
    let cases: Vec<(&str, Vec<Option<i64>>)> = vec![
        ("empty", vec![]),
        ("one value", vec![Some(42)]),
        ("one null", vec![None]),
        ("all null (64)", col_all_null(64)),
        ("single value (100)", col_single_value(&mut rng, 100)),
        ("alternating two values", (0..64).map(|i| Some((i % 2) as i64)).collect()),
        ("nulls interleaved", (0..96).map(|i| if i % 3 == 0 { None } else { Some((i % 5) as i64) }).collect()),
        ("all distinct (500)", col_all_distinct(&mut rng, 500)),
        ("extremes", vec![Some(i64::MIN), Some(0), None, Some(i64::MAX), Some(i64::MIN), None]),
        ("zipf (400)", col_zipf(&mut rng, 400, 24)),
    ];
    for (name, col) in &cases {
        let e = encodings::dict_encode(col);
        let (dict, codes) = match &e {
            Encoded::Dict { dict, codes } => (dict, codes),
            other => {
                return Check::fail(ID, LABEL, format!(
                    "{name}: dict_encode returned {} — the dictionary codec returns Encoded::Dict; choosing between codecs is encode_column's job",
                    variant(other)));
            }
        };
        if codes.len() != col.len() {
            return Check::fail(ID, LABEL, format!(
                "{name}: {} codes for {} values — every row gets exactly one code",
                codes.len(), col.len()));
        }
        if dict.iter().collect::<BTreeSet<_>>().len() != dict.len() {
            return Check::fail(ID, LABEL, format!(
                "{name}: the dictionary holds a duplicate value — a distinct-value table with duplicates costs 8 bytes per repeat and buys nothing"));
        }
        let want_distinct = ref_distinct(col);
        if dict.len() != want_distinct {
            return Check::fail(ID, LABEL, format!(
                "{name}: dictionary holds {} values, the column has {want_distinct} distinct (NULL counts as one of them)",
                dict.len()));
        }
        if let Some(bad) = codes.iter().find(|&&c| c as usize >= dict.len()) {
            return Check::fail(ID, LABEL, format!(
                "{name}: code {bad} indexes past a dictionary of {} entries", dict.len()));
        }
        let got = encodings::decode(&e);
        if got != *col {
            return Check::fail(ID, LABEL, format!(
                "{name}: decode(dict_encode(col)) != col — {}",
                first_diff(&got, col)));
        }
    }
    let big = col_zipf(&mut rng, 4096, 6);
    let e = encodings::dict_encode(&big);
    Check::pass(ID, LABEL, format!(
        "{} columns byte-exact; 6-distinct 4096-value column: {} B vs {} B plain",
        cases.len(), ref_size(&e), ref_plain_size(&big)))
}

/// 2. rle_roundtrip: runs are MAXIMAL — adjacent runs never hold equal
///    values — so a constant column is one run and an alternating column is
///    n of them. Single-element runs in the middle of a column are where
///    naive loops drop a value.
pub fn check_rle_roundtrip() -> Check {
    const ID: &str = "rle_roundtrip";
    const LABEL: &str = "RLE round-trips, including single-element runs";
    let mut rng = Rng(0x5EED_71E5);

    // an exact-shape case first: the runs themselves are graded, not just
    // the round-trip, because RLE is a canonical form
    let hand: Vec<Option<i64>> = vec![
        Some(1), Some(1), Some(2), Some(3), Some(3), Some(3), None, None, Some(3), Some(4),
    ];
    let want: Vec<(Option<i64>, u32)> =
        vec![(Some(1), 2), (Some(2), 1), (Some(3), 3), (None, 2), (Some(3), 1), (Some(4), 1)];
    match &encodings::rle_encode(&hand) {
        Encoded::Rle { runs } if *runs == want => {}
        Encoded::Rle { runs } => {
            return Check::fail(ID, LABEL, format!(
                "hand case: runs {runs:?}, want {want:?} — maximal runs, and a value that reappears after a null run starts a NEW run"));
        }
        other => {
            return Check::fail(ID, LABEL, format!(
                "hand case: rle_encode returned {} — the RLE codec returns Encoded::Rle", variant(other)));
        }
    }

    let cases: Vec<(&str, Vec<Option<i64>>, Option<usize>)> = vec![
        ("empty", vec![], Some(0)),
        ("one value", vec![Some(7)], Some(1)),
        ("one null", vec![None], Some(1)),
        ("constant (1000)", col_single_value(&mut rng, 1000), Some(1)),
        ("all null (500)", col_all_null(500), Some(1)),
        ("alternating (1000)", (0..1000).map(|i| Some((i % 2) as i64)).collect(), Some(1000)),
        ("all distinct (300)", col_all_distinct(&mut rng, 300), Some(300)),
        ("null/value alternating", (0..200).map(|i| if i % 2 == 0 { None } else { Some(5) }).collect(), Some(200)),
        ("clustered with nulls", col_runs(&mut rng, 2000), None),
        ("long run (300000)", col_single_value(&mut rng, 300_000), Some(1)),
    ];
    for (name, col, want_runs) in &cases {
        let e = encodings::rle_encode(col);
        let runs = match &e {
            Encoded::Rle { runs } => runs,
            other => {
                return Check::fail(ID, LABEL, format!("{name}: rle_encode returned {}", variant(other)));
            }
        };
        let total: u64 = runs.iter().map(|(_, c)| *c as u64).sum();
        if total != col.len() as u64 {
            return Check::fail(ID, LABEL, format!(
                "{name}: run counts sum to {total}, the column has {} values — the length is implicit in RLE, so a wrong sum is a lost or duplicated row",
                col.len()));
        }
        if let Some(i) = (1..runs.len()).find(|&i| runs[i].0 == runs[i - 1].0) {
            return Check::fail(ID, LABEL, format!(
                "{name}: runs {} and {i} hold the same value — runs must be maximal, or RLE is not a canonical form and two encoders disagree on the same column",
                i - 1));
        }
        let expect = want_runs.unwrap_or_else(|| ref_runs(col).len());
        if runs.len() != expect {
            return Check::fail(ID, LABEL, format!(
                "{name}: {} runs, the reference finds {expect}", runs.len()));
        }
        let got = encodings::decode(&e);
        if got != *col {
            return Check::fail(ID, LABEL, format!(
                "{name}: decode(rle_encode(col)) != col — {}", first_diff(&got, col)));
        }
    }
    Check::pass(ID, LABEL, format!(
        "{} columns byte-exact; a 300000-value constant column is 1 run ({} B)",
        cases.len() + 1, HEADER + 12))
}

/// 3. bitpack_roundtrip: every width 1..=32 through the codec, every width
///    1..=64 through the pack/unpack primitive (frame-of-reference needs the
///    wide end), the bit layout compared against the reference word for
///    word, and out-of-domain columns refused rather than truncated.
pub fn check_bitpack_roundtrip() -> Check {
    const ID: &str = "bitpack_roundtrip";
    const LABEL: &str = "bit-packing round-trips at every width 1..32";

    // the primitive, at every width including 64 — and n = 97 so that
    // n*width is almost never a multiple of 64: the last word is partial
    let mut rng = Rng(0x5EED_B17C);
    for width in 1..=64u32 {
        let mask = if width == 64 { u64::MAX } else { (1u64 << width) - 1 };
        let n = 97;
        let vals: Vec<u64> = (0..n).map(|i| if i == 0 { mask } else { rng.next() & mask }).collect();
        let words = encodings::pack(&vals, width);
        let want = ref_pack(&vals, width);
        if words.len() != ref_words(n, width) {
            return Check::fail(ID, LABEL, format!(
                "pack(width {width}): {} words for {n} values, want {} — the stream is contiguous bits, so values straddle word boundaries",
                words.len(), ref_words(n, width)));
        }
        if words != want {
            let i = (0..words.len()).find(|&i| words[i] != want[i]).unwrap();
            return Check::fail(ID, LABEL, format!(
                "pack(width {width}): word {i} is {:#018x}, the pinned LSB-first layout says {:#018x} — check the carry into the next word (only when bit%64 + width > 64) and that trailing bits are zero",
                words[i], want[i]));
        }
        let back = encodings::unpack(&words, width, n);
        if back != vals {
            let i = (0..n).find(|&i| back.get(i) != vals.get(i)).unwrap();
            return Check::fail(ID, LABEL, format!(
                "unpack(width {width}): value {i} came back {:?}, want {:?} — width 64 needs its own mask, since 1u64 << 64 is not 0",
                back.get(i), vals.get(i)));
        }
        if !encodings::unpack(&words, width, 0).is_empty() {
            return Check::fail(ID, LABEL, format!("unpack(width {width}, len 0) must be empty — len is the only authority on how many values a word holds"));
        }
    }

    // the codec, at every legal width
    for width in 1..=32u32 {
        let max: u64 = if width == 32 { u32::MAX as u64 } else { (1u64 << width) - 1 };
        let n = 101;
        let vals: Vec<i64> = (0..n)
            .map(|i| match i {
                0 => 0,
                1 => max as i64,
                _ => (rng.next() & max) as i64,
            })
            .collect();
        let e = match encodings::bitpack_encode(&vals) {
            Some(e) => e,
            None => {
                return Check::fail(ID, LABEL, format!(
                    "width {width}: bitpack_encode refused a column whose values all fit in {width} bits (max {max})"));
            }
        };
        let (w, len, words) = match &e {
            Encoded::BitPack { width, len, words } => (*width, *len, words),
            other => return Check::fail(ID, LABEL, format!("width {width}: bitpack_encode returned {}", variant(other))),
        };
        if w != width {
            return Check::fail(ID, LABEL, format!(
                "column with max {max} packed at width {w}, want {width} — the width is the smallest that holds the max, no rounding to bytes"));
        }
        if len as usize != n {
            return Check::fail(ID, LABEL, format!("width {width}: len {len}, want {n}"));
        }
        let raw: Vec<u64> = vals.iter().map(|&v| v as u64).collect();
        if *words != ref_pack(&raw, width) {
            return Check::fail(ID, LABEL, format!("width {width}: the packed words differ from the pinned layout"));
        }
        let got = encodings::decode(&e);
        let want: Vec<Option<i64>> = vals.iter().map(|&v| Some(v)).collect();
        if got != want {
            return Check::fail(ID, LABEL, format!(
                "width {width}: decode(bitpack_encode(col)) != col — {}", first_diff(&got, &want)));
        }
    }

    // the domain boundary: represent it exactly or refuse it
    match encodings::bitpack_encode(&[]) {
        Some(Encoded::BitPack { width: 1, len: 0, words }) if words.is_empty() => {}
        other => {
            return Check::fail(ID, LABEL, format!(
                "an empty column must be BitPack {{ width: 1, len: 0, words: [] }}, got {other:?} — width 0 makes the word count a division by zero"));
        }
    }
    match encodings::bitpack_encode(&[u32::MAX as i64, 0]) {
        Some(Encoded::BitPack { width: 32, .. }) => {}
        other => return Check::fail(ID, LABEL, format!("u32::MAX must pack at width 32, got {other:?}")),
    }
    for (name, col) in [
        ("a negative value", vec![1i64, -1]),
        ("i64::MIN", vec![i64::MIN]),
        ("one past u32::MAX", vec![u32::MAX as i64 + 1]),
        ("i64::MAX", vec![0, i64::MAX]),
    ] {
        if let Some(e) = encodings::bitpack_encode(&col) {
            return Check::fail(ID, LABEL, format!(
                "{name} is outside the codec's unsigned-32-bit domain, but bitpack_encode returned {} — a codec that cannot represent the data says None; truncating it is silent corruption (frame-of-reference is the codec for that column)",
                variant(&e)));
        }
    }
    Check::pass(ID, LABEL, "widths 1..=64 pack bit-exact, widths 1..=32 round-trip through the codec, out-of-domain columns refused")
}

/// 4. for_roundtrip: base is the column minimum and deltas are unsigned, so
///    the codec survives negative values, descending columns and a column
///    holding both i64::MIN and i64::MAX — whose span does not fit in i64.
pub fn check_for_roundtrip() -> Check {
    const ID: &str = "for_roundtrip";
    const LABEL: &str = "frame-of-reference handles negative deltas and full-range values";
    let mut rng = Rng(0x5EED_F0F0);
    let ts: Vec<i64> = col_monotone(&mut rng, 4096).iter().map(|v| v.unwrap()).collect();
    let cases: Vec<(&str, Vec<i64>)> = vec![
        ("empty", vec![]),
        ("one value", vec![1_700_000_000_000]),
        ("i64::MIN alone", vec![i64::MIN]),
        ("i64::MAX alone", vec![i64::MAX]),
        ("full range", vec![i64::MIN, i64::MAX]),
        ("full range with zero", vec![i64::MAX, 0, i64::MIN]),
        ("adjacent at the floor", vec![i64::MIN, i64::MIN + 1, i64::MIN + 2]),
        ("adjacent at the ceiling", vec![i64::MAX - 2, i64::MAX - 1, i64::MAX]),
        ("all negative", (0..500i64).map(|i| -1_000_000 - i * 3).collect()),
        ("straddling zero", (0..500i64).map(|i| i - 250).collect()),
        ("descending", (0..500i64).map(|i| 1_000_000 - i * 7).collect()),
        ("constant", vec![-42; 300]),
        ("monotone timestamps", ts.clone()),
    ];
    for (name, col) in &cases {
        let e = encodings::for_encode(col);
        let (base, width, len, words) = match &e {
            Encoded::For { base, width, len, words } => (*base, *width, *len, words),
            other => return Check::fail(ID, LABEL, format!("{name}: for_encode returned {}", variant(other))),
        };
        let (want_base, want_width, want_words) = ref_for(col);
        if base != want_base {
            return Check::fail(ID, LABEL, format!(
                "{name}: base {base}, want {want_base} — the frame base is pinned to the column MINIMUM, which is what makes every delta non-negative (base = the first value gives negative deltas that an unsigned stream cannot hold)"));
        }
        if width != want_width {
            return Check::fail(ID, LABEL, format!(
                "{name}: width {width}, want {want_width} — the width covers max−min computed as an UNSIGNED distance; in i64 that subtraction overflows on this column"));
        }
        if len as usize != col.len() {
            return Check::fail(ID, LABEL, format!("{name}: len {len}, want {}", col.len()));
        }
        if *words != want_words {
            return Check::fail(ID, LABEL, format!(
                "{name}: packed deltas differ from the reference — deltas are (v as u64).wrapping_sub(base as u64), packed LSB-first at width {want_width}"));
        }
        let got = encodings::decode(&e);
        let want: Vec<Option<i64>> = col.iter().map(|&v| Some(v)).collect();
        if got != want {
            return Check::fail(ID, LABEL, format!(
                "{name}: decode(for_encode(col)) != col — {} (decode adds the delta back with wrapping_add)",
                first_diff(&got, &want)));
        }
    }
    // the reason the codec exists: huge values, tiny spread
    let e = encodings::for_encode(&ts);
    let (size, plain) = (ref_size(&e), HEADER + 8 * ts.len());
    if size * 3 > plain {
        return Check::fail(ID, LABEL, format!(
            "4096 monotone timestamps encode to {size} B against {plain} B plain — a column with a {} span should need about {} bits per value, so the width is being computed from the values instead of the deltas",
            ts[ts.len() - 1] - ts[0], ref_bits((ts[ts.len() - 1] - ts[0]) as u64)));
    }
    Check::pass(ID, LABEL, format!(
        "{} columns byte-exact including i64::MIN..i64::MAX; 4096 timestamps: {size} B vs {plain} B plain",
        cases.len()))
}

/// 5. never_expands: the bound. Plain is always a candidate, so the chosen
///    encoding can never exceed plain_size — and the chooser must still be
///    the smallest of the five candidates, or "always fall back" would pass.
pub fn check_never_expands() -> Check {
    const ID: &str = "never_expands";
    const LABEL: &str = "no codec exceeds the plain encoding by more than the header bound";
    let mut rng = Rng(0x5EED_B0DD);

    // (name, column, must be at most this many bytes)
    let cases: Vec<(&str, Vec<Option<i64>>, Option<usize>)> = vec![
        ("empty", vec![], Some(HEADER)),
        ("one value", vec![Some(7)], None),
        ("one null", vec![None], None),
        ("all null (4096)", col_all_null(4096), Some(HEADER + 12)),
        ("single value (4096)", col_single_value(&mut rng, 4096), Some(HEADER + 12)),
        ("all distinct 64-bit (2048)", col_all_distinct(&mut rng, 2048), None),
        ("all distinct with nulls", {
            let mut c = col_all_distinct(&mut rng, 1024);
            for i in (0..c.len()).step_by(7) {
                c[i] = None;
            }
            c
        }, None),
        ("6 distinct small (4096)", col_small(&mut rng, 4096, 6, 0), Some(4096 + HEADER)),
        ("flags (4096)", col_bool(&mut rng, 4096), Some(HEADER + 8 * 64)),
        ("monotone timestamps (4096)", col_monotone(&mut rng, 4096), Some((HEADER + 8 * 4096) / 3)),
        ("zipf (4096)", col_zipf(&mut rng, 4096, 32), None),
        ("clustered with nulls (4096)", col_runs(&mut rng, 4096), None),
        ("sparse nulls, wide values", {
            let mut c = col_all_distinct(&mut rng, 1000);
            c[13] = None;
            c
        }, None),
        ("alternating extremes", (0..1000).map(|i| Some(if i % 2 == 0 { i64::MIN } else { i64::MAX })).collect(), None),
    ];

    let (mut total_plain, mut total_enc) = (0usize, 0usize);
    for (name, col, budget) in &cases {
        let e = encodings::encode_column(col);
        let (size, plain, cands) = (ref_size(&e), ref_plain_size(col), Cands::of(col));

        // the bound: HEADER + 8 bytes per value (+ the null bitmap when the
        // column has a null) and not one byte more
        if size > plain {
            return Check::fail(ID, LABEL, format!(
                "{name}: {} encoding is {size} B against a plain bound of {plain} B ({} values) — Plain is always a candidate, so exceeding it means the fallback is missing. Real formats all have one: Parquet falls back to plain pages, ORC to direct encoding. Candidates: {}",
                variant(&e), col.len(), cands.table()));
        }
        let got = encodings::decode(&e);
        if got != *col {
            return Check::fail(ID, LABEL, format!(
                "{name}: the chosen {} encoding does not round-trip — {}",
                variant(&e), first_diff(&got, col)));
        }
        let best = cands.best();
        if size != best {
            return Check::fail(ID, LABEL, format!(
                "{name}: chose {} at {size} B, but the smallest candidate is {best} B — {}",
                variant(&e), cands.table()));
        }
        if let Some(max) = budget {
            if size > *max {
                return Check::fail(ID, LABEL, format!(
                    "{name}: {size} B, and this column must compress to at most {max} B — falling back to Plain on a column with obvious structure keeps you inside the bound but wastes the codec. Candidates: {}",
                    cands.table()));
            }
        }
        // the tape measure is given, and the grader has its own copy
        if encodings::encoded_size(&e) != size || encodings::plain_size(col) != plain {
            return Check::fail(ID, LABEL, format!(
                "{name}: your size formulas disagree with the grader's ({} vs {size}, plain {} vs {plain}) — plain_size and encoded_size are GIVEN; the bound is not negotiable",
                encodings::encoded_size(&e), encodings::plain_size(col)));
        }
        total_plain += plain;
        total_enc += size;
    }

    // the lesson of the all-distinct column, stated as arithmetic: the
    // dictionary itself IS bigger, and the chooser has to notice
    let wide = col_all_distinct(&mut rng, 2048);
    let d = ref_size(&encodings::dict_encode(&wide));
    let p = ref_plain_size(&wide);
    if d <= p {
        return Check::fail(ID, LABEL, format!(
            "a dictionary over 2048 distinct values is {d} B against {p} B plain — it should be LARGER (2048 dictionary entries plus one 4-byte code per row); a smaller number means values are being dropped from the dictionary"));
    }
    if !matches!(encodings::encode_column(&wide), Encoded::Plain { .. }) {
        return Check::fail(ID, LABEL, format!(
            "on 2048 distinct full-range values every codec loses to Plain ({}), so encode_column must return Plain",
            Cands::of(&wide).table()));
    }
    Check::pass(ID, LABEL, format!(
        "{} columns inside the bound and optimal among the five candidates; {total_plain} B plain → {total_enc} B encoded",
        cases.len()))
}

/// 6. storm: 2000 seeded columns across the shapes that break codecs. Every
///    codec round-trips on every applicable column, the chooser stays
///    inside the bound, and its size equals the best of the five candidates
///    computed independently here.
pub fn check_storm() -> Check {
    const ID: &str = "storm";
    const LABEL: &str = "2000 seeded columns (all-null, all-distinct, single-value, zipf) vs a reference model";
    let mut rng = Rng(0x5EED);
    let mut shape_counts: BTreeMap<&'static str, usize> = BTreeMap::new();
    let mut chosen: BTreeMap<&'static str, usize> = BTreeMap::new();
    let (mut total_plain, mut total_enc, mut values) = (0u64, 0u64, 0u64);

    for i in 0..2000usize {
        let n = if i % 211 == 0 {
            0
        } else if i % 97 == 0 {
            4096
        } else {
            1 + rng.below(400)
        };
        // parameters are drawn BEFORE the column so the stream of random
        // numbers — and therefore the corpus — does not depend on argument
        // evaluation order
        let (zipf_d, span, null_in) = (1 + rng.below(64), 1 + rng.below(4096), 1 + rng.below(20));
        let (shape, col): (&'static str, Vec<Option<i64>>) = match i % 8 {
            0 => ("all-null", col_all_null(n)),
            1 => ("all-distinct", col_all_distinct(&mut rng, n)),
            2 => ("single-value", col_single_value(&mut rng, n)),
            3 => ("zipf", col_zipf(&mut rng, n, zipf_d)),
            4 => ("monotone", col_monotone(&mut rng, n)),
            5 => ("clustered", col_runs(&mut rng, n)),
            6 => ("narrow+nulls", col_small(&mut rng, n, span, null_in)),
            _ => ("flags", col_bool(&mut rng, n)),
        };
        *shape_counts.entry(shape).or_insert(0) += 1;
        let where_ = |what: &str| format!("column {i} ({shape}, {n} values): {what}");

        // every codec, on every column it applies to
        let dict = encodings::dict_encode(&col);
        if encodings::decode(&dict) != col {
            return Check::fail(ID, LABEL, where_("dict_encode does not round-trip"));
        }
        let rle = encodings::rle_encode(&col);
        match &rle {
            Encoded::Rle { runs } if runs.len() == ref_runs(&col).len() => {}
            Encoded::Rle { runs } => {
                return Check::fail(ID, LABEL, where_(&format!(
                    "{} runs, the reference finds {} — runs must be maximal", runs.len(), ref_runs(&col).len())));
            }
            other => return Check::fail(ID, LABEL, where_(&format!("rle_encode returned {}", variant(other)))),
        }
        if encodings::decode(&rle) != col {
            return Check::fail(ID, LABEL, where_("rle_encode does not round-trip"));
        }
        if col.iter().all(|v| v.is_some()) {
            let raw: Vec<i64> = col.iter().map(|v| v.unwrap()).collect();
            match (encodings::bitpack_encode(&raw), ref_bitpack(&raw)) {
                (Some(e), Some((w, words))) => {
                    match &e {
                        Encoded::BitPack { width, len, words: got } if *width == w && *len as usize == raw.len() && *got == words => {}
                        _ => return Check::fail(ID, LABEL, where_(&format!("bitpack_encode disagrees with the reference at width {w}"))),
                    }
                    if encodings::decode(&e) != col {
                        return Check::fail(ID, LABEL, where_("bitpack_encode does not round-trip"));
                    }
                }
                (None, None) => {}
                (Some(_), None) => {
                    return Check::fail(ID, LABEL, where_("bitpack_encode accepted a column outside its unsigned-32-bit domain"));
                }
                (None, Some((w, _))) => {
                    return Check::fail(ID, LABEL, where_(&format!("bitpack_encode refused a column that fits in {w} bits")));
                }
            }
            let f = encodings::for_encode(&raw);
            let (b, w, words) = ref_for(&raw);
            match &f {
                Encoded::For { base, width, len, words: got } if *base == b && *width == w && *len as usize == raw.len() && *got == words => {}
                Encoded::For { base, width, .. } => {
                    return Check::fail(ID, LABEL, where_(&format!(
                        "for_encode gave base {base} width {width}, the reference says base {b} width {w}")));
                }
                other => return Check::fail(ID, LABEL, where_(&format!("for_encode returned {}", variant(other)))),
            }
            if encodings::decode(&f) != col {
                return Check::fail(ID, LABEL, where_("for_encode does not round-trip"));
            }
        }

        // and the chooser
        let e = encodings::encode_column(&col);
        let (size, plain, cands) = (ref_size(&e), ref_plain_size(&col), Cands::of(&col));
        if encodings::decode(&e) != col {
            return Check::fail(ID, LABEL, where_(&format!(
                "the chosen {} encoding does not round-trip — {}",
                variant(&e), first_diff(&encodings::decode(&e), &col))));
        }
        if size > plain {
            return Check::fail(ID, LABEL, where_(&format!(
                "{} is {size} B over a plain bound of {plain} B — {}", variant(&e), cands.table())));
        }
        if size != cands.best() {
            return Check::fail(ID, LABEL, where_(&format!(
                "chose {} at {size} B, best candidate is {} B — {}", variant(&e), cands.best(), cands.table())));
        }
        *chosen.entry(variant(&e)).or_insert(0) += 1;
        total_plain += plain as u64;
        total_enc += size as u64;
        values += n as u64;
    }

    let shapes: Vec<String> = shape_counts.iter().map(|(k, v)| format!("{k} {v}")).collect();
    let picks: Vec<String> = chosen.iter().map(|(k, v)| format!("{k} {v}")).collect();
    Check::pass(ID, LABEL, format!(
        "2000 columns / {values} values model-exact — {} · chose {} · {total_plain} B plain → {total_enc} B encoded",
        shapes.join(", "), picks.join(", ")))
}

/// The first position where a decoded column diverges — the message a
/// round-trip failure needs, since "not equal" is not a diagnosis.
fn first_diff(got: &[Option<i64>], want: &[Option<i64>]) -> String {
    if got.len() != want.len() {
        return format!("length {} vs {}", got.len(), want.len());
    }
    match (0..got.len()).find(|&i| got[i] != want[i]) {
        Some(i) => format!("position {i}: got {:?}, want {:?}", got[i], want[i]),
        None => "identical (the mismatch is elsewhere)".to_string(),
    }
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_dict_roundtrip(),
        check_rle_roundtrip(),
        check_bitpack_roundtrip(),
        check_for_roundtrip(),
        check_never_expands(),
        check_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "encodings", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
