//! merge-on-read — forge lab 05 (columnspaces).
//!
//! A delta store over an immutable sorted base, a merge on the read path,
//! and a compaction policy. Labs 01–04 made a static table small, unread,
//! fast and portable. This one lets it change.
//!
//! ┌────────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/merge_on_read.rs   (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.                 │
//! └────────────────────────────────────────────────────────────────────┘
//!
//! What the harness is, in one paragraph: an independent second
//! implementation of the same semantics — a reference model that keeps one
//! visible version per key and nothing else — plus a ground truth for that
//! model, which is a from-scratch replay of the entire mutation log. Every
//! expectation compared against a student's store comes from the model, and
//! the model is audited against the replay on every storm phase. If the two
//! ever disagree the suite reports "HARNESS BUG" and fails, because a
//! reference that is itself unsound would silently excuse a wrong answer.
//!
//! The grading is split the way the production consequences are:
//!
//!   * `read_your_writes`, `merge_ordered`, `delete_semantics` and `storm`
//!     are ABSOLUTES with zero tolerance. A read that misses the newest
//!     version of a key, a merge that emits a key twice, a delete that
//!     resurrects a row — these are silent wrong answers.
//!   * `read_amp_bounded` and `write_amp_budget` are BANDS, graded on the
//!     SAME seeded workload, and they pull in opposite directions: never
//!     compacting fails the first, compacting on every write fails the
//!     second. Passing both means a policy was found rather than a
//!     preference.
//!
//! Both bands are COUNTS — levels probed per read, rows rewritten per row
//! ingested — never clocks, which is why this suite means the same thing in
//! the terminal and in the browser. And both are charged from state the
//! harness reads off the store itself (`Store::runs`, `Store::base`,
//! `Store::compactions`), never from a number the student's code reports.
//!
//! BTreeMap only, never HashMap: std's HashMap seeds itself from OS
//! randomness that does not exist on `wasm32-unknown-unknown`.

mod merge_on_read;

use kslab::{Check, Report};
use merge_on_read::{BaseRow, Key, Store, Version};
use std::collections::BTreeMap;

/* --------------------------- determinism ---------------------------- */

/// xorshift64* — the same workloads on every machine, every run, in both
/// wasm and native. Seeded per check so one failure cannot move another
/// check's data.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        if n == 0 { 0 } else { (self.next() % n as u64) as usize }
    }
    fn key(&mut self, span: u64) -> Key {
        if span == 0 { 0 } else { self.next() % span }
    }
    fn value(&mut self) -> i64 {
        match self.below(16) {
            0 => 0,
            1 => i64::MIN,
            2 => i64::MAX,
            3 => -1,
            _ => (self.next() % 1_000_000) as i64,
        }
    }
}

/* ----------------------- the reference model ------------------------ */
/* One visible version per key, and a log that can rebuild it from nothing. */
/* Every expectation in this file comes from here.                          */

struct Model {
    visible: BTreeMap<Key, Version>,
    log: Vec<(Key, Option<i64>, u64)>,
}

impl Model {
    fn new() -> Model {
        Model { visible: BTreeMap::new(), log: Vec::new() }
    }

    /// The base a store is opened over, replayed into the model as writes.
    fn seed(&mut self, rows: &[BaseRow]) {
        for r in rows {
            self.apply(r.key, Some(r.value), r.seq);
        }
    }

    /// A mutation. A tombstone REMOVES the key: there is no such thing as
    /// a visible deleted version.
    fn apply(&mut self, key: Key, value: Option<i64>, seq: u64) {
        self.log.push((key, value, seq));
        match value {
            Some(v) => {
                self.visible.insert(key, Version { value: v, seq });
            }
            None => {
                self.visible.remove(&key);
            }
        }
    }

    fn get(&self, key: Key) -> Option<Version> {
        self.visible.get(&key).copied()
    }

    fn rows(&self) -> Vec<BaseRow> {
        self.visible.iter().map(|(k, v)| BaseRow { key: *k, value: v.value, seq: v.seq }).collect()
    }

    fn range(&self, lo: Key, hi: Key) -> Vec<BaseRow> {
        if lo > hi {
            return Vec::new();
        }
        self.visible
            .range(lo..=hi)
            .map(|(k, v)| BaseRow { key: *k, value: v.value, seq: v.seq })
            .collect()
    }

    /// GROUND TRUTH for the model itself: rebuild the visible set from the
    /// log, from nothing, with different code. The incremental map above is
    /// a convenience; this is the definition.
    fn replay(&self) -> BTreeMap<Key, Version> {
        let mut out: BTreeMap<Key, Version> = BTreeMap::new();
        let mut ordered = self.log.clone();
        // sequence numbers are the authority on order, not arrival
        ordered.sort_by_key(|(_, _, seq)| *seq);
        for (key, value, seq) in ordered {
            match value {
                Some(v) => {
                    out.insert(key, Version { value: v, seq });
                }
                None => {
                    out.remove(&key);
                }
            }
        }
        out
    }

    /// The harness auditing itself. `Some(msg)` means the reference is
    /// unsound and no student verdict drawn from it can be trusted.
    fn audit(&self) -> Option<String> {
        let replayed = self.replay();
        if replayed != self.visible {
            let bad = replayed
                .iter()
                .find(|(k, v)| self.visible.get(k) != Some(v))
                .map(|(k, v)| format!("key {k}: replay says {v:?}, the model holds {:?}", self.visible.get(k)))
                .unwrap_or_else(|| "sizes differ".to_string());
            return Some(format!(
                "the reference model disagrees with a from-scratch replay of its own {}-mutation log ({bad})",
                self.log.len()));
        }
        let mut last: Option<Key> = None;
        for k in self.visible.keys() {
            if let Some(prev) = last {
                if prev >= *k {
                    return Some(format!("the reference visible set is not strictly ascending at {k}"));
                }
            }
            last = Some(*k);
        }
        None
    }
}

/* ------------------------------ helpers ----------------------------- */

/// One decimal place, computed in integers: no floating point crosses the
/// wasm boundary in this course.
fn tenths(numer: u64, denom: u64) -> u64 {
    if denom == 0 { 0 } else { numer * 10 / denom }
}

fn show(t: u64) -> String {
    format!("{}.{}", t / 10, t % 10)
}

/// The store's shape, which is also its bill. Every cost number in this
/// suite is derived from exactly these observable fields.
fn shape(store: &Store) -> String {
    let runs: Vec<String> = store.runs.iter().map(|r| r.entries.len().to_string()).collect();
    format!(
        "memtable {} / {} run(s) [{}] / base {} rows / {} levels probed per read / {} flushes / {} compactions / {} mutations since the last one",
        store.memtable.len(),
        store.runs.len(),
        runs.join(","),
        store.base.len(),
        merge_on_read::read_probes(store),
        store.flushes,
        store.compactions,
        store.since_compaction)
}

/// Structural invariants of the physical layout. The base and every run are
/// sorted, unique runs — `compact` rewrites the base out of the student's
/// `merge_all`, so an unsorted base is a merge bug that a binary search
/// will convert into wrong answers later.
fn structure_errors(store: &Store) -> Option<String> {
    for w in store.base.windows(2) {
        if w[0].key >= w[1].key {
            return Some(format!(
                "the base is not strictly ascending by key: {} is followed by {}. The base is a sorted, unique, immutable run — it is rewritten from your merge_all, so this is a merge that emitted rows out of order or emitted a key twice.",
                w[0].key, w[1].key));
        }
    }
    for (i, run) in store.runs.iter().enumerate() {
        for w in run.entries.windows(2) {
            if w[0].key >= w[1].key {
                return Some(format!(
                    "run {i} is not strictly ascending by key: {} is followed by {}",
                    w[0].key, w[1].key));
            }
        }
    }
    for (k, e) in &store.memtable {
        if e.key != *k {
            return Some(format!(
                "the memtable holds an entry whose key field is {} but which is filed under key {k} — the key a read looks up and the key the entry claims must be the same one",
                e.key));
        }
    }
    None
}

/// Every key the model or the store has ever heard of, plus a little
/// padding: the universe a "one visible version per key" claim is checked
/// over.
fn universe(model: &Model, store: &Store, pad: u64) -> Vec<Key> {
    let mut keys: BTreeMap<Key, ()> = BTreeMap::new();
    for (k, _, _) in &model.log {
        keys.insert(*k, ());
    }
    for r in &store.base {
        keys.insert(r.key, ());
    }
    for k in 0..pad {
        keys.insert(k, ());
    }
    keys.into_keys().collect()
}

/// `read` against the model, key by key. The absolute.
fn agreement(store: &Store, model: &Model, keys: &[Key], what: &str) -> Result<(), String> {
    for &k in keys {
        let got = merge_on_read::read(store, k);
        let want = model.get(k);
        if got != want {
            return Err(explain_read(store, model, k, got, want, what));
        }
    }
    Ok(())
}

/// Why a point read is wrong, in the terms of the level it should have come
/// from. The diagnosis a student can act on.
fn explain_read(
    store: &Store,
    model: &Model,
    key: Key,
    got: Option<Version>,
    want: Option<Version>,
    what: &str,
) -> String {
    let where_is_it = locate(store, key);
    let why = match (got, want) {
        (None, Some(w)) => format!(
            "you returned None for a key that is visible with value {} at seq {}. Either a level was not consulted, or a tombstone from an OLDER level beat a newer write — recency is a position: memtable, then runs newest-first, then base.",
            w.value, w.seq),
        (Some(g), None) => format!(
            "you returned value {} (seq {}) for a key that is NOT visible. Either a tombstone was treated as \"no opinion\" and the search continued into an older level — a delete that resurrects the row it deleted — or the base version of a deleted key was returned.",
            g.value, g.seq),
        (Some(g), Some(w)) if g.value != w.value => format!(
            "you returned value {} (seq {}), the visible version is value {} (seq {}) — an older version won the merge",
            g.value, g.seq, w.value, w.seq),
        (Some(g), Some(w)) => format!(
            "you returned the right value ({}) from the WRONG version: seq {} instead of seq {}. The two versions happen to share a value, so nothing looks wrong — which is exactly why the seq is graded. A merge that returns a stale version is wrong whenever the values differ, and this workload contains keys written twice with the same value on purpose.",
            g.value, g.seq, w.seq),
        (None, None) => "the two agree; this message is a harness bug".to_string(),
    };
    format!(
        "{what}: read(key {key}) — {why} Where that key lives right now: {where_is_it}. Store: {}. Model: {} visible keys after {} mutations.",
        shape(store), model.visible.len(), model.log.len())
}

/// Which levels mention a key, newest first — the fact a wrong read is
/// almost always explained by.
fn locate(store: &Store, key: Key) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(e) = store.memtable.get(&key) {
        parts.push(match e.value {
            Some(v) => format!("memtable: value {v} at seq {}", e.seq),
            None => format!("memtable: TOMBSTONE at seq {}", e.seq),
        });
    }
    for (i, run) in store.runs.iter().enumerate().rev() {
        if let Ok(at) = run.entries.binary_search_by_key(&key, |e| e.key) {
            let e = run.entries[at];
            parts.push(match e.value {
                Some(v) => format!("run {i}: value {v} at seq {}", e.seq),
                None => format!("run {i}: TOMBSTONE at seq {}", e.seq),
            });
        }
    }
    if let Ok(at) = store.base.binary_search_by_key(&key, |r| r.key) {
        let r = store.base[at];
        parts.push(format!("base: value {} at seq {}", r.value, r.seq));
    }
    if parts.is_empty() {
        return "no level mentions it".to_string();
    }
    parts.join(" | ")
}

/// A merged output, judged completely: ordered, duplicate-free, equal to
/// the model, and consistent with `read`.
fn merged_ok(rows: &[BaseRow], want: &[BaseRow], what: &str) -> Result<(), String> {
    for w in rows.windows(2) {
        if w[0].key == w[1].key {
            return Err(format!(
                "{what}: key {} appears twice in the merged output (values {} and {}). Exactly one version of a key is visible: the newest. Emitting the base row AND the delta entry is the classic shape of this bug — the merge has to CHOOSE, not concatenate.",
                w[0].key, w[0].value, w[1].value));
        }
        if w[0].key > w[1].key {
            return Err(format!(
                "{what}: the merged output is not ascending — key {} is followed by key {}. Base rows and delta entries have to come out as one ordered stream; appending the delta after the base leaves the output sorted in two pieces, which is not sorted.",
                w[0].key, w[1].key));
        }
    }
    if rows.len() != want.len() {
        let extra: Vec<Key> = rows
            .iter()
            .map(|r| r.key)
            .filter(|k| !want.iter().any(|w| w.key == *k))
            .take(4)
            .collect();
        let missing: Vec<Key> = want
            .iter()
            .map(|r| r.key)
            .filter(|k| !rows.iter().any(|w| w.key == *k))
            .take(4)
            .collect();
        return Err(format!(
            "{what}: {} rows, want {}. Keys you emit that are not visible: {extra:?} (deleted keys emitted as rows, or tombstones emitted as rows). Visible keys you omit: {missing:?}.",
            rows.len(), want.len()));
    }
    for (i, (g, w)) in rows.iter().zip(want).enumerate() {
        if g != w {
            let why = if g.key != w.key {
                "a key is out of place — the merge is not walking base and delta in one ascending order"
            } else if g.value != w.value {
                "the value is from an older version — a newer level's entry was passed over"
            } else {
                "the value is right and the seq is stale: the row came from the base (or an older run) when a newer version of that key exists. Nothing looks wrong until two versions differ."
            };
            return Err(format!(
                "{what}: row {i} is {g:?}, want {w:?} — {why}"));
        }
    }
    Ok(())
}

/// A store built by replaying a script of mutations, with the model kept in
/// step. `flush` and `compact` points are explicit so that a level boundary
/// can be placed exactly where a bug hides.
enum Step {
    W(Key, i64),
    D(Key),
    Flush,
    Compact,
}

/* ------------------------------ checks ------------------------------ */

/// 1. read_your_writes: the absolute. A read after a write sees that write
///    — whatever level it landed on, and whatever flush or compaction it
///    triggered on the way in.
pub fn check_read_your_writes() -> Check {
    const ID: &str = "read_your_writes";
    const LABEL: &str = "a read after a write sees the write, always";

    let base: Vec<BaseRow> = vec![
        BaseRow { key: 10, value: 100, seq: 0 },
        BaseRow { key: 20, value: 200, seq: 1 },
        BaseRow { key: 30, value: 300, seq: 2 },
    ];

    // the scripted phase: every case that has ever hidden a stale read
    let script: Vec<(Step, &str)> = vec![
        (Step::W(40, 400), "a key the base has never seen"),
        (Step::W(20, 999), "an overwrite of a base key"),
        (Step::W(20, 1001), "a second overwrite, same memtable"),
        (Step::W(20, 1001), "the same VALUE again — only the seq moves, and the seq is graded"),
        (Step::D(20), "a tombstone over a key that lives in the base"),
        (Step::W(20, 7), "a re-insert after the delete"),
        (Step::Flush, "the memtable is sealed into a run"),
        (Step::W(20, 8), "an overwrite of a key that now lives in a run"),
        (Step::D(40), "a tombstone over a key that exists ONLY in the delta"),
        (Step::W(40, 41), "a re-insert of that delta-only key"),
        (Step::Flush, "a second run"),
        (Step::W(10, 11), "an overwrite of a base key with two runs standing"),
        (Step::Flush, "a third run"),
        (Step::D(30), "a tombstone with three runs standing"),
        (Step::Compact, "compaction folds all of it into a new base"),
        (Step::W(30, 31), "a write immediately after compaction, into a fresh empty memtable"),
        (Step::D(10), "a delete immediately after compaction"),
        (Step::W(50, 500), "a new key immediately after compaction"),
        (Step::Compact, "a second compaction, over a delta the first one never saw"),
        (Step::W(50, 501), "a write after the second compaction"),
        (Step::D(999), "a delete of a key that never existed anywhere"),
        (Step::W(999, 1), "and then a write of it"),
    ];

    let mut store = Store::new(base.clone());
    let mut model = Model::new();
    model.seed(&base);
    let mut mutations = 0usize;

    for (step, why) in &script {
        match step {
            Step::W(k, v) => {
                let seq = merge_on_read::write(&mut store, *k, *v);
                model.apply(*k, Some(*v), seq);
                mutations += 1;
                let got = merge_on_read::read(&store, *k);
                let want = Some(Version { value: *v, seq });
                if got != want {
                    return Check::fail(ID, LABEL, format!(
                        "{}  (the case: {why})",
                        explain_read(&store, &model, *k, got, want, "immediately after write")));
                }
            }
            Step::D(k) => {
                let seq = merge_on_read::delete(&mut store, *k);
                model.apply(*k, None, seq);
                mutations += 1;
                let got = merge_on_read::read(&store, *k);
                if got.is_some() {
                    return Check::fail(ID, LABEL, format!(
                        "{}  (the case: {why})",
                        explain_read(&store, &model, *k, got, None, "immediately after delete")));
                }
            }
            Step::Flush => merge_on_read::flush(&mut store),
            Step::Compact => merge_on_read::compact(&mut store),
        }
        if let Some(msg) = structure_errors(&store) {
            return Check::fail(ID, LABEL, format!("after \"{why}\": {msg}"));
        }
        let keys = universe(&model, &store, 60);
        if let Err(msg) = agreement(&store, &model, &keys, &format!("after \"{why}\"")) {
            return Check::fail(ID, LABEL, msg);
        }
    }

    // the flush boundary, walked one write at a time: the 64th distinct key
    // seals the memtable inside the same `write` call that stored it
    let mut store = Store::empty();
    let mut model = Model::new();
    for i in 0..(merge_on_read::FLUSH_ROWS as u64 * 3 + 5) {
        let seq = merge_on_read::write(&mut store, i, i as i64 * 3);
        model.apply(i, Some(i as i64 * 3), seq);
        mutations += 1;
        let got = merge_on_read::read(&store, i);
        let want = Some(Version { value: i as i64 * 3, seq });
        if got != want {
            return Check::fail(ID, LABEL, format!(
                "{}  (the case: write number {} of a run of distinct keys — the memtable flushes at FLUSH_ROWS = {} and the write that triggers the flush must survive it)",
                explain_read(&store, &model, i, got, want, "immediately after write"),
                i + 1, merge_on_read::FLUSH_ROWS));
        }
    }

    // and the seeded phase: every mutation read back, plus three unrelated
    // keys checked against the model, over a store that flushes and
    // compacts underneath the workload
    let mut rng = Rng(0x2E01_5EED);
    let base: Vec<BaseRow> = (0..32u64).map(|i| BaseRow { key: i * 3, value: i as i64 * 11, seq: i }).collect();
    let mut store = Store::new(base.clone());
    let mut model = Model::new();
    model.seed(&base);
    const SEEDED: usize = 1200;
    for step in 0..SEEDED {
        let key = rng.key(96);
        if rng.below(4) == 0 {
            let seq = merge_on_read::delete(&mut store, key);
            model.apply(key, None, seq);
            let got = merge_on_read::read(&store, key);
            if got.is_some() {
                return Check::fail(ID, LABEL, format!(
                    "{}  (seeded step {step})",
                    explain_read(&store, &model, key, got, None, "immediately after delete")));
            }
        } else {
            let value = rng.value();
            let seq = merge_on_read::write(&mut store, key, value);
            model.apply(key, Some(value), seq);
            let got = merge_on_read::read(&store, key);
            let want = Some(Version { value, seq });
            if got != want {
                return Check::fail(ID, LABEL, format!(
                    "{}  (seeded step {step})",
                    explain_read(&store, &model, key, got, want, "immediately after write")));
            }
        }
        mutations += 1;
        for _ in 0..3 {
            let k = rng.key(96);
            let got = merge_on_read::read(&store, k);
            let want = model.get(k);
            if got != want {
                return Check::fail(ID, LABEL, explain_read(&store, &model, k, got, want, format!("seeded step {step}").as_str()));
            }
        }
    }
    if let Some(msg) = model.audit() {
        return Check::fail(ID, LABEL, format!("HARNESS BUG: {msg} — please report this"));
    }

    Check::pass(ID, LABEL, format!(
        "{} scripted cases and {mutations} mutations, every one read back immediately and matched on VALUE AND SEQ — including writes that trigger a flush, writes into a fresh memtable after compaction, re-inserts after deletes, and a key rewritten with the value it already had. Final store: {}",
        script.len(), shape(&store)))
}

/// 2. merge_ordered: the merged view is one ordered, duplicate-free stream
///    across base and delta — and it agrees with the point-read path on
///    every key.
pub fn check_merge_ordered() -> Check {
    const ID: &str = "merge_ordered";
    const LABEL: &str = "merge output is ordered and duplicate-free across base and delta";
    let mut rng = Rng(0x4D_3247_4F52);

    // hand-built stores, each one a different way for a merge to be wrong
    let mut cases: Vec<(String, Store, Model)> = Vec::new();
    let build = |name: &str, base: Vec<BaseRow>, steps: Vec<Step>| -> (String, Store, Model) {
        let mut store = Store::new(base.clone());
        let mut model = Model::new();
        model.seed(&base);
        for s in steps {
            match s {
                Step::W(k, v) => {
                    let seq = merge_on_read::write(&mut store, k, v);
                    model.apply(k, Some(v), seq);
                }
                Step::D(k) => {
                    let seq = merge_on_read::delete(&mut store, k);
                    model.apply(k, None, seq);
                }
                Step::Flush => merge_on_read::flush(&mut store),
                Step::Compact => merge_on_read::compact(&mut store),
            }
        }
        (name.to_string(), store, model)
    };

    let base3: Vec<BaseRow> = vec![
        BaseRow { key: 10, value: 100, seq: 0 },
        BaseRow { key: 20, value: 200, seq: 1 },
        BaseRow { key: 30, value: 300, seq: 2 },
    ];
    cases.push(build("an empty table", Vec::new(), Vec::new()));
    cases.push(build("base only, no delta", base3.clone(), Vec::new()));
    cases.push(build("delta only, written in DESCENDING key order", Vec::new(),
        vec![Step::W(90, 9), Step::W(70, 7), Step::W(50, 5), Step::W(30, 3), Step::W(10, 1)]));
    cases.push(build("every base key overwritten", base3.clone(),
        vec![Step::W(30, -3), Step::W(20, -2), Step::W(10, -1)]));
    cases.push(build("delta keys interleaved between base keys", base3.clone(),
        vec![Step::W(15, 15), Step::W(25, 25), Step::W(5, 5), Step::W(35, 35)]));
    cases.push(build("delta keys below and above the whole base", base3.clone(),
        vec![Step::W(1, 1), Step::W(u64::MAX, -1), Step::W(0, 0)]));
    cases.push(build("every visible key deleted", base3.clone(),
        vec![Step::W(40, 4), Step::D(10), Step::D(20), Step::D(30), Step::D(40)]));
    cases.push(build("one key in the base and in three separate runs", base3.clone(),
        vec![Step::W(20, 1), Step::Flush, Step::W(20, 2), Step::Flush, Step::W(20, 3), Step::Flush, Step::W(20, 4)]));
    cases.push(build("one key written into four successive runs, memtable empty", base3.clone(),
        vec![Step::W(20, 1), Step::Flush, Step::W(20, 2), Step::Flush, Step::W(20, 3), Step::Flush, Step::W(20, 4), Step::Flush]));
    cases.push(build("a tombstone in the NEWEST run over values in older runs", base3.clone(),
        vec![Step::W(20, 1), Step::Flush, Step::W(20, 2), Step::Flush, Step::D(20), Step::Flush]));
    cases.push(build("a re-insert in the newest run over a tombstone in the oldest", base3.clone(),
        vec![Step::D(20), Step::Flush, Step::W(20, 2), Step::Flush, Step::W(30, 3), Step::Flush]));
    cases.push(build("a tombstone in a run and a re-insert in the memtable", base3.clone(),
        vec![Step::D(10), Step::Flush, Step::W(10, 42)]));
    cases.push(build("a write in a run and a tombstone in the memtable", base3.clone(),
        vec![Step::W(10, 42), Step::Flush, Step::D(10)]));
    cases.push(build("compacted, then written again", base3.clone(),
        vec![Step::W(20, 2), Step::W(40, 4), Step::Compact, Step::W(50, 5), Step::D(10)]));
    cases.push(build("compacted twice with nothing in between", base3.clone(),
        vec![Step::W(20, 2), Step::Compact, Step::Compact]));
    cases.push(build("a delta larger than the base", base3.clone(),
        (0..200u64).map(|i| Step::W(i * 7, i as i64)).collect()));

    let mut rows_compared = 0usize;
    for (name, store, model) in &cases {
        if let Some(msg) = structure_errors(store) {
            return Check::fail(ID, LABEL, format!("{name}: {msg}"));
        }
        let got = merge_on_read::merge_all(store);
        let want = model.rows();
        if let Err(msg) = merged_ok(&got, &want, &format!("merge_all over {name}")) {
            return Check::fail(ID, LABEL, format!("{msg} Store: {}", shape(store)));
        }
        rows_compared += want.len();
        let keys = universe(model, store, 40);
        if let Err(msg) = agreement(store, model, &keys, &format!("{name} (merge_all agreed; the point read did not)")) {
            return Check::fail(ID, LABEL, msg);
        }
        // the full range must equal the full merge — two entry points, one
        // answer
        let full = merge_on_read::scan_range(store, 0, u64::MAX);
        if full != got {
            return Check::fail(ID, LABEL, format!(
                "{name}: scan_range(0, u64::MAX) returned {} rows and merge_all returned {} — the widest possible range IS the whole table, and two answers to one question is how a fast path and a correct path drift apart. Store: {}",
                full.len(), got.len(), shape(store)));
        }
    }

    // ranges, on a store with keys at known places: 10, 20, 30 in the base,
    // 15 and 25 in the delta, 20 deleted
    let (name, store, model) = build("base 10/20/30 + delta 15/25, key 20 deleted", base3.clone(),
        vec![Step::W(15, 15), Step::Flush, Step::W(25, 25), Step::D(20)]);
    let range_cases: Vec<(Key, Key, &str)> = vec![
        (0, u64::MAX, "the whole key space"),
        (1, 0, "lo > hi: a range that contradicts itself matches nothing, anywhere"),
        (20, 10, "lo > hi across live keys"),
        (10, 10, "a single key, present"),
        (20, 20, "a single key, deleted"),
        (11, 14, "a window between two keys, containing nothing"),
        (10, 15, "both bounds inclusive, both on real keys"),
        (11, 15, "the lower bound just past a key"),
        (15, 16, "the upper bound just past a key"),
        (16, 24, "a window whose only key is deleted"),
        (25, u64::MAX, "an open-ended tail"),
        (0, 9, "everything below the first key"),
        (31, u64::MAX, "everything above the last key"),
        (15, 25, "a window that starts and ends on delta keys"),
        (u64::MAX, u64::MAX, "the largest possible key"),
    ];
    for (lo, hi, why) in &range_cases {
        let got = merge_on_read::scan_range(&store, *lo, *hi);
        let want = model.range(*lo, *hi);
        if let Err(msg) = merged_ok(&got, &want, &format!("scan_range({lo}, {hi}) over {name} — {why}")) {
            return Check::fail(ID, LABEL, msg);
        }
        rows_compared += want.len();
    }

    // and seeded: nine stores at different delta-to-base ratios, each with
    // twelve random windows
    let mut ranges_checked = range_cases.len();
    for round in 0..9usize {
        let base_n = [0usize, 1, 8, 64, 256, 33, 7, 128, 512][round];
        let base: Vec<BaseRow> = (0..base_n as u64)
            .map(|i| BaseRow { key: i * 2, value: i as i64 * 5 - 7, seq: i })
            .collect();
        let mut store = Store::new(base.clone());
        let mut model = Model::new();
        model.seed(&base);
        let span = (base_n as u64 * 2 + 16).max(24);
        for _ in 0..(40 + round * 90) {
            let key = rng.key(span);
            if rng.below(3) == 0 {
                let seq = merge_on_read::delete(&mut store, key);
                model.apply(key, None, seq);
            } else {
                let value = rng.value();
                let seq = merge_on_read::write(&mut store, key, value);
                model.apply(key, Some(value), seq);
            }
        }
        if let Some(msg) = structure_errors(&store) {
            return Check::fail(ID, LABEL, format!("seeded round {round}: {msg}"));
        }
        let got = merge_on_read::merge_all(&store);
        let want = model.rows();
        if let Err(msg) = merged_ok(&got, &want, &format!("merge_all over seeded round {round} (base {base_n} rows, {})", shape(&store))) {
            return Check::fail(ID, LABEL, msg);
        }
        rows_compared += want.len();
        let keys = universe(&model, &store, span.min(4096));
        if let Err(msg) = agreement(&store, &model, &keys, &format!("seeded round {round} (merge_all agreed; the point read did not — the two paths must resolve every key to the same version)")) {
            return Check::fail(ID, LABEL, msg);
        }
        for _ in 0..12 {
            let a = rng.key(span + 8);
            let b = rng.key(span + 8);
            let (lo, hi) = if rng.below(8) == 0 { (a.max(b), a.min(b)) } else { (a.min(b), a.max(b)) };
            let got = merge_on_read::scan_range(&store, lo, hi);
            let want = model.range(lo, hi);
            if let Err(msg) = merged_ok(&got, &want, &format!("scan_range({lo}, {hi}) over seeded round {round}")) {
                return Check::fail(ID, LABEL, msg);
            }
            ranges_checked += 1;
            rows_compared += want.len();
        }
        // compaction must not change any answer, only the cost of it
        let before = got;
        let probes_before = merge_on_read::read_probes(&store);
        merge_on_read::compact(&mut store);
        if let Some(msg) = structure_errors(&store) {
            return Check::fail(ID, LABEL, format!("seeded round {round}, after compaction: {msg}"));
        }
        let after = merge_on_read::merge_all(&store);
        if after != before {
            return Check::fail(ID, LABEL, format!(
                "seeded round {round}: compaction CHANGED the answer — {} visible rows before, {} after. Compaction rewrites bytes and folds levels; it must never alter which version of a key is visible. Since compact() rewrites the base from your merge_all, a merge bug shows up here as data loss.",
                before.len(), after.len()));
        }
        if after != store.base {
            return Check::fail(ID, LABEL, format!(
                "seeded round {round}: after compaction the base ({} rows) is not the merged view ({} rows) — compaction folds the whole delta into the base, so the base must BE the visible table and nothing should be left behind it",
                store.base.len(), after.len()));
        }
        if merge_on_read::read_probes(&store) > probes_before.max(1) {
            return Check::fail(ID, LABEL, format!(
                "seeded round {round}: compaction did not reduce the levels a read must probe ({} before, {} after) — a compaction that leaves the delta standing is a bill with no benefit",
                probes_before, merge_on_read::read_probes(&store)));
        }
    }

    Check::pass(ID, LABEL, format!(
        "{} hand-built stores, {} range windows and {rows_compared} merged rows exact — strictly ascending, one row per key, no tombstones emitted, scan_range(0, u64::MAX) identical to merge_all, and compaction proven answer-preserving on nine stores",
        cases.len() + 1, ranges_checked))
}

/// 3. delete_semantics: a delete is a write of a tombstone, and after any
///    sequence of writes and deletes EXACTLY ONE version of a key is
///    visible — or none.
pub fn check_delete_semantics() -> Check {
    const ID: &str = "delete_semantics";
    const LABEL: &str = "deletes and updates resolve to exactly one visible version per key";

    let base3: Vec<BaseRow> = vec![
        BaseRow { key: 10, value: 100, seq: 0 },
        BaseRow { key: 20, value: 200, seq: 1 },
        BaseRow { key: 30, value: 300, seq: 2 },
    ];

    // (name, base, steps, the key the case is about, what must be visible)
    let cases: Vec<(&str, Vec<BaseRow>, Vec<Step>, Key, Option<i64>, &str)> = vec![
        ("a tombstone over a key that exists ONLY in the delta, same memtable",
         base3.clone(), vec![Step::W(50, 5), Step::D(50)], 50, None,
         "the key was never in the base; the tombstone has nothing older to shadow, and the write it shadows is in the same level it is"),
        ("a tombstone over a delta-only key, one flush apart",
         base3.clone(), vec![Step::W(50, 5), Step::Flush, Step::D(50)], 50, None,
         "the write is in a run and the tombstone is in the memtable: newest level wins, and the newest level says gone"),
        ("a tombstone over a delta-only key, both in the same run",
         base3.clone(), vec![Step::W(50, 5), Step::D(50), Step::Flush], 50, None,
         "the memtable keeps one entry per key, so the flushed run holds the tombstone and not the write"),
        ("a tombstone over a delta-only key, then compaction",
         base3.clone(), vec![Step::W(50, 5), Step::D(50), Step::Compact], 50, None,
         "compaction is where a tombstone is finally discharged: the key must be absent from the new base, and the tombstone must not survive as a row"),
        ("a re-insert after a delete, same memtable",
         base3.clone(), vec![Step::D(10), Step::W(10, 111)], 10, Some(111),
         "a tombstone is not a gravestone: a later write of the same key is simply newer"),
        ("a re-insert after a delete, one flush apart",
         base3.clone(), vec![Step::D(10), Step::Flush, Step::W(10, 111)], 10, Some(111),
         "the tombstone is in a run and the write is newer"),
        ("a re-insert after a delete, then flushed again",
         base3.clone(), vec![Step::D(10), Step::Flush, Step::W(10, 111), Step::Flush], 10, Some(111),
         "two runs, the newer of which holds the re-insert"),
        ("a re-insert after a delete, then compacted",
         base3.clone(), vec![Step::D(10), Step::Flush, Step::W(10, 111), Step::Compact], 10, Some(111),
         "the new base holds exactly one row for the key, carrying the re-inserted version"),
        ("delete in run 0, re-insert in run 1, delete in run 2",
         base3.clone(), vec![Step::D(20), Step::Flush, Step::W(20, 9), Step::Flush, Step::D(20), Step::Flush], 20, None,
         "three runs disagree; the newest one decides, and a read must not stop at the first level that merely MENTIONS the key in the wrong direction"),
        ("delete, re-insert, delete, re-insert across four runs",
         base3.clone(), vec![Step::D(30), Step::Flush, Step::W(30, 1), Step::Flush, Step::D(30), Step::Flush, Step::W(30, 2), Step::Flush], 30, Some(2),
         "alternating versions: only the newest survives"),
        ("a delete of a key that never existed anywhere",
         base3.clone(), vec![Step::D(777)], 777, None,
         "legal, and a no-op as far as any answer goes — but the tombstone must never surface as a visible row, and compaction must not invent a key for it"),
        ("a delete of a never-existing key, then compaction",
         base3.clone(), vec![Step::D(777), Step::Compact], 777, None,
         "the base after compaction holds visible rows only"),
        ("the same key deleted twice",
         base3.clone(), vec![Step::D(10), Step::D(10)], 10, None,
         "idempotent: two tombstones are one absence, not a resurrection"),
        ("update, delete, update",
         base3.clone(), vec![Step::W(10, 1), Step::D(10), Step::W(10, 2)], 10, Some(2),
         "the last word is the visible one"),
        ("update in a run, delete in a run, update in the memtable",
         base3.clone(), vec![Step::W(10, 1), Step::Flush, Step::D(10), Step::Flush, Step::W(10, 2)], 10, Some(2),
         "the levels are consulted newest first and the search stops at the first opinion"),
        ("every key deleted, then compacted",
         base3.clone(), vec![Step::D(10), Step::D(20), Step::D(30), Step::Compact], 10, None,
         "compacting an entirely deleted table yields an EMPTY base, not a base of tombstones"),
        ("delete then re-insert on an empty table",
         Vec::new(), vec![Step::D(5), Step::W(5, 55), Step::D(5), Step::W(5, 56)], 5, Some(56),
         "no base at all: every version lives in the delta"),
        ("a tombstone that survives a flush and a compaction",
         base3.clone(), vec![Step::D(20), Step::Flush, Step::W(99, 9), Step::Flush, Step::Compact, Step::W(98, 8)], 20, None,
         "the delete happened three levels ago and one compaction back; absence is not something that decays"),
    ];

    let mut checked_keys = 0usize;
    for (name, base, steps, about, want_value, why) in &cases {
        let mut store = Store::new(base.clone());
        let mut model = Model::new();
        model.seed(base);
        for s in steps {
            match s {
                Step::W(k, v) => {
                    let seq = merge_on_read::write(&mut store, *k, *v);
                    model.apply(*k, Some(*v), seq);
                }
                Step::D(k) => {
                    let seq = merge_on_read::delete(&mut store, *k);
                    model.apply(*k, None, seq);
                }
                Step::Flush => merge_on_read::flush(&mut store),
                Step::Compact => merge_on_read::compact(&mut store),
            }
        }
        if let Some(msg) = structure_errors(&store) {
            return Check::fail(ID, LABEL, format!("{name}: {msg}"));
        }

        // the case's own key, by value
        let got = merge_on_read::read(&store, *about);
        match (got, want_value) {
            (Some(g), Some(w)) if g.value == *w => {}
            (None, None) => {}
            _ => {
                let want = match want_value {
                    Some(v) => Some(Version {
                        value: *v,
                        seq: model.get(*about).map(|m| m.seq).unwrap_or(0),
                    }),
                    None => None,
                };
                return Check::fail(ID, LABEL, format!(
                    "{}  (the case: {name} — {why})",
                    explain_read(&store, &model, *about, got, want, "after the scripted deletes and updates")));
            }
        }

        // "exactly one visible version" as an arithmetic claim, over every
        // key anything has ever touched
        let merged = merge_on_read::merge_all(&store);
        if let Err(msg) = merged_ok(&merged, &model.rows(), &format!("merge_all over \"{name}\"")) {
            return Check::fail(ID, LABEL, format!("{msg} ({why})"));
        }
        for k in universe(&model, &store, 40) {
            let visible = merge_on_read::read(&store, k);
            let rows = merged.iter().filter(|r| r.key == k).count();
            let in_range = merge_on_read::scan_range(&store, k, k);
            if rows != usize::from(visible.is_some()) {
                return Check::fail(ID, LABEL, format!(
                    "{name}: key {k} has {rows} row(s) in the merged output but read() says it is {} — exactly one version of a key is visible, or none. {}",
                    if visible.is_some() { "visible" } else { "not visible" },
                    if rows > 1 { "More than one row means the merge kept a superseded version alongside the newest." } else { "Zero rows for a visible key means the merge dropped a live row; a row for an invisible key means a tombstone was ignored or emitted." }));
            }
            if in_range.len() != rows {
                return Check::fail(ID, LABEL, format!(
                    "{name}: scan_range({k}, {k}) returned {} row(s) and merge_all has {rows} for that key — the single-key window is the same question asked twice",
                    in_range.len()));
            }
            if let (Some(v), Some(row)) = (visible, merged.iter().find(|r| r.key == k)) {
                if row.value != v.value || row.seq != v.seq {
                    return Check::fail(ID, LABEL, format!(
                        "{name}: key {k} reads as value {} (seq {}) but merges as value {} (seq {}) — the read path and the merge path must resolve a key to the SAME version",
                        v.value, v.seq, row.value, row.seq));
                }
            }
            checked_keys += 1;
        }
        // compaction discharges tombstones: the base is the visible table
        let mut compacted = store.clone();
        merge_on_read::compact(&mut compacted);
        if compacted.base != model.rows() {
            return Check::fail(ID, LABEL, format!(
                "{name}: after compaction the base holds {} rows and the visible table has {} — compaction is where a tombstone is discharged: deleted keys leave, live keys stay exactly once, and no tombstone becomes a row",
                compacted.base.len(), model.rows().len()));
        }
        if !compacted.memtable.is_empty() || !compacted.runs.is_empty() {
            return Check::fail(ID, LABEL, format!(
                "{name}: after compaction the delta is not empty ({} memtable entries, {} runs) — compaction folds ALL of it in, and anything left behind is a level every later read still pays for",
                compacted.memtable.len(), compacted.runs.len()));
        }
    }

    // seeded, delete-heavy: half the mutations are deletes over a small key
    // space, so the same key is deleted and re-inserted many times
    let mut rng = Rng(0xDEAD_C0DE_51);
    let base: Vec<BaseRow> = (0..64u64).map(|i| BaseRow { key: i * 2, value: i as i64, seq: i }).collect();
    let mut store = Store::new(base.clone());
    let mut model = Model::new();
    model.seed(&base);
    const OPS: usize = 1000;
    let mut deletes = 0usize;
    for step in 0..OPS {
        let key = rng.key(128);
        if rng.below(2) == 0 {
            let seq = merge_on_read::delete(&mut store, key);
            model.apply(key, None, seq);
            deletes += 1;
            if let Some(v) = merge_on_read::read(&store, key) {
                return Check::fail(ID, LABEL, format!(
                    "{}  (seeded delete-heavy step {step})",
                    explain_read(&store, &model, key, Some(v), None, "immediately after delete")));
            }
        } else {
            let value = rng.value();
            let seq = merge_on_read::write(&mut store, key, value);
            model.apply(key, Some(value), seq);
        }
        if step % 25 == 0 {
            if let Some(msg) = structure_errors(&store) {
                return Check::fail(ID, LABEL, format!("seeded step {step}: {msg}"));
            }
            let merged = merge_on_read::merge_all(&store);
            if let Err(msg) = merged_ok(&merged, &model.rows(), &format!("merge_all at seeded step {step} ({})", shape(&store))) {
                return Check::fail(ID, LABEL, msg);
            }
            let keys: Vec<Key> = (0..128).collect();
            if let Err(msg) = agreement(&store, &model, &keys, &format!("seeded step {step}")) {
                return Check::fail(ID, LABEL, msg);
            }
            checked_keys += keys.len();
        }
    }
    if let Some(msg) = model.audit() {
        return Check::fail(ID, LABEL, format!("HARNESS BUG: {msg} — please report this"));
    }

    Check::pass(ID, LABEL, format!(
        "{} scripted delete/update cases and {OPS} seeded operations ({deletes} of them deletes) over {checked_keys} key resolutions — tombstones for delta-only keys, re-inserts after deletes, alternating delete/insert across four runs, deletes of keys that never existed, and tombstones discharged by compaction all resolve to exactly one visible version or none. Final store: {}",
        cases.len(), shape(&store)))
}

/* ------------------------- the cost workload ------------------------ */
/* ONE workload, two bills. The same seeded stream of mutations and reads    */
/* feeds read_amp_bounded and write_amp_budget, so the two bands are         */
/* statements about the same policy and cannot both be satisfied by taste.   */

const COST_SEED: u64 = 0x0A_4D_4F52_C057;
const COST_BASE: u64 = 512;
const COST_SPAN: u64 = 1024;
const COST_MUTATIONS: u64 = 4096;

/// Bands. Read amplification is levels probed per read (a perfectly
/// compacted store needs 1); write amplification is rows rewritten per row
/// ingested. Both are counts.
const READ_AMP_CEIL: u64 = 60; // 6.0, in tenths
const WRITE_AMP_CEIL: u64 = 50; // 5.0, in tenths

#[derive(Default)]
struct Cost {
    reads: u64,
    probes: u64,
    late_reads: u64,
    late_probes: u64,
    peak_probes: usize,
    mutations: u64,
    rewritten: u64,
    compactions: u64,
    flushes: u64,
    peak_runs: usize,
    peak_delta: usize,
    final_base: usize,
}

/// Drive the shared workload. Every read is verified against the reference
/// model as it goes — cost is only ever graded on a store that is still
/// correct, so a policy that keeps its bills down by losing data fails here
/// before any band is evaluated.
fn drive_cost() -> Result<Cost, String> {
    let mut rng = Rng(COST_SEED);
    let base: Vec<BaseRow> = (0..COST_BASE)
        .map(|i| BaseRow { key: i * 2, value: i as i64 * 13 - 5, seq: i })
        .collect();
    let mut store = Store::new(base.clone());
    let mut model = Model::new();
    model.seed(&base);
    let mut c = Cost::default();

    for step in 0..COST_MUTATIONS {
        let key = rng.key(COST_SPAN);
        let compactions_before = store.compactions;
        if rng.below(4) == 0 {
            let seq = merge_on_read::delete(&mut store, key);
            model.apply(key, None, seq);
        } else {
            let value = rng.value();
            let seq = merge_on_read::write(&mut store, key, value);
            model.apply(key, Some(value), seq);
        }
        c.mutations += 1;

        // write amplification, charged from what the store actually looks
        // like: each compaction rewrote the base it left behind
        let did = store.compactions.saturating_sub(compactions_before);
        if did > 0 {
            c.compactions += did;
            c.rewritten += did * store.base.len() as u64;
        }
        c.flushes = store.flushes;
        c.peak_runs = c.peak_runs.max(store.runs.len());
        c.peak_delta = c.peak_delta.max(merge_on_read::delta_rows(&store));

        // read-your-writes, free, so cost is never measured on a store that
        // has quietly stopped answering
        let got = merge_on_read::read(&store, key);
        let want = model.get(key);
        if got != want {
            return Err(explain_read(&store, &model, key, got, want, &format!("cost workload step {step}")));
        }

        // one read per mutation, charged structurally
        let rkey = rng.key(COST_SPAN);
        let got = merge_on_read::read(&store, rkey);
        let want = model.get(rkey);
        if got != want {
            return Err(explain_read(&store, &model, rkey, got, want, &format!("cost workload step {step}")));
        }
        let probes = merge_on_read::read_probes(&store) as u64;
        c.reads += 1;
        c.probes += probes;
        c.peak_probes = c.peak_probes.max(probes as usize);
        if step >= COST_MUTATIONS * 3 / 4 {
            c.late_reads += 1;
            c.late_probes += probes;
        }

        if step % 512 == 0 {
            if let Some(msg) = structure_errors(&store) {
                return Err(format!("cost workload step {step}: {msg}"));
            }
        }
    }

    if let Some(msg) = model.audit() {
        return Err(format!("HARNESS BUG: {msg} — please report this"));
    }
    if merge_on_read::should_compact(&store) != merge_on_read::should_compact(&store) {
        return Err("should_compact returned two different answers for the same store — the policy must be PURE, or nobody can predict the bill it produces".to_string());
    }
    let merged = merge_on_read::merge_all(&store);
    merged_ok(&merged, &model.rows(), "merge_all at the end of the cost workload")?;
    c.final_base = store.base.len();
    Ok(c)
}

/// A sentence describing the workload, shared by both band messages.
fn workload_line(c: &Cost) -> String {
    format!(
        "{} mutations (3 writes to 1 delete) over {} keys on a {}-row base, one point read after each, FLUSH_ROWS = {}: {} flushes, {} compactions, peak delta {} rows in {} runs, final base {} rows",
        c.mutations, COST_SPAN, COST_BASE, merge_on_read::FLUSH_ROWS,
        c.flushes, c.compactions, c.peak_delta, c.peak_runs, c.final_base)
}

/// 4. read_amp_bounded: the first band. Levels probed per read, averaged
///    over the workload and again over its last quarter — because a policy
///    that compacts once early and then gives up passes an average and
///    still degrades.
pub fn check_read_amp_bounded() -> Check {
    const ID: &str = "read_amp_bounded";
    const LABEL: &str = "read amplification stays within band as the delta grows";
    let c = match drive_cost() {
        Ok(c) => c,
        Err(msg) => return Check::fail(ID, LABEL, msg),
    };

    let amp = tenths(c.probes, c.reads);
    let late = tenths(c.late_probes, c.late_reads);
    let write_amp = tenths(c.rewritten, c.mutations);
    let ceiling = show(READ_AMP_CEIL);

    if amp > READ_AMP_CEIL || late > READ_AMP_CEIL {
        let which = if amp > READ_AMP_CEIL { format!("overall {}", show(amp)) } else { format!("last quarter {}", show(late)) };
        return Check::fail(ID, LABEL, format!(
            "read amplification {which}, band ends at {ceiling}. {} probes over {} reads (last quarter {} over {}), peak {} levels. Read amplification is levels consulted per read divided by the 1 a perfectly compacted base would need, and it is charged from the SHAPE your policy leaves behind — runs standing plus the base plus a non-empty memtable — so no cleverness in `read` moves it. The only lever is compaction, and the only reason not to pull it is write_amp_budget, which currently reads {} against its own band of {}. A policy that never compacts lands near 34.0 here and 0.0 there; that is not a tradeoff, it is one side of one. Your workload: {}",
            c.probes, c.reads, c.late_probes, c.late_reads, c.peak_probes,
            show(write_amp), show(WRITE_AMP_CEIL), workload_line(&c)));
    }

    Check::pass(ID, LABEL, format!(
        "read amplification {} (band ≤ {ceiling}), holding at {} over the last quarter of the workload, peak {} levels on any single read. {}. The opposing bill on the same run: write amplification {} against a band of {} — both inside, which is what makes this a policy rather than a preference.",
        show(amp), show(late), c.peak_probes, workload_line(&c),
        show(write_amp), show(WRITE_AMP_CEIL)))
}

/// 5. write_amp_budget: the opposing band. Rows rewritten by compaction per
///    row ingested — the bill for holding read amplification down.
pub fn check_write_amp_budget() -> Check {
    const ID: &str = "write_amp_budget";
    const LABEL: &str = "compaction stays within its stated write-amplification budget";
    let c = match drive_cost() {
        Ok(c) => c,
        Err(msg) => return Check::fail(ID, LABEL, msg),
    };

    let amp = tenths(c.rewritten, c.mutations);
    let read_amp = tenths(c.probes, c.reads);
    let ceiling = show(WRITE_AMP_CEIL);

    if amp > WRITE_AMP_CEIL {
        let per = if c.compactions == 0 { 0 } else { c.rewritten / c.compactions };
        return Check::fail(ID, LABEL, format!(
            "write amplification {}, band ends at {ceiling}. {} rows rewritten for {} rows ingested across {} compactions ({per} rows per compaction). Every compaction rewrites the whole base to fold in a delta of whatever size you let accumulate, so the bill is roughly base_rows ÷ delta_rows_at_the_trigger: compacting when the delta is a thirtieth of the base costs about 30×, and compacting on every mutation costs about {} — the size of the base, every time, for one row of new data. Let the delta get fuller before you pay to fold it in. The opposing band is read_amp_bounded, currently {} against a ceiling of {}, so you have room to move toward. Your workload: {}",
            show(amp), c.rewritten, c.mutations, c.compactions,
            c.final_base, show(read_amp), show(READ_AMP_CEIL), workload_line(&c)));
    }

    Check::pass(ID, LABEL, format!(
        "write amplification {} (band ≤ {ceiling}) — {} rows rewritten for {} ingested across {} compactions. {}. The opposing bill on the same run: read amplification {} against a band of {}. Never compacting would score 0.0 here and fail read_amp_bounded at ~34.0; compacting on every write would score ~{}.0 here. Both bands inside means the number you chose is defensible to somebody who has to operate it.",
        show(amp), c.rewritten, c.mutations, c.compactions, workload_line(&c),
        show(read_amp), show(READ_AMP_CEIL), c.final_base))
}

/// 6. storm: 3000 seeded mixed read/write/delete operations across three
///    phases against the reference model, which is itself audited against a
///    from-scratch replay of its own log.
pub fn check_storm() -> Check {
    const ID: &str = "storm";
    const LABEL: &str = "3000 seeded mixed read/write/delete operations vs a reference model";
    let mut rng = Rng(0x5EED_4D4F_5200);
    const OPS_PER_PHASE: usize = 1000;

    // (name, base rows, key span, delete weight, why this phase exists)
    let phases: Vec<(&str, u64, u64, usize, &str)> = vec![
        ("a mid-sized base with a mixed workload", 256, 512, 4,
         "the ordinary case: overwrites, new keys and deletes over a base big enough that compaction is a real decision"),
        ("no base at all, sparse keys", 0, 65536, 5,
         "every mutation is a new key: the delta IS the table, and merges run with an empty base underneath"),
        ("a dense key space, heavy churn", 512, 64, 3,
         "64 keys and 1000 mutations: every key is written and deleted many times, so a stale version has many chances to win"),
    ];

    let mut counts: BTreeMap<&'static str, usize> = BTreeMap::new();
    let (mut merges, mut ranges, mut rows_compared) = (0usize, 0usize, 0usize);
    let (mut flushes, mut compactions, mut probes, mut reads) = (0u64, 0u64, 0u64, 0u64);
    let mut peak_delta = 0usize;
    let mut last_shape = String::new();

    for (name, base_n, span, del_weight, why) in &phases {
        let base: Vec<BaseRow> = (0..*base_n)
            .map(|i| BaseRow { key: i * 2, value: i as i64 * 3 + 1, seq: i })
            .collect();
        let mut store = Store::new(base.clone());
        let mut model = Model::new();
        model.seed(&base);

        for step in 0..OPS_PER_PHASE {
            let roll = rng.below(20);
            let key = rng.key(*span);
            if roll < *del_weight {
                let seq = merge_on_read::delete(&mut store, key);
                model.apply(key, None, seq);
                *counts.entry("delete").or_insert(0) += 1;
                if let Some(v) = merge_on_read::read(&store, key) {
                    return Check::fail(ID, LABEL, format!(
                        "{}  ({name}, step {step}; the phase exists because {why})",
                        explain_read(&store, &model, key, Some(v), None, "immediately after delete")));
                }
            } else if roll < 12 {
                let value = rng.value();
                let seq = merge_on_read::write(&mut store, key, value);
                model.apply(key, Some(value), seq);
                *counts.entry("write").or_insert(0) += 1;
                let got = merge_on_read::read(&store, key);
                let want = Some(Version { value, seq });
                if got != want {
                    return Check::fail(ID, LABEL, format!(
                        "{}  ({name}, step {step}; the phase exists because {why})",
                        explain_read(&store, &model, key, got, want, "immediately after write")));
                }
            } else if roll < 18 {
                *counts.entry("read").or_insert(0) += 1;
                let got = merge_on_read::read(&store, key);
                let want = model.get(key);
                if got != want {
                    return Check::fail(ID, LABEL, format!(
                        "{}  ({name}, step {step})",
                        explain_read(&store, &model, key, got, want, "point read")));
                }
                reads += 1;
                probes += merge_on_read::read_probes(&store) as u64;
            } else {
                *counts.entry("scan").or_insert(0) += 1;
                let a = rng.key(*span + 4);
                let b = rng.key(*span + 4);
                let (lo, hi) = if rng.below(10) == 0 { (a.max(b), a.min(b)) } else { (a.min(b), a.max(b)) };
                let got = merge_on_read::scan_range(&store, lo, hi);
                let want = model.range(lo, hi);
                if let Err(msg) = merged_ok(&got, &want, &format!("scan_range({lo}, {hi}) in {name} at step {step}")) {
                    return Check::fail(ID, LABEL, format!("{msg} Store: {}", shape(&store)));
                }
                ranges += 1;
                rows_compared += want.len();
            }

            peak_delta = peak_delta.max(merge_on_read::delta_rows(&store));

            if step % 100 == 0 {
                if let Some(msg) = model.audit() {
                    return Check::fail(ID, LABEL, format!("HARNESS BUG: {msg} — please report this"));
                }
                if let Some(msg) = structure_errors(&store) {
                    return Check::fail(ID, LABEL, format!("{name}, step {step}: {msg}"));
                }
                let merged = merge_on_read::merge_all(&store);
                if let Err(msg) = merged_ok(&merged, &model.rows(), &format!("merge_all in {name} at step {step} ({})", shape(&store))) {
                    return Check::fail(ID, LABEL, msg);
                }
                merges += 1;
                rows_compared += merged.len();
            }
        }

        // and at the end of the phase: fold everything in, and prove the
        // answer did not move
        let before = merge_on_read::merge_all(&store);
        if let Err(msg) = merged_ok(&before, &model.rows(), &format!("merge_all at the end of {name} ({})", shape(&store))) {
            return Check::fail(ID, LABEL, msg);
        }
        flushes += store.flushes;
        compactions += store.compactions;
        last_shape = shape(&store);
        merge_on_read::compact(&mut store);
        if let Some(msg) = structure_errors(&store) {
            return Check::fail(ID, LABEL, format!("{name}, after a final compaction: {msg}"));
        }
        let after = merge_on_read::merge_all(&store);
        if after != before {
            return Check::fail(ID, LABEL, format!(
                "{name}: a final compaction changed the visible table — {} rows before, {} after. Compaction moves bytes, never answers.",
                before.len(), after.len()));
        }
        if store.base != before {
            return Check::fail(ID, LABEL, format!(
                "{name}: after compaction the base is not the visible table ({} rows vs {})",
                store.base.len(), before.len()));
        }
        let keys: Vec<Key> = universe(&model, &store, 0);
        if let Err(msg) = agreement(&store, &model, &keys, &format!("{name}, after a final compaction")) {
            return Check::fail(ID, LABEL, msg);
        }
        merges += 2;
        rows_compared += after.len() + keys.len();
    }

    let mix: Vec<String> = counts.iter().map(|(k, v)| format!("{k} {v}")).collect();
    Check::pass(ID, LABEL, format!(
        "{} operations over {} phases model-exact ({}) — every mutation read back immediately, {merges} full merges and {ranges} range scans compared row for row against the reference ({rows_compared} rows), {flushes} flushes and {compactions} compactions along the way, peak delta {peak_delta} rows, {} levels probed per read on average. The reference model was audited against a from-scratch replay of its own mutation log at every checkpoint. Final store of the last phase: {last_shape}",
        OPS_PER_PHASE * phases.len(), phases.len(), mix.join(", "),
        show(tenths(probes, reads.max(1)))))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_read_your_writes(),
        check_merge_ordered(),
        check_delete_semantics(),
        check_read_amp_bounded(),
        check_write_amp_budget(),
        check_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "merge-on-read", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
