//! shuffle — forge lab 06 (columnspaces).
//!
//! A partitioned hash join with skew handling, and the broadcast-vs-
//! partition decision that precedes it. Labs 01–05 billed bytes read,
//! decoded and rewritten inside one process. This one bills bytes MOVED,
//! which is the only cost in the stack that a codec cannot touch.
//!
//! ┌────────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/shuffle.rs   (the only file with TODO(you))        │
//! │  DO NOT EDIT this file — it is the grading harness.                 │
//! └────────────────────────────────────────────────────────────────────┘
//!
//! What the harness is: an independent second implementation of the join —
//! a global build-and-probe over both whole sides, with no partitioning and
//! no salting anywhere in it — plus two ground truths for that reference. It
//! is audited against an O(n²) nested loop on every case small enough to
//! afford one, and against the closed form `Σ_k left(k)·right(k)` on every
//! case at all. If the reference ever disagrees with either, the suite
//! reports "HARNESS BUG" and fails, because a grader that is itself wrong
//! would silently excuse a wrong answer.
//!
//! The grading splits the way the production consequences do:
//!
//!   * `join_correct` and `storm` are ABSOLUTES with zero tolerance. The
//!     output is a MULTISET and it is exact: every matching pair once, no
//!     pair dropped, no pair duplicated. Duplicate keys on both sides, keys
//!     on one side only, empty inputs, one key holding the whole table —
//!     all of it, exactly.
//!   * `broadcast_choice` is an absolute too, but of a different kind: the
//!     decision is graded against the ARITHMETIC on cases that flip both
//!     ways (and on 240 seeded ones), never against a stored answer. The
//!     harness fails ITSELF if its case set does not contain both outcomes
//!     and a tie.
//!   * `bytes_shuffled` and `skew_bounded` are the two BANDS, and they pull
//!     in opposite directions. Salting is the only knob: never salt and the
//!     hot key blows the per-partition bound; salt everything and you have
//!     shipped the table `partitions` times. Passing both means a policy
//!     was found rather than a preference.
//!
//! Both bands are COUNTS — bytes of row-copies routed, rows landed on the
//! busiest partition — never clocks, which is why this suite means the same
//! thing in the terminal and in the browser. Both are charged
//! STRUCTURALLY, off the `Shuffled` the student's router returns, never from
//! a number the student's code reports. And every case that scores a band
//! verifies the join output first, so cost is only ever graded on a plan
//! that is still correct.
//!
//! `skew_bounded` carries one extra self-audit that is worth stating: for
//! every case it grades, it proves that a PLAIN hash router (its own
//! avalanche, not the student's) blows the bound, or — for the strided-key
//! cases — that a raw `key % partitions` router does. A skew case that a
//! naive router could pass would teach nothing, so the harness treats that
//! as a bug in itself.
//!
//! BTreeMap only, never HashMap: std's HashMap seeds itself from OS
//! randomness that does not exist on `wasm32-unknown-unknown`.

mod shuffle;

use kslab::{Check, Report};
use shuffle::{JoinRow, Key, Plan, Row, Shuffled, Stats, ROW_BYTES, SKEW_FACTOR};
use std::collections::BTreeMap;

/* --------------------------- determinism ---------------------------- */

/// xorshift64* — the same workloads on every machine, every run, in both
/// wasm and native. Seeded per check so one failure cannot move another
/// check's data.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        if n == 0 {
            0
        } else {
            (self.next() % n as u64) as usize
        }
    }
    fn payload(&mut self) -> i64 {
        match self.below(24) {
            0 => 0,
            1 => i64::MIN,
            2 => i64::MAX,
            3 => -1,
            _ => (self.next() % 1_000_000) as i64,
        }
    }
}

/* ------------------------- the harness's hash ------------------------ */
/* Its own avalanche, so "what would a plain hash router do" is answered   */
/* without asking the code under test.                                    */

fn hh(key: Key) -> u64 {
    let mut z = key.wrapping_add(0x9E37_79B9_7F4A_7C15);
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

/// The harness's own copy of the published bound. Cross-checked against the
/// GIVEN `shuffle::partition_bound` by `givens_intact`.
fn bound_of(total_rows: u64, partitions: usize) -> u64 {
    if partitions == 0 {
        return 0;
    }
    let p = partitions as u64;
    let mean = total_rows / p + u64::from(total_rows % p != 0);
    (SKEW_FACTOR * mean).max(1)
}

fn mean_of(total_rows: u64, partitions: usize) -> u64 {
    if partitions == 0 {
        return 0;
    }
    let p = partitions as u64;
    total_rows / p + u64::from(total_rows % p != 0)
}

/// The largest partition a router of the given flavour would produce, if it
/// co-located every key and salted nothing.
fn naive_max_load(left: &[Row], right: &[Row], partitions: usize, avalanche: bool) -> u64 {
    if partitions == 0 {
        return 0;
    }
    let mut loads = vec![0u64; partitions];
    for r in left.iter().chain(right.iter()) {
        let h = if avalanche { hh(r.key) } else { r.key };
        loads[(h % partitions as u64) as usize] += 1;
    }
    loads.into_iter().max().unwrap_or(0)
}

/* ----------------------- the reference join -------------------------- */
/* A global build-and-probe over both whole sides. No partitions, no salt,  */
/* no policy — every expectation in this file comes from here.              */

fn reference_join(left: &[Row], right: &[Row]) -> Vec<JoinRow> {
    let mut build: BTreeMap<Key, Vec<i64>> = BTreeMap::new();
    for r in right {
        build.entry(r.key).or_default().push(r.payload);
    }
    let mut out = Vec::new();
    for l in left {
        if let Some(rs) = build.get(&l.key) {
            for r in rs {
                out.push(JoinRow { key: l.key, left: l.payload, right: *r });
            }
        }
    }
    out.sort_unstable();
    out
}

/// Ground truth #1: the definition of an inner join, written as slowly as
/// possible. Affordable only on small cases.
fn nested_loop_join(left: &[Row], right: &[Row]) -> Vec<JoinRow> {
    let mut out = Vec::new();
    for l in left {
        for r in right {
            if l.key == r.key {
                out.push(JoinRow { key: l.key, left: l.payload, right: r.payload });
            }
        }
    }
    out.sort_unstable();
    out
}

/// Ground truth #2: the output cardinality in closed form, `Σ_k l(k)·r(k)`.
/// Cheap enough to run on every case.
fn expected_cardinality(left: &[Row], right: &[Row]) -> u64 {
    let mut lc: BTreeMap<Key, u64> = BTreeMap::new();
    for r in left {
        *lc.entry(r.key).or_insert(0) += 1;
    }
    let mut rc: BTreeMap<Key, u64> = BTreeMap::new();
    for r in right {
        *rc.entry(r.key).or_insert(0) += 1;
    }
    lc.iter().map(|(k, l)| l * rc.get(k).copied().unwrap_or(0)).sum()
}

/// The audited reference. Errors from here are HARNESS BUGs, not student
/// failures.
fn reference(left: &[Row], right: &[Row], ctx: &str) -> Result<Vec<JoinRow>, String> {
    let want = reference_join(left, right);
    let card = expected_cardinality(left, right);
    if want.len() as u64 != card {
        return Err(format!(
            "HARNESS BUG: the reference join produced {} rows for {ctx} but Σ_k left(k)·right(k) = {card} — please report this",
            want.len()
        ));
    }
    if left.len().saturating_mul(right.len()) <= 4096 {
        let slow = nested_loop_join(left, right);
        if slow != want {
            return Err(format!(
                "HARNESS BUG: the reference join disagrees with a nested loop for {ctx} ({} vs {} rows) — please report this",
                want.len(),
                slow.len()
            ));
        }
    }
    Ok(want)
}

/* --------------------------- comparisons ----------------------------- */

/// Multiset comparison of join output, with a difference that says which
/// pair went missing or got produced twice.
fn join_diff(got_raw: &[JoinRow], want: &[JoinRow], ctx: &str) -> Option<String> {
    let mut got: Vec<JoinRow> = got_raw.to_vec();
    got.sort_unstable();
    if got == want {
        return None;
    }
    let mut gc: BTreeMap<JoinRow, i64> = BTreeMap::new();
    for r in &got {
        *gc.entry(*r).or_insert(0) += 1;
    }
    for r in want {
        *gc.entry(*r).or_insert(0) -= 1;
    }
    let missing: Vec<(JoinRow, i64)> = gc.iter().filter(|(_, n)| **n < 0).map(|(r, n)| (*r, -*n)).collect();
    let extra: Vec<(JoinRow, i64)> = gc.iter().filter(|(_, n)| **n > 0).map(|(r, n)| (*r, *n)).collect();
    let show_rows = |v: &[(JoinRow, i64)]| -> String {
        v.iter()
            .take(3)
            .map(|(r, n)| format!("(key {}, left {}, right {}) ×{}", r.key, r.left, r.right, n))
            .collect::<Vec<_>>()
            .join(", ")
    };
    let mut msg = format!("{ctx}: join output is not the reference multiset — {} rows vs {}", got.len(), want.len());
    if !missing.is_empty() {
        msg.push_str(&format!(
            ". MISSING {} distinct pair(s), e.g. {} — a pair is lost when the two rows never met on the same partition",
            missing.len(),
            show_rows(&missing)
        ));
    }
    if !extra.is_empty() {
        msg.push_str(&format!(
            ". DUPLICATED/INVENTED {} distinct pair(s), e.g. {} — a pair is produced twice when both sides were replicated to the same salt buckets",
            extra.len(),
            show_rows(&extra)
        ));
    }
    Some(msg)
}

/// Structural validity of a `Shuffled`: the right number of buckets, and
/// nothing on the wire that was not in the input.
fn structure_errors(s: &Shuffled, left: &[Row], right: &[Row], partitions: usize, ctx: &str) -> Option<String> {
    if s.left.len() != partitions || s.right.len() != partitions {
        return Some(format!(
            "{ctx}: shuffle returned {} left buckets and {} right buckets for {partitions} partitions — start from Shuffled::new(partitions)",
            s.left.len(),
            s.right.len()
        ));
    }
    for (side, input, routed) in [("left", left, &s.left), ("right", right, &s.right)] {
        let mut allowed: BTreeMap<Row, u64> = BTreeMap::new();
        for r in input {
            *allowed.entry(*r).or_insert(0) += 1;
        }
        for (p, bucket) in routed.iter().enumerate() {
            for r in bucket {
                if !allowed.contains_key(r) {
                    return Some(format!(
                        "{ctx}: partition {p} holds a {side} row (key {}, payload {}) that is not in the {side} input — you may copy rows, not invent or edit them",
                        r.key, r.payload
                    ));
                }
            }
        }
    }
    None
}

/// The lab's stated scope, machine-checked rather than promised in prose.
///
/// A key that does not fit in one partition is handled by splitting one side
/// and replicating the other — so the replicated side is present in every
/// one of that key's buckets, and no amount of splitting can get a bucket
/// below `min(left(k), right(k))`. When BOTH sides of one key are large, the
/// only bounded plan is a GRID split (s×t buckets, s·t copies), which this
/// lab does not ask for.
///
/// So: the bound is only ever enforced on plans where every key's smaller
/// side fits inside one average partition. Correctness is enforced
/// everywhere, without exception.
fn grid_key(left: &[Row], right: &[Row], partitions: usize) -> Option<String> {
    let total = (left.len() + right.len()) as u64;
    let mean = mean_of(total, partitions);
    let mut lc: BTreeMap<Key, u64> = BTreeMap::new();
    for r in left {
        *lc.entry(r.key).or_insert(0) += 1;
    }
    let mut rc: BTreeMap<Key, u64> = BTreeMap::new();
    for r in right {
        *rc.entry(r.key).or_insert(0) += 1;
    }
    for (k, l) in &lc {
        let r = rc.get(k).copied().unwrap_or(0);
        if l.min(&r) > &mean {
            return Some(format!(
                "key {k} is heavy on BOTH sides ({l} left, {r} right, average partition {mean}) — only a grid split could bound it"
            ));
        }
    }
    None
}

/// The smallest contribution the heaviest key can possibly make to SOME
/// partition, under any one-sided split: the replicated side is present in
/// every bucket of that key, and the split side cannot be divided into more
/// than `partitions` pieces. No router can be blamed for this much.
fn largest_atom(left: &[Row], right: &[Row], partitions: usize) -> u64 {
    if partitions == 0 {
        return 0;
    }
    let p = partitions as u64;
    let mut lc: BTreeMap<Key, u64> = BTreeMap::new();
    for r in left {
        *lc.entry(r.key).or_insert(0) += 1;
    }
    let mut rc: BTreeMap<Key, u64> = BTreeMap::new();
    for r in right {
        *rc.entry(r.key).or_insert(0) += 1;
    }
    let mut atom = 0u64;
    for k in lc.keys().chain(rc.keys()) {
        let l = lc.get(k).copied().unwrap_or(0);
        let r = rc.get(k).copied().unwrap_or(0);
        let (heavy, light) = if l >= r { (l, r) } else { (r, l) };
        let split = light + (heavy / p + u64::from(heavy % p != 0));
        atom = atom.max(split.min(l + r));
    }
    atom
}

fn distinct_keys(left: &[Row], right: &[Row]) -> usize {
    let mut keys: BTreeMap<Key, ()> = BTreeMap::new();
    for r in left.iter().chain(right.iter()) {
        keys.insert(r.key, ());
    }
    keys.len()
}

/// Everything one plan is worth knowing about, once it has been proved
/// correct.
struct Graded {
    moved: u64,
    reference_bytes: u64,
    max_load: u64,
    mean_load: u64,
    bound: u64,
    out_rows: usize,
}

/// Run one plan through the student's router and verify it before measuring
/// it: structure, then the join output against the audited reference, then
/// (optionally) purity. Only then are the counts meaningful.
fn grade(left: &[Row], right: &[Row], partitions: usize, ctx: &str, purity: bool) -> Result<Graded, String> {
    let want = reference(left, right, ctx)?;
    let got = shuffle::shuffle(left, right, partitions);
    if let Some(msg) = structure_errors(&got, left, right, partitions, ctx) {
        return Err(msg);
    }
    if purity {
        let again = shuffle::shuffle(left, right, partitions);
        if again != got {
            return Err(format!(
                "{ctx}: two shuffles of the same inputs disagree — routing must be pure, or nobody can predict the bill"
            ));
        }
    }
    let out = shuffle::local_join(&got);
    if let Some(msg) = join_diff(&out, &want, ctx) {
        return Err(msg);
    }
    let total = (left.len() + right.len()) as u64;
    let loads = shuffle::partition_loads(&got);
    Ok(Graded {
        moved: shuffle::bytes_moved(&got),
        reference_bytes: total * ROW_BYTES,
        max_load: loads.iter().copied().max().unwrap_or(0),
        mean_load: mean_of(total, partitions),
        bound: bound_of(total, partitions),
        out_rows: out.len(),
    })
}

/* ---------------------------- the GIVENs ----------------------------- */

/// The cost model is published, which means it is also part of the
/// contract: if a GIVEN has been edited, the numbers the bands are scored
/// against are no longer the ones the lab describes.
fn givens_intact() -> Option<String> {
    if ROW_BYTES != 16 {
        return Some(format!("ROW_BYTES is {ROW_BYTES}, not 16 — restore the GIVEN cost model in src/shuffle.rs"));
    }
    if SKEW_FACTOR != 3 {
        return Some(format!("SKEW_FACTOR is {SKEW_FACTOR}, not 3 — restore the GIVEN cost model in src/shuffle.rs"));
    }
    for (total, parts) in [(0u64, 1usize), (1, 1), (100, 8), (5000, 16), (4097, 64), (7, 4)] {
        let mine = bound_of(total, parts);
        let theirs = shuffle::partition_bound(total, parts);
        if mine != theirs {
            return Some(format!(
                "partition_bound({total}, {parts}) returns {theirs}, but the published model says {mine} — restore the GIVEN in src/shuffle.rs"
            ));
        }
    }
    for (l, r) in [(0u64, 0u64), (10, 1), (1_000_000, 3)] {
        let stats = Stats { left_rows: l, right_rows: r, workers: 4 };
        let want = (l + r) * ROW_BYTES;
        if shuffle::partition_bytes(&stats) != want {
            return Some(format!(
                "partition_bytes for ({l}, {r}) returns {}, but a partitioned plan moves both sides once = {want} — restore the GIVEN in src/shuffle.rs",
                shuffle::partition_bytes(&stats)
            ));
        }
    }
    for key in [0u64, 1, 2, 63, 64, 1_000_003, u64::MAX] {
        if shuffle::hash_key(key) != hh(key) {
            return Some(format!(
                "hash_key({key}) returns {} but the GIVEN avalanche is {} — restore the GIVEN in src/shuffle.rs (and note that a router is graded on the loads it produces, not on the hash it uses)",
                shuffle::hash_key(key),
                hh(key)
            ));
        }
    }
    let fresh = Shuffled::new(5);
    if fresh.partitions() != 5 || fresh.left.len() != 5 || fresh.right.len() != 5 || shuffle::bytes_moved(&fresh) != 0 {
        return Some("Shuffled::new(5) no longer yields 5 empty buckets a side — restore the GIVEN in src/shuffle.rs".to_string());
    }
    None
}

/* ---------------------------- generators ----------------------------- */

fn rows_from(pairs: &[(Key, i64)]) -> Vec<Row> {
    pairs.iter().map(|(k, p)| Row { key: *k, payload: *p }).collect()
}

/// `n` rows with keys drawn uniformly from `[0, span)`.
fn uniform(rng: &mut Rng, n: usize, span: u64) -> Vec<Row> {
    (0..n)
        .map(|_| Row { key: if span == 0 { 0 } else { rng.next() % span }, payload: rng.payload() })
        .collect()
}

/// `n` rows, `hot` of them carrying `hot_key`, the rest uniform over
/// `[0, span)` — and shuffled, so the heavy hitter is not a contiguous run
/// that a lucky implementation could stumble into balancing.
fn with_hot(rng: &mut Rng, n: usize, hot_key: Key, hot: usize, span: u64) -> Vec<Row> {
    let hot = hot.min(n);
    let mut out: Vec<Row> = (0..hot).map(|_| Row { key: hot_key, payload: rng.payload() }).collect();
    for _ in hot..n {
        let mut k = if span == 0 { 0 } else { rng.next() % span };
        if k == hot_key {
            k = k.wrapping_add(1) % span.max(1);
        }
        out.push(Row { key: k, payload: rng.payload() });
    }
    for i in (1..out.len()).rev() {
        out.swap(i, rng.below(i + 1));
    }
    out
}

/// `n` rows whose keys are all multiples of `stride` — ids allocated in
/// blocks, timestamps on the minute, anything aligned. Uniformly spread
/// under a real hash; catastrophically aligned under `key % partitions`.
fn strided(rng: &mut Rng, n: usize, distinct: u64, stride: u64) -> Vec<Row> {
    (0..n)
        .map(|_| Row { key: (rng.next() % distinct.max(1)) * stride, payload: rng.payload() })
        .collect()
}

/* ---------------------------- formatting ----------------------------- */

fn tenths(num: u64, den: u64) -> u64 {
    if den == 0 {
        return 0;
    }
    (num * 10 + den / 2) / den
}

fn hundredths(num: u64, den: u64) -> u64 {
    if den == 0 {
        return 0;
    }
    (num * 100 + den / 2) / den
}

fn show2(h: u64) -> String {
    format!("{}.{:02}", h / 100, h % 100)
}

fn show1(t: u64) -> String {
    format!("{}.{}", t / 10, t % 10)
}

/* ========================= 1 · join_correct ========================== */

/// Bytes moved and partitions balanced are both irrelevant if the answer is
/// wrong, so this comes first: the output multiset, exactly, on the shapes
/// that break partitioned joins.
pub fn check_join_correct() -> Check {
    const ID: &str = "join_correct";
    const LABEL: &str = "join output matches a reference hash join exactly";
    if let Some(msg) = givens_intact() {
        return Check::fail(ID, LABEL, msg);
    }

    // The statistics come first: everything downstream is built on them.
    {
        let mut rng = Rng(0xC0DE_C0DE_0001);
        let mut inputs: Vec<Vec<Row>> = vec![
            Vec::new(),
            rows_from(&[(0, 0)]),
            rows_from(&[(9, 1), (9, 2), (9, 3)]),
            rows_from(&[(1, 1), (2, 2), (3, 3)]),
            rows_from(&[(u64::MAX, 1), (0, 2), (u64::MAX, 3)]),
        ];
        for _ in 0..6 {
            let n = 1 + rng.below(200);
            let span = 1 + rng.next() % 12;
            inputs.push(uniform(&mut rng, n, span));
        }
        for rows in &inputs {
            let mut want: BTreeMap<Key, u64> = BTreeMap::new();
            for r in rows {
                *want.entry(r.key).or_insert(0) += 1;
            }
            let got = shuffle::key_counts(rows);
            if got != want {
                let bad = want
                    .iter()
                    .find(|(k, n)| got.get(k) != Some(n))
                    .map(|(k, n)| format!("key {k} carries {n} rows but key_counts says {:?}", got.get(k)))
                    .unwrap_or_else(|| {
                        got.keys()
                            .find(|k| !want.contains_key(k))
                            .map(|k| format!("key_counts reports key {k}, which is not in the input"))
                            .unwrap_or_else(|| "the maps differ".to_string())
                    });
                return Check::fail(
                    ID,
                    LABEL,
                    format!(
                        "key_counts is wrong on a {}-row input: {} distinct keys reported where there are {} — {bad}. Nothing downstream can find a heavy hitter without this.",
                        rows.len(),
                        got.len(),
                        want.len()
                    ),
                );
            }
        }
    }

    struct Case {
        name: &'static str,
        left: Vec<Row>,
        right: Vec<Row>,
        partitions: usize,
    }
    let mut cases: Vec<Case> = Vec::new();
    let mut push = |name: &'static str, left: Vec<Row>, right: Vec<Row>, partitions: usize| {
        cases.push(Case { name, left, right, partitions });
    };

    push("both sides empty", Vec::new(), Vec::new(), 4);
    push("empty left, populated right", Vec::new(), rows_from(&[(1, 10), (2, 20), (2, 21)]), 4);
    push("populated left, empty right", rows_from(&[(1, 10), (1, 11), (5, 50)]), Vec::new(), 4);
    push("one row each side, matching", rows_from(&[(7, 1)]), rows_from(&[(7, 2)]), 4);
    push("one row each side, not matching", rows_from(&[(7, 1)]), rows_from(&[(8, 2)]), 4);
    push(
        "duplicate keys on BOTH sides (every pair, once each)",
        rows_from(&[(1, 100), (1, 101), (1, 102), (2, 200), (2, 201)]),
        rows_from(&[(1, 900), (1, 901), (1, 902), (1, 903), (2, 800), (3, 700), (3, 701)]),
        8,
    );
    push(
        "keys present on only one side",
        rows_from(&[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]),
        rows_from(&[(4, 40), (5, 50), (6, 60), (7, 70), (8, 80), (9, 90)]),
        8,
    );
    push(
        "the same payload twice on one key (multiset, not a set)",
        rows_from(&[(3, 7), (3, 7)]),
        rows_from(&[(3, 9), (3, 9), (3, 9)]),
        4,
    );
    push(
        "every row shares one key — 60 × 40 pairs through a salted router",
        (0..60).map(|i| Row { key: 42, payload: i }).collect(),
        (0..40).map(|i| Row { key: 42, payload: 1000 + i }).collect(),
        8,
    );
    push(
        "payload extremes",
        rows_from(&[(1, i64::MIN), (1, i64::MAX), (2, 0), (2, -1)]),
        rows_from(&[(1, i64::MAX), (1, 0), (2, i64::MIN), (2, -1)]),
        4,
    );
    push(
        "a single partition",
        rows_from(&[(1, 1), (2, 2), (2, 3), (9, 9)]),
        rows_from(&[(2, 20), (2, 21), (9, 90)]),
        1,
    );
    push(
        "more partitions than rows",
        rows_from(&[(11, 1), (12, 2), (13, 3)]),
        rows_from(&[(12, 20), (13, 30), (14, 40)]),
        32,
    );
    push(
        "strided keys (multiples of 64) over 8 partitions",
        (0..40).map(|i| Row { key: (i % 10) * 64, payload: i as i64 }).collect(),
        (0..30).map(|i| Row { key: (i % 12) * 64, payload: 100 + i as i64 }).collect(),
        8,
    );
    push(
        "key 0 on both sides",
        rows_from(&[(0, 1), (0, 2), (5, 5)]),
        rows_from(&[(0, 10), (5, 50), (5, 51)]),
        4,
    );
    push(
        "u64::MAX as a key",
        rows_from(&[(u64::MAX, 1), (u64::MAX - 1, 2)]),
        rows_from(&[(u64::MAX, 10), (u64::MAX, 11)]),
        4,
    );
    push(
        "one hot key and a long tail",
        {
            let mut rng = Rng(0x5EED_0001);
            with_hot(&mut rng, 300, 77, 160, 500)
        },
        {
            let mut rng = Rng(0x5EED_0002);
            with_hot(&mut rng, 200, 77, 6, 500)
        },
        16,
    );

    // Seeded rounds over tiny key spaces, where duplicates are the rule and
    // the nested-loop audit is affordable on every one.
    let mut rng = Rng(0x1234_5678_9ABC_DEF1);
    let mut seeded = 0usize;
    let mut seeded_rows = 0usize;
    let mut seeded_names: Vec<String> = Vec::new();
    for round in 0..28usize {
        let span = [1u64, 2, 3, 5, 8, 13][round % 6];
        let ln = rng.below(40);
        let rn = rng.below(40);
        let parts = [1usize, 2, 3, 4, 7, 8, 16][round % 7];
        let left = uniform(&mut rng, ln, span);
        let right = uniform(&mut rng, rn, span);
        let ctx = format!("seeded round {round} ({ln} × {rn} rows over {span} distinct keys, {parts} partitions)");
        match grade(&left, &right, parts, &ctx, true) {
            Err(msg) => return Check::fail(ID, LABEL, msg),
            Ok(g) => {
                seeded += 1;
                seeded_rows += g.out_rows;
            }
        }
        let want = match reference(&left, &right, &ctx) {
            Ok(w) => w,
            Err(msg) => return Check::fail(ID, LABEL, msg),
        };
        if let Some(msg) = join_diff(&shuffle::execute(&left, &right, parts), &want, &format!("{ctx}, via execute")) {
            return Check::fail(ID, LABEL, msg);
        }
        seeded_names.push(format!("{span}k"));
    }

    let mut pairs = 0usize;
    for c in &cases {
        let ctx = format!("case \"{}\" ({} × {} rows, {} partitions)", c.name, c.left.len(), c.right.len(), c.partitions);
        let g = match grade(&c.left, &c.right, c.partitions, &ctx, true) {
            Ok(g) => g,
            Err(msg) => return Check::fail(ID, LABEL, msg),
        };
        pairs += g.out_rows;
        // The plan the student chose must not change the answer either.
        let want = match reference(&c.left, &c.right, &ctx) {
            Ok(w) => w,
            Err(msg) => return Check::fail(ID, LABEL, msg),
        };
        if let Some(msg) = join_diff(&shuffle::execute(&c.left, &c.right, c.partitions), &want, &format!("{ctx}, via execute")) {
            return Check::fail(ID, LABEL, msg);
        }
    }

    Check::pass(
        ID,
        LABEL,
        format!(
            "{} hand-built cases and {seeded} seeded rounds are multiset-exact against the reference join — {} + {seeded_rows} output pairs compared row for row, through both the partitioned path and the plan execute() chose. Duplicates on both sides, keys on one side only, empty inputs, one key holding the whole table, strided keys, u64::MAX, and i64::MIN/MAX payloads all agree. Every reference was audited against Σ_k left(k)·right(k) and, where affordable, a nested loop.",
            cases.len(),
            pairs
        ),
    )
}

/* ======================== 2 · bytes_shuffled ========================= */

/// Bytes moved, as a count of row-copies on the wire, against the reference
/// plan's "both sides once". The band is what stops salting from being free.
pub fn check_bytes_shuffled() -> Check {
    const ID: &str = "bytes_shuffled";
    const LABEL: &str = "bytes moved within band of the reference plan";
    /// Aggregate ceiling, in percent of the reference plan.
    const MAX_TOTAL_PCT: u64 = 110;
    /// Per-plan ceiling, in percent — so one ruinous plan cannot hide inside
    /// an average.
    const MAX_PLAN_PCT: u64 = 112;

    if let Some(msg) = givens_intact() {
        return Check::fail(ID, LABEL, msg);
    }

    // The sizing rule first: "the fewest buckets that clears the capacity"
    // is the half of the policy that this band grades.
    for (count, capacity) in [
        (0u64, 10u64),
        (1, 10),
        (10, 10),
        (11, 10),
        (20, 10),
        (21, 10),
        (1, 1),
        (7, 1),
        (5, 0),
        (1800, 313),
        (3600, 300),
        (1_000_000, 999),
    ] {
        let cap = capacity.max(1);
        let want = if count == 0 { 1 } else { ((count + cap - 1) / cap).max(1) } as usize;
        let got = shuffle::salts_for(count, capacity);
        if got != want {
            return Check::fail(
                ID,
                LABEL,
                format!(
                    "salts_for({count}, {capacity}) returned {got}, but the fewest buckets that fit {count} rows into buckets of {cap} is ceil({count}/{cap}) = {want}. \
                     Too few and the bucket still blows the bound; too many and every extra bucket replicates the other side of that key once more."
                ),
            );
        }
    }

    /// One plan whose bytes are counted.
    struct Plan_ {
        name: &'static str,
        left: Vec<Row>,
        right: Vec<Row>,
        partitions: usize,
    }
    let mut rng = Rng(0xB17E_5000_0001);
    let mut plans: Vec<Plan_> = Vec::new();
    plans.push(Plan_ {
        name: "uniform 2000 × 2000 over a wide key space",
        left: uniform(&mut rng, 2000, 100_000),
        right: uniform(&mut rng, 2000, 100_000),
        partitions: 16,
    });
    plans.push(Plan_ {
        name: "4000 × 250, 8 partitions",
        left: uniform(&mut rng, 4000, 50_000),
        right: uniform(&mut rng, 250, 50_000),
        partitions: 8,
    });
    plans.push(Plan_ {
        name: "duplicate-heavy: 1500 × 1500 over 200 keys",
        left: uniform(&mut rng, 1500, 200),
        right: uniform(&mut rng, 1500, 200),
        partitions: 16,
    });
    plans.push(Plan_ {
        name: "mildly skewed: hot key at 15 % of the rows",
        left: with_hot(&mut rng, 2000, 909, 450, 5000),
        right: with_hot(&mut rng, 1000, 909, 20, 5000),
        partitions: 16,
    });
    plans.push(Plan_ {
        name: "skewed: hot key at 40 % of the left side",
        left: with_hot(&mut rng, 3000, 13, 1200, 4000),
        right: with_hot(&mut rng, 800, 13, 12, 4000),
        partitions: 16,
    });
    plans.push(Plan_ {
        name: "two hot keys, one on each side",
        left: with_hot(&mut rng, 2400, 5, 900, 3000),
        right: with_hot(&mut rng, 2400, 6, 900, 3000),
        partitions: 16,
    });
    plans.push(Plan_ {
        // The over-salting plan: the hot key's SMALLER side is 60 rows, so
        // every bucket beyond the fewest that clears the bound costs 60 more
        // copies. Splitting this key 16 ways instead of 4 is a fifth of the
        // whole table, moved for nothing.
        name: "a hot key whose other side is not tiny",
        left: with_hot(&mut rng, 3000, 21, 600, 4000),
        right: with_hot(&mut rng, 800, 21, 60, 4000),
        partitions: 16,
    });
    plans.push(Plan_ {
        name: "strided keys, multiples of 64",
        left: strided(&mut rng, 2000, 700, 64),
        right: strided(&mut rng, 2000, 700, 64),
        partitions: 16,
    });
    plans.push(Plan_ {
        name: "one partition — nothing to balance",
        left: uniform(&mut rng, 800, 400),
        right: uniform(&mut rng, 800, 400),
        partitions: 1,
    });
    plans.push(Plan_ {
        name: "64 partitions, 1500 rows a side",
        left: uniform(&mut rng, 1500, 20_000),
        right: uniform(&mut rng, 1500, 20_000),
        partitions: 64,
    });

    let mut total_moved = 0u64;
    let mut total_ref = 0u64;
    let mut worst = (0u64, "");
    let mut lines: Vec<String> = Vec::new();
    for p in &plans {
        let ctx = format!("plan \"{}\" ({} × {} rows, {} partitions)", p.name, p.left.len(), p.right.len(), p.partitions);
        if let Some(why) = grid_key(&p.left, &p.right, p.partitions) {
            return Check::fail(
                ID,
                LABEL,
                format!("HARNESS BUG: {ctx} is outside the lab's stated scope — {why}. Please report this."),
            );
        }
        let g = match grade(&p.left, &p.right, p.partitions, &ctx, false) {
            Ok(g) => g,
            Err(msg) => return Check::fail(ID, LABEL, msg),
        };
        let pct = hundredths(g.moved, g.reference_bytes);
        if pct > MAX_PLAN_PCT {
            return Check::fail(
                ID,
                LABEL,
                format!(
                    "{ctx}: moved {} bytes where the reference plan moves {} — {}× the band's {}× per-plan ceiling. \
                     Every extra copy is a row crossing the network twice: salt only the keys that blow the per-partition bound, \
                     by the fewest buckets that clears it, and replicate the SMALLER side of that key.",
                    g.moved,
                    g.reference_bytes,
                    show2(pct),
                    show2(MAX_PLAN_PCT)
                ),
            );
        }
        total_moved += g.moved;
        total_ref += g.reference_bytes;
        if pct > worst.0 {
            worst = (pct, p.name);
        }
        lines.push(format!("{} {}×", p.name, show2(pct)));
    }

    let pct = hundredths(total_moved, total_ref);
    if pct > MAX_TOTAL_PCT {
        return Check::fail(
            ID,
            LABEL,
            format!(
                "moved {total_moved} bytes over {} plans where the reference plan moves {total_ref} — {}×, over the {}× band. \
                 The worst plan was \"{}\" at {}×. Salting is the knob: each extra bucket replicates the other side of that key once more.",
                plans.len(),
                show2(pct),
                show2(MAX_TOTAL_PCT),
                worst.1,
                show2(worst.0)
            ),
        );
    }

    Check::pass(
        ID,
        LABEL,
        format!(
            "{total_moved} bytes moved over {} plans against a reference plan of {total_ref} — {}× (band {}×), worst plan \"{}\" at {}× (per-plan ceiling {}×). \
             Every plan's join output was verified against the reference before its bytes were counted. Per plan: {}.",
            plans.len(),
            show2(pct),
            show2(MAX_TOTAL_PCT),
            worst.1,
            show2(worst.0),
            show2(MAX_PLAN_PCT),
            lines.join("; ")
        ),
    )
}

/* ======================= 3 · broadcast_choice ======================== */

/// The decision, graded against the arithmetic. Never against a stored
/// answer: the harness computes `small_side × workers` versus `both sides
/// once` for every case and fails itself if its cases do not flip both ways.
pub fn check_broadcast_choice() -> Check {
    const ID: &str = "broadcast_choice";
    const LABEL: &str = "broadcast chosen iff it moves fewer bytes than partitioning, given the stats";
    if let Some(msg) = givens_intact() {
        return Check::fail(ID, LABEL, msg);
    }

    // The arithmetic, written out once, in the harness's own hand.
    let bcast = |s: &Stats| -> u64 { s.left_rows.min(s.right_rows) * ROW_BYTES * s.workers };
    let part = |s: &Stats| -> u64 { (s.left_rows + s.right_rows) * ROW_BYTES };

    let mut cases: Vec<(&'static str, Stats)> = Vec::new();
    let mut push = |name: &'static str, l: u64, r: u64, w: u64| {
        cases.push((name, Stats { left_rows: l, right_rows: r, workers: w }));
    };
    push("1 000-row dimension against a 1 M-row fact, 4 workers", 1_000_000, 1_000, 4);
    push("the same join with the small side on the LEFT", 1_000, 1_000_000, 4);
    push("the same dimension table over 4 096 workers", 1_000_000, 1_000, 4_096);
    push("100 M-row 'dimension' table, 4 workers", 1_000_000_000, 100_000_000, 4);
    push("exact tie: equal sides, 2 workers", 500, 500, 2);
    push("exact tie: 300 × 900 over 4 workers", 300, 900, 4);
    push("a single worker — nothing to fan out to", 500, 500, 1);
    push("a single worker, lopsided sides", 10_000_000, 3, 1);
    push("empty left side", 0, 5_000, 8);
    push("empty right side", 5_000, 0, 64);
    push("both sides empty", 0, 0, 8);
    push("one row against one row, 2 workers", 1, 1, 2);
    push("one row against one row, 3 workers", 1, 1, 3);
    push("small side 1/8 of the big one, 8 workers", 80_000, 10_000, 8);
    push("small side 1/8 of the big one, 9 workers", 80_000, 10_000, 9);
    push("small side 1/8 of the big one, 7 workers", 80_000, 10_000, 7);
    push("2 workers, sides within a factor of two", 3_000, 2_000, 2);
    push("2 workers, sides equal to the byte", 2_000, 2_000, 2);
    push("1 024 workers, tiny lookup table", 500_000_000, 40, 1_024);
    push("1 024 workers, not-so-tiny lookup table", 500_000_000, 4_000_000, 1_024);

    let mut broadcasts = 0usize;
    let mut partitions = 0usize;
    let mut ties = 0usize;
    let mut checked = 0usize;
    let mut examples: Vec<String> = Vec::new();

    let grade_one = |name: &str, s: &Stats| -> Result<Plan, String> {
        let b = bcast(s);
        let p = part(s);
        let got_bytes = shuffle::broadcast_bytes(s);
        if got_bytes != b {
            return Err(format!(
                "{name}: broadcast_bytes({} left, {} right, {} workers) returned {got_bytes}, but broadcasting sends the SMALL side ({} rows) to every worker: {} × {ROW_BYTES} × {} = {b}",
                s.left_rows,
                s.right_rows,
                s.workers,
                s.left_rows.min(s.right_rows),
                s.left_rows.min(s.right_rows),
                s.workers
            ));
        }
        if shuffle::partition_bytes(s) != p {
            return Err(format!("{name}: partition_bytes disagrees with the published model ({} vs {p})", shuffle::partition_bytes(s)));
        }
        let want = if b < p { Plan::Broadcast } else { Plan::Partitioned };
        let got = shuffle::choose_plan(s);
        if got != shuffle::choose_plan(s) {
            return Err(format!("{name}: choose_plan is not a function of its statistics — two calls, two answers"));
        }
        if got != want {
            let why = if b < p {
                format!("broadcast moves {b} bytes and partitioning moves {p} — broadcast is cheaper, so broadcast")
            } else if b == p {
                format!("both plans move exactly {b} bytes — a tie is not 'fewer', and partitioning is the plan whose cost does not grow when workers are added")
            } else {
                format!("broadcast moves {b} bytes and partitioning moves {p} — partitioning is cheaper, so partition")
            };
            return Err(format!(
                "{name}: chose {got:?} for {} left rows, {} right rows, {} workers, but {why}",
                s.left_rows, s.right_rows, s.workers
            ));
        }
        Ok(want)
    };

    for (name, s) in &cases {
        match grade_one(name, s) {
            Err(msg) => return Check::fail(ID, LABEL, msg),
            Ok(want) => {
                checked += 1;
                if bcast(s) == part(s) {
                    ties += 1;
                }
                match want {
                    Plan::Broadcast => broadcasts += 1,
                    Plan::Partitioned => partitions += 1,
                }
                if examples.len() < 3 {
                    examples.push(format!("{name} → {want:?}"));
                }
            }
        }
    }

    // Seeded sweep: the arithmetic decides, every time, over sizes and
    // worker counts nobody could have memorised.
    let mut rng = Rng(0xC0FF_EE00_1234);
    for round in 0..240usize {
        let scale = [1u64, 10, 1_000, 100_000, 10_000_000][round % 5];
        let l = (rng.next() % (scale * 10 + 1)) as u64;
        let r = (rng.next() % (scale * 10 + 1)) as u64;
        let w = 1 + (rng.next() % 2_048);
        let s = Stats { left_rows: l, right_rows: r, workers: w };
        match grade_one(&format!("seeded case {round}"), &s) {
            Err(msg) => return Check::fail(ID, LABEL, msg),
            Ok(want) => {
                checked += 1;
                if bcast(&s) == part(&s) {
                    ties += 1;
                }
                match want {
                    Plan::Broadcast => broadcasts += 1,
                    Plan::Partitioned => partitions += 1,
                }
            }
        }
    }

    if broadcasts == 0 || partitions == 0 {
        return Check::fail(
            ID,
            LABEL,
            format!(
                "HARNESS BUG: the case set does not flip both ways ({broadcasts} broadcast, {partitions} partitioned) — a decision graded on one-sided cases would pass a constant answer. Please report this."
            ),
        );
    }
    if ties == 0 {
        return Check::fail(
            ID,
            LABEL,
            "HARNESS BUG: the case set contains no tie, so 'strictly fewer' is not actually graded — please report this".to_string(),
        );
    }

    Check::pass(
        ID,
        LABEL,
        format!(
            "{checked} plans graded against the arithmetic — {broadcasts} where broadcast moves fewer bytes, {partitions} where partitioning does, including {ties} exact ties (which must partition). \
             broadcast_bytes matched min(left, right) × {ROW_BYTES} × workers on every one, over worker counts from 1 to 4 096 and sides from empty to 10⁹ rows, with the small side on both the left and the right. \
             E.g. {}.",
            examples.join("; ")
        ),
    )
}

/* ========================= 4 · skew_bounded ========================== */

/// The largest partition is the runtime. This bounds it — and proves, for
/// every case, that a naive router blows the bound, so passing requires
/// heavy-hitter detection rather than luck.
pub fn check_skew_bounded() -> Check {
    const ID: &str = "skew_bounded";
    const LABEL: &str = "no partition exceeds the per-partition bound on a deliberately skewed key";
    if let Some(msg) = givens_intact() {
        return Check::fail(ID, LABEL, msg);
    }

    // The router first: in range, avalanching, and consistent with the
    // GIVEN salt mapping that both sides of a key depend on.
    {
        for partitions in [1usize, 2, 3, 7, 8, 16, 64] {
            for key in [0u64, 1, 63, 64, 128, 4096, 1_000_003, u64::MAX] {
                let p = shuffle::hash_partition(key, partitions);
                if p >= partitions {
                    return Check::fail(
                        ID,
                        LABEL,
                        format!("hash_partition({key}, {partitions}) returned {p} — a partition index must be < partitions"),
                    );
                }
                for salt in 0..partitions.min(4) {
                    let want = (p + salt) % partitions;
                    let got = shuffle::salted_partition(key, salt, partitions);
                    if got != want {
                        return Check::fail(
                            ID,
                            LABEL,
                            format!("salted_partition({key}, {salt}, {partitions}) returned {got}, not {want} — restore the GIVEN in src/shuffle.rs; both sides of a salted key depend on it agreeing"),
                        );
                    }
                }
            }
        }
        // 4096 strided keys over 16 partitions. A raw `key % partitions`
        // router puts every one of them on 1 partition; an avalanche spreads
        // them within a few percent of even.
        let partitions = 16usize;
        let mut loads = vec![0u64; partitions];
        for i in 0..4096u64 {
            loads[shuffle::hash_partition(i * 64, partitions)] += 1;
        }
        let mean = 4096 / partitions as u64;
        let max = loads.iter().copied().max().unwrap_or(0);
        if max > mean * 2 {
            return Check::fail(
                ID,
                LABEL,
                format!(
                    "hash_partition sent {max} of 4096 strided keys (all multiples of 64) to one of {partitions} partitions, where an even spread is {mean}. \
                     `key % partitions` on aligned keys is not a data skew problem, it is a router that never mixed the bits — avalanche the key with hash_key first."
                ),
            );
        }
    }

    /// What a case exists to break.
    struct Case {
        name: &'static str,
        left: Vec<Row>,
        right: Vec<Row>,
        partitions: usize,
        /// A plain (avalanched) hash router must blow the bound here.
        breaks_hashing: bool,
        /// A raw `key % partitions` router must blow the bound here.
        breaks_modulo: bool,
    }

    let mut rng = Rng(0x5CEE_0000_0001);
    let mut cases: Vec<Case> = Vec::new();

    cases.push(Case {
        name: "one key holds 40 % of the rows",
        left: with_hot(&mut rng, 4000, 31337, 1800, 6000),
        right: with_hot(&mut rng, 1000, 31337, 10, 6000),
        partitions: 16,
        breaks_hashing: true,
        breaks_modulo: false,
    });
    cases.push(Case {
        name: "the hot key is on the RIGHT side",
        left: with_hot(&mut rng, 1200, 9, 8, 5000),
        right: with_hot(&mut rng, 4000, 9, 2000, 5000),
        partitions: 16,
        breaks_hashing: true,
        breaks_modulo: false,
    });
    cases.push(Case {
        name: "two hot keys, 25 % each",
        left: {
            let mut v = with_hot(&mut rng, 2000, 101, 1000, 4000);
            v.extend(with_hot(&mut rng, 2000, 202, 1000, 4000));
            v
        },
        right: {
            let mut v = with_hot(&mut rng, 400, 101, 10, 4000);
            v.extend(with_hot(&mut rng, 400, 202, 14, 4000));
            v
        },
        partitions: 16,
        breaks_hashing: true,
        breaks_modulo: false,
    });
    cases.push(Case {
        name: "the hot key alone is 6× the bound",
        left: with_hot(&mut rng, 5000, 4242, 3600, 8000),
        right: with_hot(&mut rng, 1000, 4242, 6, 8000),
        partitions: 16,
        breaks_hashing: true,
        breaks_modulo: false,
    });
    cases.push(Case {
        name: "almost everything is one key (80 %)",
        left: with_hot(&mut rng, 3000, 7, 2600, 2000),
        right: with_hot(&mut rng, 500, 7, 20, 2000),
        partitions: 8,
        breaks_hashing: true,
        breaks_modulo: false,
    });
    cases.push(Case {
        name: "strided keys, multiples of 64, over 16 partitions",
        left: strided(&mut rng, 3000, 900, 64),
        right: strided(&mut rng, 3000, 900, 64),
        partitions: 16,
        breaks_hashing: false,
        breaks_modulo: true,
    });
    cases.push(Case {
        name: "strided keys AND a hot one — both routers lose",
        left: {
            let mut v = strided(&mut rng, 2500, 800, 128);
            v.extend((0..1500).map(|i| Row { key: 128 * 5, payload: i }));
            for i in (1..v.len()).rev() {
                let j = rng.below(i + 1);
                v.swap(i, j);
            }
            v
        },
        right: {
            let mut v = strided(&mut rng, 900, 800, 128);
            v.extend((0..9).map(|i| Row { key: 128 * 5, payload: 900 + i }));
            v
        },
        partitions: 16,
        breaks_hashing: true,
        breaks_modulo: true,
    });
    cases.push(Case {
        name: "a hot key over 32 partitions",
        left: with_hot(&mut rng, 6400, 55, 2600, 9000),
        right: with_hot(&mut rng, 1600, 55, 24, 9000),
        partitions: 32,
        breaks_hashing: true,
        breaks_modulo: false,
    });

    let mut audited_hashing = 0usize;
    let mut audited_modulo = 0usize;
    let mut lines: Vec<String> = Vec::new();
    let mut worst = (0u64, "");

    for c in &cases {
        let total = (c.left.len() + c.right.len()) as u64;
        let bound = bound_of(total, c.partitions);
        let mean = mean_of(total, c.partitions);
        let ctx = format!("case \"{}\" ({} × {} rows, {} partitions)", c.name, c.left.len(), c.right.len(), c.partitions);

        // Self-audit: the case must actually be hard for the router it
        // claims to defeat, or it teaches nothing.
        if let Some(why) = grid_key(&c.left, &c.right, c.partitions) {
            return Check::fail(
                ID,
                LABEL,
                format!("HARNESS BUG: {ctx} is outside the lab's stated scope — {why}. Please report this."),
            );
        }
        if c.breaks_hashing {
            let naive = naive_max_load(&c.left, &c.right, c.partitions, true);
            if naive <= bound {
                return Check::fail(
                    ID,
                    LABEL,
                    format!("HARNESS BUG: {ctx} is passed by a plain hash router ({naive} rows on its busiest partition, bound {bound}) — it does not force heavy-hitter detection. Please report this."),
                );
            }
            audited_hashing += 1;
        }
        if c.breaks_modulo {
            let naive = naive_max_load(&c.left, &c.right, c.partitions, false);
            if naive <= bound {
                return Check::fail(
                    ID,
                    LABEL,
                    format!("HARNESS BUG: {ctx} is passed by a raw `key % partitions` router ({naive} rows on its busiest partition, bound {bound}) — please report this."),
                );
            }
            audited_modulo += 1;
        }

        let g = match grade(&c.left, &c.right, c.partitions, &ctx, false) {
            Ok(g) => g,
            Err(msg) => return Check::fail(ID, LABEL, msg),
        };
        if g.max_load > g.bound {
            let hot = {
                let mut counts: BTreeMap<Key, u64> = BTreeMap::new();
                for r in c.left.iter().chain(c.right.iter()) {
                    *counts.entry(r.key).or_insert(0) += 1;
                }
                counts.into_iter().max_by_key(|(_, n)| *n).map(|(k, n)| format!("key {k} carries {n} of the {total} rows")).unwrap_or_default()
            };
            return Check::fail(
                ID,
                LABEL,
                format!(
                    "{ctx}: the busiest partition holds {} rows, over the bound of {} ({}× the average partition's {mean}). {hot}. \
                     The largest partition IS the runtime — the mean of {mean} is the number that made you think you had scaled. \
                     Detect the heavy hitter with key_counts, split its bigger side across salt buckets, and replicate the smaller side into all of them.",
                    g.max_load, g.bound, show1(tenths(g.max_load, mean.max(1)))
                ),
            );
        }
        let ratio = tenths(g.max_load, mean.max(1));
        if ratio > worst.0 {
            worst = (ratio, c.name);
        }
        lines.push(format!("{} max {} / bound {} ({}× mean)", c.name, g.max_load, g.bound, show1(ratio)));
    }

    if audited_hashing == 0 || audited_modulo == 0 {
        return Check::fail(
            ID,
            LABEL,
            format!("HARNESS BUG: {audited_hashing} cases proved to defeat plain hashing and {audited_modulo} to defeat raw modulo — both must be non-zero. Please report this."),
        );
    }

    Check::pass(
        ID,
        LABEL,
        format!(
            "{} deliberately skewed cases all fit under the published bound of {}× the average partition, worst at {}× the mean (\"{}\"). \
             The harness proved each case first: {audited_hashing} of them blow the bound under a plain hash router, {audited_modulo} under a raw `key % partitions` router — so no naive routing passes this. \
             Every case's join output was verified against the reference before its partitions were measured. Per case: {}.",
            cases.len(),
            SKEW_FACTOR,
            show1(worst.0),
            worst.1,
            lines.join("; ")
        ),
    )
}

/* ============================= 5 · storm ============================= */

/// 800 seeded join plans across cardinalities and skew profiles, every one
/// of them multiset-exact against the reference — through the partitioned
/// path and through the plan `execute` chose — with the total bytes moved
/// held to a sane multiple of the reference plan so that a router cannot buy
/// balance with unlimited replication.
pub fn check_storm() -> Check {
    const ID: &str = "storm";
    const LABEL: &str = "800 seeded join plans across cardinalities and skew profiles";
    const PLANS: usize = 800;
    /// Generous — the bands do the tight grading. This catches routers that
    /// replicate their way out of trouble.
    const MAX_TOTAL_PCT: u64 = 200;

    if let Some(msg) = givens_intact() {
        return Check::fail(ID, LABEL, msg);
    }

    let mut rng = Rng(0x570F_B000_0001);
    let mut moved = 0u64;
    let mut reference_bytes = 0u64;
    let mut pairs = 0usize;
    let mut rows_routed = 0u64;
    let mut over_bound = 0usize;
    let mut in_scope = 0usize;
    let mut grid_scope = 0usize;
    let mut first_over = String::new();
    let mut profile_counts = [0usize; 6];
    let mut broadcasts = 0usize;
    let mut worst_skew = (0u64, 0usize);
    let mut max_pairs = 0usize;

    for plan in 0..PLANS {
        let profile = plan % 6;
        profile_counts[profile] += 1;
        let partitions = [1usize, 2, 4, 8, 16, 32, 7, 13][plan % 8];
        let (left, right) = match profile {
            // 0 — uniform over a wide key space: nothing to salt.
            0 => {
                let n = 1 + rng.below(600);
                let m = 1 + rng.below(600);
                (uniform(&mut rng, n, 5000), uniform(&mut rng, m, 5000))
            }
            // 1 — a tiny key space: duplicates on both sides everywhere.
            1 => {
                let n = 1 + rng.below(96);
                let m = 1 + rng.below(96);
                let span = 1 + rng.next() % 8;
                (uniform(&mut rng, n, span), uniform(&mut rng, m, span))
            }
            // 2 — one hot key on the left.
            2 => {
                let n = 40 + rng.below(500);
                let hot = n / 2 + rng.below(n / 3 + 1);
                let m = 20 + rng.below(200);
                let cold = 1 + rng.below(6);
                (with_hot(&mut rng, n, 777, hot, 900), with_hot(&mut rng, m, 777, cold, 900))
            }
            // 3 — one hot key on the right.
            3 => {
                let n = 20 + rng.below(200);
                let m = 40 + rng.below(500);
                let hot = m / 2 + rng.below(m / 3 + 1);
                let cold = 1 + rng.below(6);
                (with_hot(&mut rng, n, 31, cold, 900), with_hot(&mut rng, m, 31, hot, 900))
            }
            // 4 — strided keys: a router that does not avalanche collapses.
            4 => {
                let n = 1 + rng.below(400);
                let m = 1 + rng.below(400);
                let stride = [8u64, 64, 256, 1024][rng.below(4)];
                (strided(&mut rng, n, 300, stride), strided(&mut rng, m, 300, stride))
            }
            // 5 — degenerate cardinalities, including empty sides.
            _ => {
                let n = rng.below(4);
                let m = rng.below(300);
                if plan % 12 == 5 {
                    (uniform(&mut rng, n, 50), Vec::new())
                } else {
                    (uniform(&mut rng, n, 50), uniform(&mut rng, m, 50))
                }
            }
        };

        let ctx = format!(
            "storm plan {plan} (profile {profile}, {} × {} rows, {partitions} partitions)",
            left.len(),
            right.len()
        );
        let g = match grade(&left, &right, partitions, &ctx, plan % 97 == 0) {
            Ok(g) => g,
            Err(msg) => return Check::fail(ID, LABEL, msg),
        };
        moved += g.moved;
        reference_bytes += g.reference_bytes;
        rows_routed += g.moved / ROW_BYTES;
        pairs += g.out_rows;
        max_pairs = max_pairs.max(g.out_rows);
        // The bound is enforced on every plan where the harness can PROVE it
        // is reachable: enough distinct keys for hashing to behave, and a
        // busiest key whose indivisible minimum is small enough that several
        // of them could share a partition and still fit. Everywhere else the
        // key distribution itself defeats any router that cannot place
        // buckets by hand, so only correctness — enforced above, with no
        // allowance whatsoever — is graded.
        let atom = largest_atom(&left, &right, partitions);
        let distinct = distinct_keys(&left, &right);
        let provable = distinct >= 4 * partitions && atom * SKEW_FACTOR <= g.bound;
        if provable {
            in_scope += 1;
            if g.max_load > g.bound {
                over_bound += 1;
                if first_over.is_empty() {
                    first_over = format!(
                        "{ctx}: busiest partition {} rows, bound {} (mean {}, {distinct} distinct keys, busiest key's indivisible minimum {atom})",
                        g.max_load, g.bound, g.mean_load
                    );
                }
            }
            let ratio = tenths(g.max_load, g.mean_load.max(1));
            if ratio > worst_skew.0 {
                worst_skew = (ratio, plan);
            }
        } else {
            grid_scope += 1;
        }

        let stats = Stats { left_rows: left.len() as u64, right_rows: right.len() as u64, workers: partitions as u64 };
        if shuffle::choose_plan(&stats) == Plan::Broadcast {
            broadcasts += 1;
        }
        let want = match reference(&left, &right, &ctx) {
            Ok(w) => w,
            Err(msg) => return Check::fail(ID, LABEL, msg),
        };
        if let Some(msg) = join_diff(&shuffle::execute(&left, &right, partitions), &want, &format!("{ctx}, via execute")) {
            return Check::fail(ID, LABEL, msg);
        }
    }

    let pct = hundredths(moved, reference_bytes);
    if pct > MAX_TOTAL_PCT {
        return Check::fail(
            ID,
            LABEL,
            format!(
                "the {PLANS} plans were all correct, but they moved {moved} bytes against a reference plan of {reference_bytes} — {}×, over the {}× storm ceiling. \
                 Balance bought with unlimited replication is not balance, it is a bigger network bill.",
                show2(pct),
                show2(MAX_TOTAL_PCT)
            ),
        );
    }
    if over_bound > 0 {
        return Check::fail(
            ID,
            LABEL,
            format!(
                "{over_bound} of the {in_scope} storm plans whose bound is provably reachable left a partition over it — e.g. {first_over}. \
                 See skew_bounded for the same failure on a case built to explain it."
            ),
        );
    }
    if in_scope < PLANS / 4 {
        return Check::fail(
            ID,
            LABEL,
            format!("HARNESS BUG: only {in_scope} of {PLANS} storm plans have a provably reachable bound, so balance is barely graded here — please report this"),
        );
    }

    Check::pass(
        ID,
        LABEL,
        format!(
            "{PLANS} seeded plans across 6 skew profiles ({} uniform, {} tiny-key-space, {} left-hot, {} right-hot, {} strided, {} degenerate) are multiset-exact against the reference — \
             {pairs} output pairs compared row for row (largest single plan {max_pairs}), through the partitioned path and through the plan execute() chose ({broadcasts} of them broadcast). \
             {rows_routed} row-copies routed = {moved} bytes against a reference plan of {reference_bytes} ({}×, ceiling {}×). \
             The per-partition bound held on all {in_scope} plans where it is provably reachable, worst at {}× that plan's mean (plan {}); on the other {grid_scope} the key distribution itself defeats any hash-placed router, so only correctness was graded. \
             Every reference was audited against Σ_k left(k)·right(k), and against a nested loop wherever affordable.",
            profile_counts[0],
            profile_counts[1],
            profile_counts[2],
            profile_counts[3],
            profile_counts[4],
            profile_counts[5],
            show2(pct),
            show2(MAX_TOTAL_PCT),
            show1(worst_skew.0),
            worst_skew.1
        ),
    )
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_join_correct(),
        check_bytes_shuffled(),
        check_broadcast_choice(),
        check_skew_bounded(),
        check_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "shuffle", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
