//! vectorized — forge lab 03 (columnspaces).
//!
//! Batch-at-a-time execution: a selection vector, a filter, a hash
//! aggregate, and the path that answers a query on RLE runs and dictionary
//! codes without decoding them. Lab 02 stopped reading blocks; this lab
//! stops decoding the ones it does read.
//!
//! ┌────────────────────────────────────────────────────────────────┐
//! │  YOU EDIT:   src/vectorized.rs  (the only file with TODO(you)) │
//! │  DO NOT EDIT this file — it is the grading harness.             │
//! └────────────────────────────────────────────────────────────────┘
//!
//! What the harness is: an independent second implementation plus a ground
//! truth. It filters by scanning every row with its own three-valued logic,
//! it aggregates with its own arithmetic (never through `Agg::add`), and it
//! encodes its own RLE and dictionary columns. Every expectation comes from
//! there, not from the student's crate.
//!
//! The compressed path is graded as an EQUIVALENCE. The reference answer is
//! produced by decoding and running the scalar path, so a fast path that
//! disagrees is not a slower-but-safer trade-off — it is a wrong answer
//! arriving sooner, and it fails.
//!
//! Two columns declare billions of rows in a handful of runs. The harness
//! cannot expand those either, so their expected aggregate is computed
//! arithmetically — and that arithmetic reference is itself audited against
//! full expansion on every column small enough to expand. If the two
//! disagree, the harness fails LOUDLY with "HARNESS BUG" rather than
//! grading a student against an unsound model.
//!
//! Cost here is a COUNT — rows scanned, values materialized, predicate
//! evaluations, runs touched — never a clock, which is why this suite means
//! the same thing in the terminal and in the browser.
//!
//! BTreeMap only, never HashMap: std's HashMap seeds itself from OS
//! randomness that does not exist on `wasm32-unknown-unknown`.

mod vectorized;

use kslab::{Check, Report};
use std::collections::BTreeMap;
use vectorized::{Agg, Dict, GroupTable, Pred, Run};

/* --------------------------- determinism ---------------------------- */

/// xorshift64* — the same columns and the same predicates on every machine,
/// every run, in both wasm and native. Seeded per check so one failure
/// cannot move another check's data.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    fn below(&mut self, n: usize) -> usize {
        if n == 0 { 0 } else { (self.next() % n as u64) as usize }
    }
}

/* ----------------------- the reference model ------------------------ */
/* A second implementation of the pinned semantics: its own 3VL, its own     */
/* arithmetic, its own encoders. Nothing here calls into the student's       */
/* helpers, not even the GIVEN ones.                                         */

/// GROUND TRUTH, at row level: three-valued logic. A null is not comparable
/// to anything.
fn ref_matches(value: Option<i64>, pred: &Pred) -> bool {
    let v = match value {
        None => return matches!(pred, Pred::IsNull),
        Some(v) => v,
    };
    match pred {
        Pred::Ge(k) => v >= *k,
        Pred::Gt(k) => v > *k,
        Pred::Le(k) => v <= *k,
        Pred::Lt(k) => v < *k,
        Pred::Eq(k) => v == *k,
        Pred::Between(lo, hi) => v >= *lo && v <= *hi,
        Pred::IsNull => false,
        Pred::IsNotNull => true,
    }
}

/// GROUND TRUTH: the positions of `input` whose value satisfies `pred`,
/// found by looking at every one of them.
fn ref_filter(values: &[Option<i64>], pred: &Pred, input: &[u32]) -> Vec<u32> {
    input
        .iter()
        .copied()
        .filter(|&p| (p as usize) < values.len() && ref_matches(values[p as usize], pred))
        .collect()
}

fn ref_gather(values: &[Option<i64>], sel: &[u32]) -> Vec<Option<i64>> {
    sel.iter().map(|&p| values[p as usize]).collect()
}

/// GROUND TRUTH: the aggregate of a set of values, computed with the
/// harness's own arithmetic and built as a struct literal — `Agg::add` is
/// the student's file, and a reference that borrows the implementation it
/// grades is not a reference.
fn ref_agg(values: &[Option<i64>]) -> Agg {
    let mut count = 0u64;
    let mut nulls = 0u64;
    let mut sum = 0i128;
    let mut min: Option<i64> = None;
    let mut max: Option<i64> = None;
    for &v in values {
        count += 1;
        match v {
            None => nulls += 1,
            Some(x) => {
                sum += x as i128;
                min = Some(min.map_or(x, |m| if x < m { x } else { m }));
                max = Some(max.map_or(x, |m| if x > m { x } else { m }));
            }
        }
    }
    Agg { count, nulls, sum, min, max }
}

/// A SECOND way to compute the same thing, used only to audit `ref_agg`:
/// iterator combinators over the non-null values instead of one loop.
fn ref_agg_alt(values: &[Option<i64>]) -> Agg {
    let live: Vec<i64> = values.iter().filter_map(|v| *v).collect();
    Agg {
        count: values.len() as u64,
        nulls: (values.len() - live.len()) as u64,
        sum: live.iter().map(|&v| v as i128).sum(),
        min: live.iter().copied().min(),
        max: live.iter().copied().max(),
    }
}

/// The arithmetic reference for a run: what execute-on-compressed must
/// produce. Audited against `ref_agg(expand(runs))` on every expandable
/// column below — that audit is what earns this function the right to be
/// the expectation for columns too large to expand.
fn ref_run_agg(value: Option<i64>, count: u32) -> Agg {
    if count == 0 {
        return Agg::default();
    }
    match value {
        None => Agg { count: count as u64, nulls: count as u64, sum: 0, min: None, max: None },
        Some(v) => Agg {
            count: count as u64,
            nulls: 0,
            sum: v as i128 * count as i128,
            min: Some(v),
            max: Some(v),
        },
    }
}

fn ref_merge(a: &Agg, b: &Agg) -> Agg {
    let pick = |x: Option<i64>, y: Option<i64>, lt: bool| -> Option<i64> {
        match (x, y) {
            (None, y) => y,
            (x, None) => x,
            (Some(x), Some(y)) => Some(if (x < y) == lt { x } else { y }),
        }
    };
    Agg {
        count: a.count + b.count,
        nulls: a.nulls + b.nulls,
        sum: a.sum + b.sum,
        min: pick(a.min, b.min, true),
        max: pick(a.max, b.max, false),
    }
}

fn ref_rle_agg(runs: &[Run]) -> Agg {
    runs.iter().fold(Agg::default(), |acc, &(v, c)| ref_merge(&acc, &ref_run_agg(v, c)))
}

/// GROUND TRUTH for the aggregate: group by key over selected positions,
/// with a NULL key as a group of its own.
fn ref_groups(keys: &[Option<i64>], vals: &[Option<i64>], sel: &[u32]) -> BTreeMap<Option<i64>, Vec<Option<i64>>> {
    let mut out: BTreeMap<Option<i64>, Vec<Option<i64>>> = BTreeMap::new();
    for &p in sel {
        out.entry(keys[p as usize]).or_default().push(vals[p as usize]);
    }
    out
}

fn ref_group_aggs(keys: &[Option<i64>], vals: &[Option<i64>], sel: &[u32]) -> Vec<(Option<i64>, Agg)> {
    ref_groups(keys, vals, sel).into_iter().map(|(k, vs)| (k, ref_agg(&vs))).collect()
}

/* ------------------------------ encoders ---------------------------- */

/// Maximal runs — the encoded form lab 01 produces.
fn rle(values: &[Option<i64>]) -> Vec<Run> {
    let mut runs: Vec<Run> = Vec::new();
    for &v in values {
        match runs.last_mut() {
            Some((last, count)) if *last == v => *count += 1,
            _ => runs.push((v, 1)),
        }
    }
    runs
}

fn expand(runs: &[Run]) -> Vec<Option<i64>> {
    let mut out = Vec::new();
    for &(v, count) in runs {
        for _ in 0..count {
            out.push(v);
        }
    }
    out
}

/// Distinct values in sorted order, one code per row. Sorted so the codes
/// are deterministic — a real dictionary is usually insertion-ordered, and
/// nothing in the lab depends on which.
fn dict_encode(values: &[Option<i64>]) -> Dict {
    let mut distinct: Vec<Option<i64>> = Vec::new();
    {
        let mut seen: std::collections::BTreeSet<Option<i64>> = std::collections::BTreeSet::new();
        for &v in values {
            if seen.insert(v) {
                distinct.push(v);
            }
        }
        distinct.sort();
    }
    let index: BTreeMap<Option<i64>, u32> =
        distinct.iter().enumerate().map(|(i, v)| (*v, i as u32)).collect();
    Dict {
        codes: values.iter().map(|v| index[v]).collect(),
        entries: distinct,
    }
}

fn dict_decode(dict: &Dict) -> Vec<Option<i64>> {
    dict.codes.iter().map(|&c| dict.entries[c as usize]).collect()
}

/* ---------------------------- formatting ---------------------------- */

fn pred_str(p: &Pred) -> String {
    match p {
        Pred::Ge(k) => format!("v >= {k}"),
        Pred::Gt(k) => format!("v > {k}"),
        Pred::Le(k) => format!("v <= {k}"),
        Pred::Lt(k) => format!("v < {k}"),
        Pred::Eq(k) => format!("v == {k}"),
        Pred::Between(lo, hi) => format!("v BETWEEN {lo} AND {hi}"),
        Pred::IsNull => "v IS NULL".to_string(),
        Pred::IsNotNull => "v IS NOT NULL".to_string(),
    }
}

fn shape(p: &Pred) -> &'static str {
    match p {
        Pred::Ge(_) => ">=",
        Pred::Gt(_) => ">",
        Pred::Le(_) => "<=",
        Pred::Lt(_) => "<",
        Pred::Eq(_) => "==",
        Pred::Between(..) => "between",
        Pred::IsNull => "is null",
        Pred::IsNotNull => "is not null",
    }
}

fn agg_str(a: &Agg) -> String {
    format!("count {} (nulls {}), sum {}, min {:?}, max {:?}", a.count, a.nulls, a.sum, a.min, a.max)
}

/// Where two aggregates differ, field by field — "want Agg { .. }" is not a
/// diagnosis.
fn agg_diff(got: &Agg, want: &Agg) -> String {
    let mut parts = Vec::new();
    if got.count != want.count {
        parts.push(format!("count {} vs {} (count is COUNT(*): every selected row, nulls included)", got.count, want.count));
    }
    if got.nulls != want.nulls {
        parts.push(format!("nulls {} vs {}", got.nulls, want.nulls));
    }
    if got.sum != want.sum {
        parts.push(format!("sum {} vs {} (over non-null values only, in i128)", got.sum, want.sum));
    }
    if got.min != want.min {
        parts.push(format!("min {:?} vs {:?} (non-null values only; None means there were none)", got.min, want.min));
    }
    if got.max != want.max {
        parts.push(format!("max {:?} vs {:?}", got.max, want.max));
    }
    if parts.is_empty() {
        "identical".to_string()
    } else {
        parts.join("; ")
    }
}

fn sel_str(sel: &[u32]) -> String {
    if sel.len() <= 12 {
        format!("{sel:?}")
    } else {
        format!("[{}, … {} more]", sel[..8].iter().map(|p| p.to_string()).collect::<Vec<_>>().join(", "), sel.len() - 8)
    }
}

fn vals_str(vs: &[Option<i64>]) -> String {
    if vs.len() <= 8 {
        format!("{vs:?}")
    } else {
        format!("[{:?}, … {} more]", &vs[..6], vs.len() - 6)
    }
}

fn percent(part: u64, whole: u64) -> String {
    if whole == 0 {
        return "n/a".to_string();
    }
    let tenths = part * 1000 / whole;
    format!("{}.{}%", tenths / 10, tenths % 10)
}

fn ratio(numer: u64, denom: u64) -> String {
    if denom == 0 {
        return "n/a".to_string();
    }
    let tenths = numer * 10 / denom;
    format!("{}.{}", tenths / 10, tenths % 10)
}

/* ------------------------- selection hygiene ------------------------ */

/// The four pinned `Sel` invariants, checked on every selection the student
/// returns anywhere in this suite. A selection that breaks one of these is
/// not merely wrong here — it silently corrupts whatever consumes it,
/// because every later operator indexes by position.
fn check_sel(sel: &[u32], input: &[u32], n: usize, what: &str) -> Result<(), String> {
    for w in sel.windows(2) {
        if w[0] >= w[1] {
            return Err(format!(
                "{what}: selection {} is not strictly increasing ({} then {}) — row order is the one thing a selection vector must preserve, and gather, composition and late materialization all assume a forward pass",
                sel_str(sel), w[0], w[1]));
        }
    }
    if let Some(&bad) = sel.iter().find(|&&p| p as usize >= n) {
        return Err(format!(
            "{what}: selection contains position {bad} in a batch of {n} rows — a position indexes THIS batch; out of range means the next operator reads someone else's memory (or panics)",
            ));
    }
    let allowed: std::collections::BTreeSet<u32> = input.iter().copied().collect();
    if let Some(&bad) = sel.iter().find(|p| !allowed.contains(p)) {
        return Err(format!(
            "{what}: selection contains position {bad}, which was not in the input selection {} — a filter NARROWS. Resurrecting a row an earlier predicate already killed turns a chain of ANDs into something else entirely",
            sel_str(input)));
    }
    Ok(())
}

/* --------------------------- column shapes -------------------------- */

fn col_random(rng: &mut Rng, n: usize, span: usize) -> Vec<Option<i64>> {
    (0..n).map(|_| Some(rng.below(span) as i64)).collect()
}

fn col_constant(rng: &mut Rng, n: usize) -> Vec<Option<i64>> {
    let v = rng.below(1000) as i64;
    vec![Some(v); n]
}

fn col_all_null(n: usize) -> Vec<Option<i64>> {
    vec![None; n]
}

/// Monotone: the timestamp column, and the one RLE hates and FOR loves.
fn col_monotone(rng: &mut Rng, n: usize) -> Vec<Option<i64>> {
    let mut t = 1_700_000_000_000i64 + rng.below(1 << 20) as i64;
    (0..n)
        .map(|_| {
            t = t.wrapping_add(1 + rng.below(97) as i64);
            Some(t)
        })
        .collect()
}

/// Few distinct values, skewed: the shape a dictionary is for, and the one
/// where a per-distinct-value predicate evaluation is 12 comparisons for a
/// million rows.
fn col_few_distinct(rng: &mut Rng, n: usize, k: usize) -> Vec<Option<i64>> {
    let vals: Vec<Option<i64>> = (0..k)
        .map(|i| if i == 0 && k > 3 { None } else { Some(rng.below(200) as i64) })
        .collect();
    (0..n)
        .map(|_| {
            // skewed: the low codes are far more common, as in real data
            let r = rng.below(100);
            let i = if r < 60 { 0 } else if r < 85 { 1 } else { rng.below(k) };
            vals[i.min(k - 1)]
        })
        .collect()
}

/// Long runs of one value: the shape RLE is for.
fn col_long_runs(rng: &mut Rng, n: usize) -> Vec<Option<i64>> {
    let mut out = Vec::with_capacity(n);
    while out.len() < n {
        let v = if rng.below(4) == 0 { None } else { Some(rng.below(30) as i64) };
        let len = (1 + rng.below(50)).min(n - out.len());
        for _ in 0..len {
            out.push(v);
        }
    }
    out
}

/// i64 edges, where an aggregate written in i64 overflows and a range test
/// written with arithmetic wraps.
fn col_extremes(rng: &mut Rng, n: usize) -> Vec<Option<i64>> {
    (0..n)
        .map(|_| match rng.below(6) {
            0 => Some(i64::MIN),
            1 => Some(i64::MAX),
            2 => Some(0),
            3 => None,
            4 => Some(i64::MAX - 1),
            _ => Some(rng.next() as i64),
        })
        .collect()
}

fn col_alt_nulls(n: usize) -> Vec<Option<i64>> {
    (0..n).map(|i| if i % 2 == 0 { None } else { Some(i as i64) }).collect()
}

fn col_bools(rng: &mut Rng, n: usize) -> Vec<Option<i64>> {
    (0..n).map(|_| Some(rng.below(2) as i64)).collect()
}

/// Nine families, each of which embarrasses a different operator.
fn make_column(rng: &mut Rng, n: usize, i: usize) -> (String, Vec<Option<i64>>) {
    match i % 9 {
        0 => ("random over 64".to_string(), col_random(rng, n, 64)),
        1 => ("constant".to_string(), col_constant(rng, n)),
        2 => ("all null".to_string(), col_all_null(n)),
        3 => ("monotone timestamps".to_string(), col_monotone(rng, n)),
        4 => ("12 distinct, skewed, with a null entry".to_string(), col_few_distinct(rng, n, 12)),
        5 => ("long runs".to_string(), col_long_runs(rng, n)),
        6 => ("i64 extremes".to_string(), col_extremes(rng, n)),
        7 => ("alternating nulls".to_string(), col_alt_nulls(n)),
        _ => ("booleans".to_string(), col_bools(rng, n)),
    }
}

/// Group keys: a handful of groups, some null keys, and — when `unique_at`
/// is `Some(p)` — one key placed at exactly one position, which is the
/// group that vanishes if batches are aggregated independently and then
/// dropped.
fn make_keys(rng: &mut Rng, n: usize, groups: usize, unique_at: Option<usize>) -> Vec<Option<i64>> {
    let mut keys: Vec<Option<i64>> = (0..n)
        .map(|_| {
            if rng.below(11) == 0 {
                None
            } else {
                Some(rng.below(groups.max(1)) as i64)
            }
        })
        .collect();
    if let Some(p) = unique_at {
        if p < n {
            keys[p] = Some(999_999);
        }
    }
    keys
}

/// A predicate over `values`, drawn so that the mix contains selective
/// windows, predicates nothing satisfies, and predicates everything
/// satisfies. All eight shapes appear.
fn make_pred(rng: &mut Rng, values: &[Option<i64>], i: usize) -> Pred {
    let live: Vec<i64> = values.iter().filter_map(|v| *v).collect();
    let (min, max) = (live.iter().copied().min(), live.iter().copied().max());
    let pick = |rng: &mut Rng| -> i64 {
        match (min, max) {
            (Some(min), Some(max)) => {
                let span = (max as u64).wrapping_sub(min as u64);
                match rng.below(8) {
                    // outside the range on either side: nothing survives
                    0 => min.wrapping_sub(1 + rng.below(1000) as i64),
                    1 => max.wrapping_add(1 + rng.below(1000) as i64),
                    // the boundaries, where >= and > differ
                    2 => min,
                    3 => max,
                    _ => {
                        let off = if span == u64::MAX { rng.next() } else { rng.next() % (span + 1) };
                        (min as u64).wrapping_add(off) as i64
                    }
                }
            }
            _ => rng.next() as i64,
        }
    };
    match i % 8 {
        0 => Pred::Ge(pick(rng)),
        1 => Pred::Gt(pick(rng)),
        2 => Pred::Le(pick(rng)),
        3 => Pred::Lt(pick(rng)),
        4 => Pred::Eq(pick(rng)),
        5 => {
            let (a, b) = (pick(rng), pick(rng));
            // one in eight is deliberately self-contradicting (hi < lo)
            if rng.below(8) == 0 {
                Pred::Between(a.max(b), a.min(b))
            } else {
                Pred::Between(a.min(b), a.max(b))
            }
        }
        6 => Pred::IsNull,
        _ => Pred::IsNotNull,
    }
}

/// Batch boundaries over `n` rows with batch size `bs`, so that the final
/// batch is partial whenever `n % bs != 0`. Every check in this lab runs
/// over at least one partial final batch, because that is where an
/// off-by-one in a batched loop lives.
fn batches(n: usize, bs: usize) -> Vec<(usize, usize)> {
    let bs = bs.max(1);
    let mut out = Vec::new();
    let mut lo = 0;
    while lo < n {
        let hi = (lo + bs).min(n);
        out.push((lo, hi));
        lo = hi;
    }
    out
}

/* --------------------------- harness audit -------------------------- */

/// The harness checking its own model before it grades anybody: the two
/// independent aggregate implementations must agree, the arithmetic run
/// reference must agree with full expansion, and both encoders must round
/// trip. Called at the top of every check with that check's own data.
fn audit(values: &[Option<i64>], what: &str) -> Result<(), String> {
    let a = ref_agg(values);
    let b = ref_agg_alt(values);
    if a != b {
        return Err(format!(
            "HARNESS BUG: the two reference aggregates disagree on {what} — {} vs {} — please report this",
            agg_str(&a), agg_str(&b)));
    }
    let runs = rle(values);
    let round = expand(&runs);
    if round != values {
        return Err(format!("HARNESS BUG: the reference RLE encoder does not round trip on {what} — please report this"));
    }
    let arith = ref_rle_agg(&runs);
    if arith != a {
        return Err(format!(
            "HARNESS BUG: the arithmetic run reference ({}) disagrees with decode-then-aggregate ({}) on {what} — the expectations for the billion-row columns come from that arithmetic, so this must never happen. Please report this.",
            agg_str(&arith), agg_str(&a)));
    }
    let dict = dict_encode(values);
    if dict_decode(&dict) != values {
        return Err(format!("HARNESS BUG: the reference dictionary encoder does not round trip on {what} — please report this"));
    }
    if dict.entries.len() > values.len() && !values.is_empty() {
        return Err(format!("HARNESS BUG: dictionary for {what} has more entries than rows — please report this"));
    }
    Ok(())
}

/* ------------------------------ checks ------------------------------ */

/// 1. filter_matches_scalar: the batched filter answers exactly what a
///    row-at-a-time loop answers — same rows, same order — under all eight
///    predicate shapes, on nine column families, including empty batches
///    and batches where nothing survives.
pub fn check_filter_matches_scalar() -> Check {
    const ID: &str = "filter_matches_scalar";
    const LABEL: &str = "batched filter produces the same rows as a scalar reference";
    let mut rng = Rng(0x03F1_17E5);

    // hand cases, where the answer is obvious by eye
    let hand: Vec<(&str, Vec<Option<i64>>, Pred)> = vec![
        ("an empty batch", vec![], Pred::Ge(0)),
        ("one value, matching", vec![Some(5)], Pred::Ge(5)),
        ("one value, not matching", vec![Some(5)], Pred::Gt(5)),
        ("one null, IS NULL", vec![None], Pred::IsNull),
        ("one null, a comparison", vec![None], Pred::Ge(i64::MIN)),
        ("all nulls, IS NOT NULL", vec![None; 8], Pred::IsNotNull),
        ("everything matches", vec![Some(1), Some(2), Some(3)], Pred::Between(i64::MIN, i64::MAX)),
        ("nothing matches", vec![Some(1), Some(2), Some(3)], Pred::Gt(3)),
        ("first row only", vec![Some(9), Some(1), Some(1)], Pred::Gt(1)),
        ("last row only", vec![Some(1), Some(1), Some(9)], Pred::Gt(1)),
        ("nulls between matches", vec![Some(9), None, Some(9), None], Pred::Eq(9)),
        ("a self-contradicting range", vec![Some(1), Some(5), Some(9)], Pred::Between(9, 1)),
        ("i64 edges", vec![Some(i64::MIN), None, Some(0), Some(i64::MAX)], Pred::Ge(0)),
        ("boundary: >= max", vec![Some(1), Some(2), Some(3)], Pred::Ge(3)),
        ("boundary: > max", vec![Some(1), Some(2), Some(3)], Pred::Gt(3)),
        ("boundary: <= min", vec![Some(1), Some(2), Some(3)], Pred::Le(1)),
        ("boundary: < min", vec![Some(1), Some(2), Some(3)], Pred::Lt(1)),
    ];
    for (name, values, pred) in &hand {
        let input = vectorized::all_rows(values.len());
        if input != (0..values.len() as u32).collect::<Vec<u32>>() {
            return Check::fail(ID, LABEL, "all_rows is GIVEN and must return every position in order — if you changed it, put it back");
        }
        let got = vectorized::filter(values, pred, &input);
        let want = ref_filter(values, pred, &input);
        if let Err(msg) = check_sel(&got, &input, values.len(), name) {
            return Check::fail(ID, LABEL, msg);
        }
        if got != want {
            return Check::fail(ID, LABEL, format!(
                "{name}: filter({}, {}) selected {}, want {} — the scalar reference tested every row with three-valued logic. {}",
                vals_str(values), pred_str(pred), sel_str(&got), sel_str(&want),
                if want.is_empty() { "Nothing survives here: an empty selection is the right answer, and it is NOT all_rows." } else { "Compare the values at the positions that differ." }));
        }
        let materialized = vectorized::gather(values, &got);
        let want_vals = ref_gather(values, &want);
        if materialized != want_vals {
            return Check::fail(ID, LABEL, format!(
                "{name}: gather over the selection produced {}, want {} — gather copies the values at the selection's positions, in selection order, and nothing else",
                vals_str(&materialized), vals_str(&want_vals)));
        }
    }

    // gather's own contract, separately: over all_rows it is the identity
    let probe: Vec<Option<i64>> = vec![Some(3), None, Some(-1), Some(i64::MAX), None];
    if vectorized::gather(&probe, &vectorized::all_rows(probe.len())) != probe {
        return Check::fail(ID, LABEL,
            "gather(values, all_rows(n)) must return the values unchanged — it is a copy, in order, with nulls preserved as nulls");
    }
    if !vectorized::gather(&probe, &Vec::new()).is_empty() {
        return Check::fail(ID, LABEL, "gather over an empty selection is an empty vector — no rows survived, so no values are produced");
    }

    // and over the corpus: nine families × eight shapes, in batches with a
    // partial final batch
    let mut shapes: BTreeMap<&'static str, usize> = BTreeMap::new();
    let (mut scanned, mut survived, mut batch_count, mut partials) = (0u64, 0u64, 0u64, 0u64);
    for i in 0..27 {
        let n = [1usize, 7, 64, 100, 257, 512][i % 6];
        let (cname, values) = make_column(&mut rng, n, i);
        if let Err(msg) = audit(&values, &cname) {
            return Check::fail(ID, LABEL, msg);
        }
        let bs = [1usize, 3, 16, 64, 300][i % 5];
        for j in 0..8 {
            let pred = make_pred(&mut rng, &values, j);
            *shapes.entry(shape(&pred)).or_insert(0) += 1;
            for (lo, hi) in batches(n, bs) {
                let batch = &values[lo..hi];
                let input = vectorized::all_rows(batch.len());
                let got = vectorized::filter(batch, &pred, &input);
                let want = ref_filter(batch, &pred, &input);
                batch_count += 1;
                if hi - lo < bs {
                    partials += 1;
                }
                scanned += batch.len() as u64;
                survived += got.len() as u64;
                if let Err(msg) = check_sel(&got, &input, batch.len(), &format!("{cname}, rows {lo}..{hi}, {}", pred_str(&pred))) {
                    return Check::fail(ID, LABEL, msg);
                }
                if got != want {
                    let first = (0..got.len().max(want.len()))
                        .find(|&k| got.get(k) != want.get(k))
                        .unwrap_or(0);
                    let pos = want.get(first).or_else(|| got.get(first)).copied().unwrap_or(0);
                    return Check::fail(ID, LABEL, format!(
                        "{cname}, batch of rows {lo}..{hi} under {}: you selected {} ({} rows), the scalar reference selects {} ({} rows). They first differ at output index {first}, around batch position {pos}, whose value is {:?}. A batched filter is not allowed to be a different filter.",
                        pred_str(&pred), sel_str(&got), got.len(), sel_str(&want), want.len(),
                        batch.get(pos as usize)));
                }
                if vectorized::gather(batch, &got) != ref_gather(batch, &want) {
                    return Check::fail(ID, LABEL, format!(
                        "{cname}, rows {lo}..{hi} under {}: the selection is right but gather produced different values — gather(values, sel) is values[sel[0]], values[sel[1]], … in that order",
                        pred_str(&pred)));
                }
            }
        }
    }
    let mix: Vec<String> = shapes.iter().map(|(k, v)| format!("{k} {v}")).collect();
    Check::pass(ID, LABEL, format!(
        "{} hand cases and {batch_count} batches ({partials} of them partial final batches) exact against a row-at-a-time reference — {scanned} rows scanned, {survived} survived ({}). Mix: {}.",
        hand.len(), percent(survived, scanned), mix.join(", ")))
}

/// 2. selection_vector: selections compose. Two predicates on two columns
///    of the same batch narrow one selection without either of them copying
///    a value — and the composed answer equals the answer you would get by
///    materializing in between, which is the proof that materializing is
///    unnecessary rather than merely slower.
pub fn check_selection_vector() -> Check {
    const ID: &str = "selection_vector";
    const LABEL: &str = "selection vectors compose across chained predicates without materializing";
    let mut rng = Rng(0x5E1E_C701);

    // an empty input selection: every predicate must return empty. This is
    // the "survives nothing" case, and it must survive the whole pipeline.
    let values: Vec<Option<i64>> = vec![Some(1), None, Some(5), Some(9)];
    for pred in [
        Pred::Ge(i64::MIN), Pred::Gt(0), Pred::Le(i64::MAX), Pred::Lt(9),
        Pred::Eq(5), Pred::Between(i64::MIN, i64::MAX), Pred::IsNull, Pred::IsNotNull,
    ] {
        let out = vectorized::filter(&values, &pred, &Vec::new());
        if !out.is_empty() {
            return Check::fail(ID, LABEL, format!(
                "filter over an EMPTY input selection under {} returned {} — an empty selection means no rows survived the previous operator. Reading it as \"no selection, therefore all rows\" resurrects every row in the batch, and the query returns rows a predicate already rejected.",
                pred_str(&pred), sel_str(&out)));
        }
    }

    // chains: two and three deep, over columns of different shapes
    let (mut chains, mut kept, mut input_rows) = (0u64, 0u64, 0u64);
    let mut nothing_survived = 0u64;
    for i in 0..24 {
        let n = [8usize, 33, 64, 129, 256][i % 5];
        let (name_a, a) = make_column(&mut rng, n, i);
        let (name_b, b) = make_column(&mut rng, n, i + 4);
        let (name_c, c) = make_column(&mut rng, n, i + 7);
        if let Err(msg) = audit(&a, &name_a) {
            return Check::fail(ID, LABEL, msg);
        }
        for j in 0..8 {
            let p1 = make_pred(&mut rng, &a, j);
            let p2 = make_pred(&mut rng, &b, j + 3);
            let p3 = make_pred(&mut rng, &c, j + 5);
            let all = vectorized::all_rows(n);

            let s1 = vectorized::filter(&a, &p1, &all);
            if let Err(msg) = check_sel(&s1, &all, n, &format!("{name_a} under {}", pred_str(&p1))) {
                return Check::fail(ID, LABEL, msg);
            }
            let s2 = vectorized::filter(&b, &p2, &s1);
            if let Err(msg) = check_sel(&s2, &s1, n, &format!("{name_b} under {} chained after {}", pred_str(&p2), pred_str(&p1))) {
                return Check::fail(ID, LABEL, msg);
            }
            let s3 = vectorized::filter(&c, &p3, &s2);
            if let Err(msg) = check_sel(&s3, &s2, n, "the third link of the chain") {
                return Check::fail(ID, LABEL, msg);
            }

            // ground truth: the positions satisfying all three, found by
            // scanning
            let want: Vec<u32> = (0..n as u32)
                .filter(|&p| {
                    ref_matches(a[p as usize], &p1)
                        && ref_matches(b[p as usize], &p2)
                        && ref_matches(c[p as usize], &p3)
                })
                .collect();
            if s3 != want {
                return Check::fail(ID, LABEL, format!(
                    "chain [{} on {name_a}] → [{} on {name_b}] → [{} on {name_c}] over {n} rows: you kept {}, the reference keeps {}. A chain of filters is an AND over positions: each link tests only the rows the previous link left alive, and positions never shift.",
                    pred_str(&p1), pred_str(&p2), pred_str(&p3), sel_str(&s3), sel_str(&want)));
            }

            // order independence: AND commutes, so the two orders must give
            // the same positions
            let alt = vectorized::filter(&a, &p1, &vectorized::filter(&b, &p2, &all));
            let both: Vec<u32> = (0..n as u32)
                .filter(|&p| ref_matches(a[p as usize], &p1) && ref_matches(b[p as usize], &p2))
                .collect();
            if alt != both || vectorized::filter(&b, &p2, &s1) != both {
                return Check::fail(ID, LABEL, format!(
                    "[{} on {name_a}] then [{} on {name_b}] gives {}, but the other order gives {} — an AND of two predicates is one set of positions, and a selection vector that depends on evaluation order is not a set",
                    pred_str(&p1), pred_str(&p2), sel_str(&vectorized::filter(&b, &p2, &s1)), sel_str(&alt)));
            }

            // idempotence: re-applying a predicate to its own output is a
            // no-op
            if vectorized::filter(&a, &p1, &s1) != s1 {
                return Check::fail(ID, LABEL, format!(
                    "applying {} twice changed the selection — every surviving row already satisfies it",
                    pred_str(&p1)));
            }

            // THE POINT: composing selections equals materializing in
            // between. Filter b's GATHERED values, then map the local
            // positions back through s1 — if that is not s2, then the
            // selection vector is not carrying position information
            // faithfully, and late materialization would change answers.
            let mat_b = vectorized::gather(&b, &s1);
            let local = vectorized::filter(&mat_b, &p2, &vectorized::all_rows(mat_b.len()));
            let mapped: Vec<u32> = local.iter().map(|&l| s1[l as usize]).collect();
            if mapped != s2 {
                return Check::fail(ID, LABEL, format!(
                    "composing selections gave {}, but materializing the intermediate column and filtering that gave {} (mapped back through the first selection) — these must be the same positions. When they are not, late materialization is not safe in your engine, and the entire reason for a selection vector is gone.",
                    sel_str(&s2), sel_str(&mapped)));
            }

            // and a selection that survives nothing must stay nothing
            if s3.is_empty() {
                nothing_survived += 1;
                let after = vectorized::filter(&a, &Pred::IsNotNull, &s3);
                if !after.is_empty() {
                    return Check::fail(ID, LABEL,
                        "a chain that killed every row was followed by a filter that produced rows — nothing can survive an empty selection");
                }
                if !vectorized::gather(&a, &s3).is_empty() {
                    return Check::fail(ID, LABEL, "gather over an empty selection must produce no values");
                }
                let mut table = GroupTable::new();
                vectorized::aggregate_batch(&mut table, &a, &b, &s3);
                if !table.is_empty() {
                    return Check::fail(ID, LABEL, format!(
                        "aggregating an EMPTY selection created {} group(s) — a group that exists with count 0 is a row in a report that does not exist. No rows selected means no groups touched.",
                        table.len()));
                }
            }
            chains += 1;
            input_rows += n as u64;
            kept += s3.len() as u64;
        }
    }
    Check::pass(ID, LABEL, format!(
        "{chains} three-deep chains over {input_rows} row-positions: {kept} survived ({}), {nothing_survived} chains selected nothing at all and stayed empty through filter, gather and aggregate. Composition equals materialize-then-map on every chain — which is the proof that the intermediate copy is unnecessary, not merely expensive.",
        percent(kept, input_rows)))
}

/// 3. aggregate_correct: groups and their aggregates exact, accumulated
///    across batches — including a key that appears in exactly one batch, a
///    NULL key, a group whose values are all null, and batches that select
///    nothing.
pub fn check_aggregate_correct() -> Check {
    const ID: &str = "aggregate_correct";
    const LABEL: &str = "hash aggregate matches reference groups and sums exactly";
    let mut rng = Rng(0xA66_2E6A);

    // hand cases first: each one is a specific way the aggregate goes wrong
    struct HandCase {
        name: &'static str,
        keys: Vec<Option<i64>>,
        vals: Vec<Option<i64>>,
        sel: Vec<u32>,
        why: &'static str,
    }
    let hand = vec![
        HandCase { name: "empty batch", keys: vec![], vals: vec![], sel: vec![], why: "no rows, no groups" },
        HandCase {
            name: "empty selection over a full batch",
            keys: vec![Some(1), Some(2)], vals: vec![Some(10), Some(20)], sel: vec![],
            why: "nothing was selected, so no group exists — not even one with count 0",
        },
        HandCase {
            name: "one row",
            keys: vec![Some(7)], vals: vec![Some(3)], sel: vec![0],
            why: "count 1, sum 3, min = max = 3",
        },
        HandCase {
            name: "a NULL key",
            keys: vec![None, Some(1), None], vals: vec![Some(5), Some(6), Some(7)], sel: vec![0, 1, 2],
            why: "SQL's GROUP BY makes NULL a group: two rows here, and it sorts before every Some(k)",
        },
        HandCase {
            name: "a group whose values are all NULL",
            keys: vec![Some(1), Some(1)], vals: vec![None, None], sel: vec![0, 1],
            why: "count 2 (COUNT(*) counts null rows), nulls 2, sum 0, min and max absent — absent is not 0, and a sum of 0 is not a min of 0",
        },
        HandCase {
            name: "nulls mixed into a group",
            keys: vec![Some(1), Some(1), Some(1)], vals: vec![Some(4), None, Some(6)], sel: vec![0, 1, 2],
            why: "count 3, nulls 1, sum 10, min 4, max 6 — the null is counted and not summed",
        },
        HandCase {
            name: "a selection that skips rows of the same group",
            keys: vec![Some(1), Some(1), Some(1), Some(1)], vals: vec![Some(1), Some(100), Some(2), Some(200)], sel: vec![0, 2],
            why: "only the selected rows contribute: sum 3, max 2. An aggregate that ignores the selection reads rows a predicate rejected",
        },
        HandCase {
            name: "i64 extremes in one group",
            keys: vec![Some(0), Some(0), Some(0)], vals: vec![Some(i64::MAX), Some(i64::MAX), Some(2)], sel: vec![0, 1, 2],
            why: "sum is 18446744073709551616, which does not fit in an i64 — Agg::sum is i128 for exactly this reason, and an i64 accumulator here silently reports a negative total",
        },
        HandCase {
            name: "many keys, one row each",
            keys: (0..16).map(|i| Some(i)).collect(),
            vals: (0..16).map(|i| Some(i * 10)).collect(),
            sel: (0..16).collect(),
            why: "16 groups of one row",
        },
        HandCase {
            name: "keys out of order",
            keys: vec![Some(9), Some(1), Some(5), Some(1)], vals: vec![Some(1), Some(2), Some(3), Some(4)], sel: vec![0, 1, 2, 3],
            why: "the output is ordered by key regardless of arrival order: 1, 5, 9",
        },
    ];
    for case in &hand {
        let mut table = GroupTable::new();
        vectorized::aggregate_batch(&mut table, &case.keys, &case.vals, &case.sel);
        let got = table.finish();
        let want = ref_group_aggs(&case.keys, &case.vals, &case.sel);
        if got != want {
            return Check::fail(ID, LABEL, format!(
                "{}: you produced {} group(s) {}, want {} group(s) {} — {}",
                case.name, got.len(),
                got.iter().map(|(k, a)| format!("{k:?}: {}", agg_str(a))).collect::<Vec<_>>().join(" | "),
                want.len(),
                want.iter().map(|(k, a)| format!("{k:?}: {}", agg_str(a))).collect::<Vec<_>>().join(" | "),
                case.why));
        }
    }

    // ordering: keys ascending, NULL first, always
    let keys = vec![Some(5), None, Some(-3), Some(0), None, Some(i64::MAX), Some(i64::MIN)];
    let vals: Vec<Option<i64>> = (0..keys.len()).map(|i| Some(i as i64)).collect();
    let mut table = GroupTable::new();
    vectorized::aggregate_batch(&mut table, &keys, &vals, &vectorized::all_rows(keys.len()));
    let order: Vec<Option<i64>> = table.finish().into_iter().map(|(k, _)| k).collect();
    let want_order = vec![None, Some(i64::MIN), Some(-3), Some(0), Some(5), Some(i64::MAX)];
    if order != want_order {
        return Check::fail(ID, LABEL, format!(
            "group order is {order:?}, want {want_order:?} — GroupTable::finish is GIVEN and a BTreeMap already orders Option<i64> with None first. A different order means the keys went in somewhere other than the map (or the map is not the map)."));
    }

    // multi-batch accumulation, which is the whole reason `table` is a
    // parameter: a key seen in batch 0 and batch 7 is ONE group
    let (mut runs_done, mut group_total, mut batch_total, mut partial_total) = (0u64, 0u64, 0u64, 0u64);
    let mut unique_key_cases = 0u64;
    for i in 0..20 {
        let n = [37usize, 64, 100, 251, 512][i % 5];
        let (vname, vals) = make_column(&mut rng, n, i);
        if let Err(msg) = audit(&vals, &vname) {
            return Check::fail(ID, LABEL, msg);
        }
        let bs = [1usize, 7, 16, 60, 128][i % 5];
        let bounds = batches(n, bs);
        // the key that appears in exactly one batch, placed in the LAST
        // (possibly partial) batch half the time
        let unique_at = if i % 2 == 0 { Some(n - 1) } else { Some(n / 3) };
        let keys = make_keys(&mut rng, n, 1 + i % 7, unique_at);
        for j in 0..4 {
            let pred = make_pred(&mut rng, &vals, j + i);
            // one table across every batch, exactly as an engine does it
            let mut table = GroupTable::new();
            let mut all_sel: Vec<u32> = Vec::new();
            for (lo, hi) in &bounds {
                let (kb, vb) = (&keys[*lo..*hi], &vals[*lo..*hi]);
                let input = vectorized::all_rows(vb.len());
                let sel = vectorized::filter(vb, &pred, &input);
                if let Err(msg) = check_sel(&sel, &input, vb.len(), &format!("{vname} rows {lo}..{hi}")) {
                    return Check::fail(ID, LABEL, msg);
                }
                vectorized::aggregate_batch(&mut table, kb, vb, &sel);
                for p in &sel {
                    all_sel.push(*p + *lo as u32);
                }
                batch_total += 1;
                if hi - lo < bs {
                    partial_total += 1;
                }
            }
            let got = table.finish();
            let want = ref_group_aggs(&keys, &vals, &all_sel);
            if got.len() != want.len() {
                let gk: Vec<Option<i64>> = got.iter().map(|(k, _)| *k).collect();
                let wk: Vec<Option<i64>> = want.iter().map(|(k, _)| *k).collect();
                let missing: Vec<String> = wk.iter().filter(|k| !gk.contains(k)).map(|k| format!("{k:?}")).collect();
                let extra: Vec<String> = gk.iter().filter(|k| !wk.contains(k)).map(|k| format!("{k:?}")).collect();
                return Check::fail(ID, LABEL, format!(
                    "{vname}, {n} rows in batches of {bs} ({} batches) under {}: {} groups, want {}. Missing: [{}]. Unexpected: [{}]. A key that appears in exactly ONE batch is still a group — key 999999 is planted at row {} for that reason — and a batch whose selection is empty must not create one.",
                    bounds.len(), pred_str(&pred), got.len(), want.len(),
                    missing.join(", "), extra.join(", "), unique_at.unwrap()));
            }
            for (k, (g, w)) in got.iter().zip(&want).enumerate() {
                if g.0 != w.0 {
                    return Check::fail(ID, LABEL, format!(
                        "{vname} under {}: group {k} has key {:?}, want {:?} — output is ordered by key, NULL first",
                        pred_str(&pred), g.0, w.0));
                }
                if g.1 != w.1 {
                    return Check::fail(ID, LABEL, format!(
                        "{vname}, {n} rows in batches of {bs} under {}: group {:?} is wrong — {}. Accumulating across batches means merging into the existing entry, never replacing it.",
                        pred_str(&pred), g.0, agg_diff(&g.1, &w.1)));
                }
            }
            if unique_at.is_some() && want.iter().any(|(k, _)| *k == Some(999_999)) {
                unique_key_cases += 1;
            }
            group_total += got.len() as u64;
            runs_done += 1;
        }
    }
    Check::pass(ID, LABEL, format!(
        "{} hand cases and {runs_done} multi-batch queries ({batch_total} batches, {partial_total} of them partial final batches) group-for-group exact — {group_total} groups total, {unique_key_cases} of the queries had a key that appeared in exactly one batch, and empty selections created no groups. Sums are i128, so a group of two i64::MAX values reports 18446744073709551616 rather than -2.",
        hand.len()))
}

/// 4. compressed_path: the EQUIVALENCE. Aggregating RLE runs and filtering
///    or aggregating dictionary codes must produce results identical to
///    decoding first and running the scalar path. A fast path that
///    disagrees is a correctness bug, and it is graded as one.
pub fn check_compressed_path() -> Check {
    const ID: &str = "compressed_path";
    const LABEL: &str = "execute-on-compressed agrees with the decode-then-execute path";
    let mut rng = Rng(0xC0FF_EE01);

    /* --- one run at a time, where the arithmetic is visible ---------- */
    let runs_hand: Vec<(&str, Option<i64>, u32, &str)> = vec![
        ("an empty run", Some(5), 0, "count == 0 holds NO rows: the aggregate is empty, with no min and no max. A run that describes nothing must not contribute a value to the answer."),
        ("a null run of 0", None, 0, "still no rows"),
        ("one value", Some(5), 1, "count 1, sum 5"),
        ("a constant run", Some(7), 1000, "sum is 7 × 1000 = 7000: one multiply, not a thousand adds"),
        ("a null run", None, 40, "count 40, nulls 40, sum 0, and NO min or max — nulls are counted, never summed, and never compared"),
        ("a negative constant", Some(-9), 300, "sum -2700"),
        ("zero", Some(0), 12, "sum 0, min 0, max 0 — a sum of 0 with a min of Some(0) is a different fact from a sum of 0 with no min at all"),
        ("i64::MAX × 3", Some(i64::MAX), 3, "27670116110564327421 — i64 cannot hold this and i128 can, which is why sum is i128"),
        ("i64::MIN × 2", Some(i64::MIN), 2, "-18446744073709551616"),
        ("four billion sevens", Some(7), 4_000_000_000, "28000000000 — the harness does not expand this run either; the expected value is arithmetic, and if your code loops `count` times it will not finish"),
        ("three billion i64::MAX", Some(i64::MAX), 3_000_000_000, "the extreme case of both: a huge count and a huge value"),
        ("u32::MAX nulls", None, u32::MAX, "4294967295 rows, all null, sum 0"),
    ];
    for (name, value, count, why) in &runs_hand {
        let got = vectorized::run_agg(*value, *count);
        let want = ref_run_agg(*value, *count);
        if got != want {
            return Check::fail(ID, LABEL, format!(
                "run_agg({value:?}, {count}) — {name} — is {}, want {} ({}). {why}",
                agg_str(&got), agg_str(&want), agg_diff(&got, &want)));
        }
    }

    /* --- whole columns: RLE and dictionary vs decode-then-execute ---- */
    let hand_cols: Vec<(&str, Vec<Option<i64>>)> = vec![
        ("empty column", vec![]),
        ("one value", vec![Some(1)]),
        ("one null", vec![None]),
        ("all null, 64 rows", vec![None; 64]),
        ("constant, 64 rows", vec![Some(-3); 64]),
        ("two long runs", { let mut v = vec![Some(1); 50]; v.extend(vec![Some(2); 50]); v }),
        ("runs around a null run", { let mut v = vec![Some(3); 4]; v.extend(vec![None; 40]); v.extend(vec![Some(-3); 4]); v }),
        ("alternating (RLE's worst case)", (0..64).map(|i| if i % 2 == 0 { Some(0) } else { Some(1) }).collect()),
        ("all distinct (dictionary's worst case)", (0..64).map(|i| Some(i as i64 * 3)).collect()),
        ("i64 edges", vec![Some(i64::MIN), Some(i64::MAX), None, Some(0), Some(i64::MAX), None]),
        ("two values and a null", vec![Some(5), None, Some(5), Some(9), None, Some(9)]),
    ];
    let mut cols: Vec<(String, Vec<Option<i64>>)> =
        hand_cols.into_iter().map(|(n, v)| (n.to_string(), v)).collect();
    // the column dictionary encoding exists for: 20 000 rows, a handful of
    // distinct values. The predicate is evaluated once per distinct value,
    // so the cost ratio here is the lesson stated as a count.
    cols.push(("20000 rows, 12 distinct values (skewed)".to_string(), col_few_distinct(&mut rng, 20_000, 12)));
    cols.push(("20000 rows in long runs".to_string(), col_long_runs(&mut rng, 20_000)));
    for i in 0..27 {
        let n = [1usize, 9, 64, 100, 257][i % 5];
        cols.push(make_column(&mut rng, n, i));
    }

    let (mut rows_total, mut runs_total, mut dict_entries, mut dict_rows) = (0u64, 0u64, 0u64, 0u64);
    for (name, values) in &cols {
        if let Err(msg) = audit(values, name) {
            return Check::fail(ID, LABEL, msg);
        }
        let runs = rle(values);
        // the reference: DECODE, then run the scalar path
        let want = ref_agg(values);
        let got = vectorized::rle_aggregate(&runs);
        if got != want {
            return Check::fail(ID, LABEL, format!(
                "{name} ({} rows in {} runs): rle_aggregate on the encoded form gives {}, decode-then-aggregate gives {} — {}. This is an EQUIVALENCE, not an optimisation: a compressed path that disagrees with the decoded path is a wrong answer that arrives sooner.",
                values.len(), runs.len(), agg_str(&got), agg_str(&want), agg_diff(&got, &want)));
        }
        rows_total += values.len() as u64;
        runs_total += runs.len() as u64;

        // count-0 runs spliced in: legal metadata that holds no rows, and
        // must not change the answer
        if !runs.is_empty() {
            let mut padded: Vec<Run> = vec![(Some(-999_999), 0)];
            for &r in &runs {
                padded.push(r);
                padded.push((Some(999_999), 0));
            }
            padded.push((None, 0));
            let got = vectorized::rle_aggregate(&padded);
            if got != want {
                return Check::fail(ID, LABEL, format!(
                    "{name}: after splicing count-0 runs (values -999999 and 999999) into the run list, rle_aggregate gives {} instead of {} — a run of count 0 holds no rows and contributes nothing at all, not even a min",
                    agg_str(&got), agg_str(&want)));
            }
        }

        // the dictionary path, over every predicate shape
        let dict = dict_encode(values);
        let decoded = dict_decode(&dict);
        if decoded != *values {
            return Check::fail(ID, LABEL, format!("HARNESS BUG: dictionary round trip failed for {name} — please report this"));
        }
        for j in 0..8 {
            let pred = make_pred(&mut rng, values, j);
            let mask = vectorized::dict_code_mask(&dict.entries, &pred);
            if mask.len() != dict.entries.len() {
                return Check::fail(ID, LABEL, format!(
                    "{name}: dict_code_mask returned {} booleans for {} dictionary entries — the length IS the cost claim. One evaluation per DISTINCT value ({} of them here) instead of one per row ({}) is the entire reason to filter on codes.",
                    mask.len(), dict.entries.len(), dict.entries.len(), dict.codes.len()));
            }
            for (c, (m, e)) in mask.iter().zip(&dict.entries).enumerate() {
                let want_m = ref_matches(*e, &pred);
                if *m != want_m {
                    return Check::fail(ID, LABEL, format!(
                        "{name}: mask[{c}] is {m} for dictionary entry {e:?} under {}, want {want_m} — the mask answers \"would a row holding this value survive\", with lab 02's three-valued logic unchanged",
                        pred_str(&pred)));
                }
            }
            let all = vectorized::all_rows(dict.codes.len());
            let got_sel = vectorized::dict_filter(&dict, &mask, &all);
            let want_sel = ref_filter(values, &pred, &all);
            if let Err(msg) = check_sel(&got_sel, &all, values.len(), &format!("{name}, dict_filter under {}", pred_str(&pred))) {
                return Check::fail(ID, LABEL, msg);
            }
            if got_sel != want_sel {
                return Check::fail(ID, LABEL, format!(
                    "{name} under {}: dict_filter selected {}, filtering the DECODED values selects {} — identical, or it is a wrong answer. Check that you index the mask by the row's CODE (dict.codes[pos]) and not by the position",
                    pred_str(&pred), sel_str(&got_sel), sel_str(&want_sel)));
            }
            // and the same over a narrowed input selection: a dictionary
            // filter is a filter, so it composes like one
            let narrowed: Vec<u32> = all.iter().copied().filter(|p| p % 3 != 0).collect();
            let got_narrow = vectorized::dict_filter(&dict, &mask, &narrowed);
            let want_narrow = ref_filter(values, &pred, &narrowed);
            if got_narrow != want_narrow {
                return Check::fail(ID, LABEL, format!(
                    "{name} under {} with an input selection of {} positions: dict_filter gave {}, want {} — it must honour the input selection exactly like filter does",
                    pred_str(&pred), narrowed.len(), sel_str(&got_narrow), sel_str(&want_narrow)));
            }
            // aggregate the dictionary at the surviving positions, without
            // decoding: must equal aggregating the gathered decoded values
            let got_agg = vectorized::dict_aggregate(&dict, &got_sel);
            let want_agg = ref_agg(&ref_gather(values, &want_sel));
            if got_agg != want_agg {
                return Check::fail(ID, LABEL, format!(
                    "{name} under {} ({} rows selected of {}): dict_aggregate gives {}, decode-then-aggregate gives {} — {}. Tally the selected rows per CODE, then merge run_agg(entries[c], tally[c]): a per-code count is a run length that is not contiguous.",
                    pred_str(&pred), want_sel.len(), values.len(),
                    agg_str(&got_agg), agg_str(&want_agg), agg_diff(&got_agg, &want_agg)));
            }
            dict_entries += dict.entries.len() as u64;
            dict_rows += dict.codes.len() as u64;
        }
        // an empty selection over a dictionary column aggregates to nothing
        if vectorized::dict_aggregate(&dict, &Vec::new()) != Agg::default() {
            return Check::fail(ID, LABEL, format!(
                "{name}: dict_aggregate over an empty selection must be the empty aggregate (count 0, sum 0, no min, no max) — no rows were selected, so there is nothing to aggregate"));
        }
    }

    /* --- a dictionary with entries no row uses ----------------------- */
    let unused = Dict {
        entries: vec![None, Some(-5), Some(0), Some(5), Some(1000)],
        codes: vec![3, 3, 1, 3],
    };
    let decoded = dict_decode(&unused);
    for pred in [Pred::Ge(0), Pred::IsNull, Pred::Eq(1000), Pred::Between(-5, 5), Pred::IsNotNull] {
        let mask = vectorized::dict_code_mask(&unused.entries, &pred);
        let all = vectorized::all_rows(unused.codes.len());
        let got = vectorized::dict_filter(&unused, &mask, &all);
        let want = ref_filter(&decoded, &pred, &all);
        if got != want {
            return Check::fail(ID, LABEL, format!(
                "a dictionary carrying entries no row uses (entries {:?}, codes {:?}) under {}: you selected {}, want {} — an unused entry may match the predicate without producing a single row, and a mask entry is not a row",
                unused.entries, unused.codes, pred_str(&pred), sel_str(&got), sel_str(&want)));
        }
        let got_agg = vectorized::dict_aggregate(&unused, &got);
        let want_agg = ref_agg(&ref_gather(&decoded, &want));
        if got_agg != want_agg {
            return Check::fail(ID, LABEL, format!(
                "the same dictionary under {}: dict_aggregate gives {}, want {} — {}. Codes 0, 2 and 4 appear in no row, so their entries contribute nothing however well they match.",
                pred_str(&pred), agg_str(&got_agg), agg_str(&want_agg), agg_diff(&got_agg, &want_agg)));
        }
    }

    /* --- the columns nobody can expand ------------------------------- */
    let huge: Vec<(&str, Vec<Run>)> = vec![
        ("4 billion sevens", vec![(Some(7), 4_000_000_000)]),
        ("a billion nulls between two constants", vec![(Some(1), 10), (None, 1_000_000_000), (Some(2), 10)]),
        ("three runs of u32::MAX", vec![(Some(-1), u32::MAX), (Some(2), u32::MAX), (None, u32::MAX)]),
        ("i64::MAX four billion times", vec![(Some(i64::MAX), 4_000_000_000)]),
        ("count-0 runs among huge ones", vec![(Some(999), 0), (Some(3), 2_000_000_000), (None, 0), (Some(4), 1)]),
    ];
    for (name, runs) in &huge {
        let want = ref_rle_agg(runs);
        let got = vectorized::rle_aggregate(runs);
        if got != want {
            return Check::fail(ID, LABEL, format!(
                "{name} ({} runs describing {} rows): rle_aggregate gives {}, want {} — {}. Neither you nor the harness can expand this column: the expected answer is value × count in i128, which is what execute-on-compressed means. (The arithmetic reference used here is audited against full expansion on every column small enough to expand.)",
                runs.len(), runs.iter().map(|(_, c)| *c as u64).sum::<u64>(),
                agg_str(&got), agg_str(&want), agg_diff(&got, &want)));
        }
    }

    Check::pass(ID, LABEL, format!(
        "{} single runs, {} columns and {} unexpandable columns agree with decode-then-execute exactly. RLE: {rows_total} rows summarised through {runs_total} runs ({} rows per run). Dictionary: {dict_entries} predicate evaluations for {dict_rows} rows ({} rows per evaluation) — plus five columns declaring {} rows that were never expanded by either side.",
        runs_hand.len(), cols.len(), huge.len(),
        ratio(rows_total, runs_total.max(1)), ratio(dict_rows, dict_entries.max(1)),
        huge.iter().map(|(_, r)| r.iter().map(|(_, c)| *c as u64).sum::<u64>()).sum::<u64>()))
}

/// 5. storm: 2000 seeded batches through the whole pipeline — chained
///    filters, a hash aggregate accumulated across batches, and both
///    compressed paths — every one of them compared against the reference
///    model. Partial final batches and empty selections are counted and
///    reported, because they are where batched code breaks.
pub fn check_storm() -> Check {
    const ID: &str = "storm";
    const LABEL: &str = "2000 seeded batches, including partial final batches and empty selections";
    let mut rng = Rng(0x5EED_0303);
    const BATCHES: usize = 2000;

    let mut shapes: BTreeMap<&'static str, usize> = BTreeMap::new();
    let (mut done, mut queries, mut partials, mut empties) = (0usize, 0usize, 0u64, 0u64);
    let (mut rows, mut survivors, mut materialized) = (0u64, 0u64, 0u64);
    let (mut runs_touched, mut dict_evals, mut groups) = (0u64, 0u64, 0u64);
    let mut i = 0usize;

    while done < BATCHES {
        let n = [1usize, 2, 17, 64, 129, 256, 501, 1024, 2048][i % 9];
        let bs = [1usize, 7, 16, 64, 256, 512][i % 6];
        // a batch size of 1 is the degenerate case and worth covering, but
        // 2048 batches of one row would eat the entire budget and turn the
        // storm into a scalar test
        let n = if bs == 1 { n.min(32) } else { n };
        let (vname, vals) = make_column(&mut rng, n, i);
        let (fname, filt) = make_column(&mut rng, n, i + 5);
        if let Err(msg) = audit(&vals, &vname) {
            return Check::fail(ID, LABEL, msg);
        }
        if let Err(msg) = audit(&filt, &fname) {
            return Check::fail(ID, LABEL, msg);
        }
        let keys = make_keys(&mut rng, n, 1 + i % 9, Some(i % n));
        let p1 = make_pred(&mut rng, &filt, i);
        let p2 = make_pred(&mut rng, &vals, i + 3);
        *shapes.entry(shape(&p1)).or_insert(0) += 1;
        *shapes.entry(shape(&p2)).or_insert(0) += 1;

        let bounds = batches(n, bs);
        let mut table = GroupTable::new();
        let mut global_sel: Vec<u32> = Vec::new();
        for (lo, hi) in &bounds {
            let (kb, vb, fb) = (&keys[*lo..*hi], &vals[*lo..*hi], &filt[*lo..*hi]);
            let input = vectorized::all_rows(vb.len());
            // chain: filter on one column, then another, then aggregate a
            // third — no intermediate materialization anywhere
            let s1 = vectorized::filter(fb, &p1, &input);
            if let Err(msg) = check_sel(&s1, &input, vb.len(), &format!("{fname} rows {lo}..{hi} under {}", pred_str(&p1))) {
                return Check::fail(ID, LABEL, msg);
            }
            let s2 = vectorized::filter(vb, &p2, &s1);
            if let Err(msg) = check_sel(&s2, &s1, vb.len(), &format!("{vname} rows {lo}..{hi} under {}", pred_str(&p2))) {
                return Check::fail(ID, LABEL, msg);
            }
            let want_sel: Vec<u32> = (0..(hi - lo) as u32)
                .filter(|&p| ref_matches(fb[p as usize], &p1) && ref_matches(vb[p as usize], &p2))
                .collect();
            if s2 != want_sel {
                return Check::fail(ID, LABEL, format!(
                    "batch {done} ({vname} / {fname}, rows {lo}..{hi} of {n}, batch size {bs}) under {} AND {}: you kept {}, the reference keeps {}",
                    pred_str(&p1), pred_str(&p2), sel_str(&s2), sel_str(&want_sel)));
            }
            vectorized::aggregate_batch(&mut table, kb, vb, &s2);
            // late materialization: gather ONCE, at the end of the chain
            let got_vals = vectorized::gather(vb, &s2);
            let want_vals = ref_gather(vb, &want_sel);
            if got_vals != want_vals {
                return Check::fail(ID, LABEL, format!(
                    "batch {done}: gather over the surviving selection gave {}, want {}",
                    vals_str(&got_vals), vals_str(&want_vals)));
            }
            // the compressed paths on this batch's slice
            let runs = rle(vb);
            let got_rle = vectorized::rle_aggregate(&runs);
            let want_rle = ref_agg(vb);
            if got_rle != want_rle {
                return Check::fail(ID, LABEL, format!(
                    "batch {done} ({vname}, rows {lo}..{hi}, {} runs): rle_aggregate gives {}, decode-then-aggregate gives {} — {}",
                    runs.len(), agg_str(&got_rle), agg_str(&want_rle), agg_diff(&got_rle, &want_rle)));
            }
            let dict = dict_encode(vb);
            let mask = vectorized::dict_code_mask(&dict.entries, &p2);
            if mask.len() != dict.entries.len() {
                return Check::fail(ID, LABEL, format!(
                    "batch {done}: dict_code_mask returned {} booleans for {} entries",
                    mask.len(), dict.entries.len()));
            }
            let got_dsel = vectorized::dict_filter(&dict, &mask, &s1);
            if got_dsel != want_sel {
                return Check::fail(ID, LABEL, format!(
                    "batch {done} ({vname}, {} distinct values): filtering CODES under {} after the first predicate gave {}, filtering decoded values gives {} — the two paths must select the same positions",
                    dict.entries.len(), pred_str(&p2), sel_str(&got_dsel), sel_str(&want_sel)));
            }
            let got_dagg = vectorized::dict_aggregate(&dict, &got_dsel);
            let want_dagg = ref_agg(&want_vals);
            if got_dagg != want_dagg {
                return Check::fail(ID, LABEL, format!(
                    "batch {done} ({vname}): dict_aggregate over the selection gives {}, decode-then-aggregate gives {} — {}",
                    agg_str(&got_dagg), agg_str(&want_dagg), agg_diff(&got_dagg, &want_dagg)));
            }

            for p in &s2 {
                global_sel.push(*p + *lo as u32);
            }
            rows += (hi - lo) as u64;
            survivors += s2.len() as u64;
            materialized += got_vals.len() as u64;
            runs_touched += runs.len() as u64;
            dict_evals += dict.entries.len() as u64;
            if hi - lo < bs {
                partials += 1;
            }
            if s2.is_empty() {
                empties += 1;
            }
            done += 1;
        }

        let got = table.finish();
        let want = ref_group_aggs(&keys, &vals, &global_sel);
        if got != want {
            let gk: Vec<String> = got.iter().map(|(k, _)| format!("{k:?}")).collect();
            let wk: Vec<String> = want.iter().map(|(k, _)| format!("{k:?}")).collect();
            let first = (0..got.len().max(want.len())).find(|&k| got.get(k) != want.get(k)).unwrap_or(0);
            return Check::fail(ID, LABEL, format!(
                "query {queries} ({vname} grouped by {} keys, {n} rows in batches of {bs}) under {} AND {}: groups disagree first at index {first} — yours {:?}, reference {:?}. Your keys [{}] vs [{}].",
                keys.iter().collect::<std::collections::BTreeSet<_>>().len(),
                pred_str(&p1), pred_str(&p2),
                got.get(first).map(|(k, a)| format!("{k:?} → {}", agg_str(a))),
                want.get(first).map(|(k, a)| format!("{k:?} → {}", agg_str(a))),
                gk.join(", "), wk.join(", ")));
        }
        groups += got.len() as u64;
        queries += 1;
        i += 1;
    }

    if partials == 0 || empties == 0 {
        return Check::fail(ID, LABEL, format!(
            "HARNESS BUG: the storm generated {partials} partial final batches and {empties} empty selections — it is supposed to generate both. Please report this."));
    }
    let mix: Vec<String> = shapes.iter().map(|(k, v)| format!("{k} {v}")).collect();
    Check::pass(ID, LABEL, format!(
        "{done} batches across {queries} queries model-exact: {rows} rows scanned, {survivors} survived two chained predicates ({}), {materialized} values materialized — and materialization happened once per batch, at the end. {partials} partial final batches, {empties} batches where the selection survived nothing, {groups} groups accumulated across batch boundaries. Compressed paths agreed with decode-then-execute on every batch: {runs_touched} runs summarised {rows} rows ({} rows per run), {dict_evals} dictionary evaluations covered the same rows ({} rows per evaluation). Predicate mix: {}.",
        percent(survivors, rows), ratio(rows, runs_touched.max(1)), ratio(rows, dict_evals.max(1)), mix.join(", ")))
}

/// The full suite, in grading order.
pub fn self_checks() -> Vec<Check> {
    vec![
        check_filter_matches_scalar(),
        check_selection_vector(),
        check_aggregate_correct(),
        check_compressed_path(),
        check_storm(),
    ]
}

/* ------------------------------ wasm ABI ---------------------------- */

#[no_mangle]
pub extern "C" fn ks_run(_in_ptr: u32, _in_len: u32) -> u64 {
    let report = Report { lab: "vectorized", version: 1, checks: self_checks() };
    kslab::emit(&report)
}
